artilleryio/artillery

bin/minigun, lib/commands/index.js, lib/commands/report.js, lib/report/index.html.ejs, package.json
- The command generates a self-contained HTML file with a summary of
stats from the JSON file.
- HTML is written to minigun_report_xxxxxxx.json.html
- Resulting HTML is opened in user's default browser
=> Add initial implementation of `minigun report` (#4)

package.json, test/test.sh
=> Fix coverage check

bin/minigun, lib/commands/run.js
=> Target option

lib/commands/run.js, test/scripts/environments.json, test/test.sh
=> Now errors when no target specified

lib/commands/run.js
Fixes https://github.com/shoreditch-ops/minigun/issues/33
=> Fix: output can be piped

lib/commands/run.js
Support for multiple payloads (to go with: https://github.com/shoreditch-ops/minigun-core/commit/380f5c76f86ea6ca1d14a861bf819e3651373401)
=> Multiple payloads

lib/commands/quick.js, package.json, test/test.sh
=> Contributor stanza entry

lib/commands/run.js
Experimental and subject to change.
=> Processor support

lib/commands/run.js
=> Debugging friendly message shows parsing errors

lib/commands/dino.js
Use the localized year, month, and day modulo the length of the dino art to
select the proper art for the day.
Add brontosaurus and tyrannosaurus.
Potential issue: misalignment to speech bubble.
Hoping no one was feeling strongly about simple dino art.
=> (#29) - One Dino Per Day

.gitignore, lib/commands/run.js, test/scripts/single_payload_object.json, test/test.sh
Fix for #72 . Adjusted tests to cover just fields being specified in json payload with path in command line, and added another for both in the json payload.
=> Issue 72 csv

lib/commands/run.js, lib/report/index.html.ejs
- "Requests completed" -> "Scenarios completed" in HTML reports
- RPS -> RPS sent (the number of requests sent in the last N seconds)
- Requests made -> Requests completed
=> Reporting fixes

package.json, test/test.sh
=> Fix code coverage check

lib/commands/run.js, lib/dist.js, lib/runner.js, lib/worker.js, test/test.sh
Gotta use all of those CPUs! 🔥  🔥  🔥
=> Multicore!

lib/commands/run.js, lib/runner.js
Creating reports should be the responsibility of the code that's wrapping the runner.
=> Emit raw stats from runner

test/test.sh
=> Fix tests for OSX - add -t to mktime

lib/commands/run.js, lib/report/index.html.ejs
To go with: https://github.com/shoreditch-ops/artillery-core/pull/100
=> Report how many of each scenario Artillery launched

lib/index.js, package.json
Fixes #173 
@hassy I think this should do the trick. I'm on Windows so couldn't verify with all the make/test commands. I don't anticipate this breaking anything but you never know! :)
=> Expose commands to Node modules

lib/commands/run.js
=> Warn if running on Node 6.8.1+ and using rampTo

lib/commands/run.js, lib/runner.js, lib/worker.js, test/runner.sh, test/test.sh
=> Add graceful shutdown of main process and workers

lib/runner.js
Fixes https://github.com/shoreditch-ops/artillery/issues/264
=> Clear interval rather than relying on unref()

test/scripts/environments.yaml, test/scripts/hello.json, test/scripts/processor.js, test/test.sh
- Test for scenario level hooks
- Test for rewriting request URLs in hooks
=> Test: add tests for hook functions

bin/artillery, lib/commands/run.js, test/scripts/hello.json, test/scripts/hello_config.json, test/test.bats
`--config <path>` can be used to load the configuration for a test from another file.
=> Add --config parameter for run

bin/artillery, lib/commands/run.js, test/test.bats
Ref: https://github.com/shoreditch-ops/artillery/issues/372
=> feat: Allow for script overrides with the --overrides option

lib/commands/run.js, lib/console-reporter.js
Fixes: https://github.com/shoreditch-ops/artillery/issues/375
=> fix: Fix regression where concurrency is reported in the summary

lib/commands/run.js, lib/runner.js, lib/worker.js
Depends on: https://github.com/shoreditch-ops/artillery-core/pull/211
=> feat: Allow all loaded plugins to cleanup on exit/when interrupted

lib/commands/quick.js
=> fix(quick): Show helpful message when run without target

README.md
Was modified the README because I found a typo error in the first lines.
=> Typo Error on the main README

core/lib/engine_http.js
Fixes https://github.com/shoreditch-ops/artillery/issues/518
=> fix(http): Better detection of an afterResponse hook for callback

core/lib/engine_util.js, package-lock.json, package.json, test/core/run.sh, test/core/scripts/captures_array_random.json
=> fix: Use jsonpath package instead of JSONPath

lib/commands/report.js
Fixes https://github.com/shoreditch-ops/artillery/issues/401
=> fix(report): Remove detailed latency records from the report

core/lib/engine_ws.js
this request is to fix issue #510
=> fix: #510 TypeError occurs with custom function in WS engine

core/lib/engine_util.js, core/lib/runner.js, lib/util.js, test/core/unit/util.test.js, test/testcases/variables-from-external-files.bats
- Make process environment available to virtual users as `$processEnvironment`
- Add support for templates in the `config` section
- Add support for object property lookups in template strings (e.g. `{{ objectVar.attribute }}`)
=> Templating improvements

package-lock.json, package.json
Ref: https://nvd.nist.gov/vuln/detail/CVE-2018-1000620
=> chore: Update Hapi.js to fix hapi > cryptiles CVE-2018-1000620

core/lib/engine_http.js
Refactor the logic that manages how socket connections are created
and managed. With this change, we no longer rely on request.js to
manage it for us, and instead either create a global agent to share
between all VUs, or create an agent for each VU depending on whether
config.http.pool is set.
Ref https://github.com/shoreditch-ops/artillery/issues/90#issuecomment-432994456
=> fix(engine_http): Ensure config.http.pool works as expected

core/lib/engine_util.js, test/core/unit/util.test.js
👋Hey stranger! This a fix for #561 - in which checking a value is equal to 0 isn't working as expected. 
Any problems, just give me a shout!
=> fixes #561 - enable zero value assertions

core/lib/runner.js, lib/util.js
=> fix: Make context functions available when templating $.config

core/lib/engine_http.js, core/lib/engine_util.js, core/lib/runner.js, package-lock.json, test/core/unit/index.js, test/core/unit/interpolation.test.js, test/core/unit/templates.test.js
- $loopElement is now interpolated
- name is now interpolated
- context.funcs.$template() can be used to interpolate any value in before(Request|Scenario) or after(Response|Scenario)
=> allows interpolation of loopElement & name; Adds template for context.funcs

lib/console-reporter.js, lib/util.js, package.json, test/lib/index.js, test/lib/run.sh, test/lib/test_util.js
=> Show elapsed time when printing report to console

core/lib/runner.js
=> allow default engine to be set in 'config' section

.circleci/config.yml, commitlint.config.js, package-lock.json, package.json
Set up [commitlint](https://github.com/marionebl/commitlint#getting-started) with [config-conventional](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional#type-enum).
=> Add commitlint

bin/artillery, test/testcases/errors-and-warnings.bats
=> feat(cli): Complain when an unknown command is used

core/lib/phases.js, core/lib/runner.js, core/lib/stats2.js, lib/console-reporter.js, test/core/index.js, test/core/scripts/concurrent_requests_arrival_count.json, test/core/scripts/concurrent_requests_arrival_rate.json, test/core/scripts/concurrent_requests_multiple_phases.json, test/core/scripts/concurrent_requests_ramp_to.json, test/core/test_concurrent_requests.js
please see https://github.com/artilleryio/artillery/pull/615
=> feat: Add the ability to limit the number of concurrent virtual users

core/lib/engine_http.js, test/core/unit/interpolation.test.js
- Allows the ability to alter functions called within a `loop/over` to setup/teardown specific scenarios
=> feat: Allow interpolation in beforeRequest and afterResponse

bin/artillery, test/testcases/errors-and-warnings.bats
- "--version" does not display "unknown commands"
- always exiting with non-zero code
- more tests
=> fix(cli): Better handling of unknown commands

core/lib/engine_util.js, test/core/unit/templates.test.js
=> fix(util): Handle null values in template()

core/lib/runner.js, core/lib/weighted-pick.js
=> fix(runner): Allow setting scenario weight to zero

core/lib/engine_util.js, test/core/unit/templates.test.js
Fixes https://github.com/artilleryio/artillery/issues/87
=> fix(template): Multiple built-in functions may be used

core/lib/runner.js
This PR adds support for setting scenario weights with variables.
Template strings that set weights may use inline variables from `config.variables` or values from the environment through `$processEnvironment`.
If a weight cannot be parsed as a number it will be set to 0.
=> feat(runner): Allow scenario weights to be set with templates

core/lib/engine_http.js
=> fix(http): Template querystrings set with qs

core/lib/runner.js, core/lib/schemas/artillery_test_script.json, test/core/scripts/before_test.json, test/core/test_capture.js
=> Rebase & merge #625

package-lock.json, package.json
jsonpath = 1.0.2
@commitlint/cli = 8.1.0
=> chore: Update jsonpath and @commitlint/cli to latest

package-lock.json, package.json
This PR fixes an `npm audit` warning.
=> chore: Update csv-parse

lib/commands/quick.js
=> Correct documentation

core/lib/engine_http.js, package.json, test/core/unit/engine_http.test.js
- Add formData support - Request handled it for us behind the scenes, but we
need to do it ourselves with Got
- Add test for using formData
- Add missing test for redirect handling
=> fix(http): multipart form data support

core/lib/engine_ws.js, test/core/run.sh, test/core/scripts/captures_ws.json, test/core/targets/ws_json.js, test/core/test_capture.js
Fixes #800. Retains backwards compatibility with existing send api and will support existing capture api too.
=> feat: add capture support to ws engine

package.json
=> fix: include missing files for publishing

.circleci/config.yml, commitlint.config.js, core/lib/engine_http.js, package.json
https://github.com/artilleryio/artillery/issues/998
=> feat(http): decompress response when gzip=true

core/lib/engine_ws.js
fixes https://github.com/artilleryio/artillery/issues/1021
=> feat(websockets): support "log" action

core/lib/engine_util.js
=> fix: ability to match falsy values

core/lib/engine_http.js
=> fix: reference correct requestParams

core/lib/ssms.js, package.json, test/core/targets/simple.js, test/helpers/sleep.js, test/unit/ssms-basic.test.js, test/unit/ssms-multi-process.test.js, test/unit/ssms-worker.js
Use our own fork of sketches-js until the PR is merged upstream: https://github.com/DataDog/sketches-js/pull/13
=> test(ssms): run SSMS tests as part of the test suite

core/lib/engine_http.js
even if the response is decompressed
=> fix(http): emit "end" event

lib/report/index.html.ejs
=> fix: Update index.html.ejs

lib/artillery-global.js, lib/artillery-worker-local.js, lib/launch-local.js, lib/worker.js, package-lock.json, package.json, test/cli/suggested-exit-codes.test.js, test/scripts/test-suggest-exit-code.js, test/scripts/test-suggest-exit-code.yml
Fixes: https://github.com/artilleryio/artillery/issues/1206
=> fix: propagate suggested exit code from workers to main thread

lib/report/index.html.ejs
- adds a summary table for custom counters
- adds a custom counters at intervals line chart
=> feat(reports): add custom counters charts and summary

core/lib/runner.js, lib/artillery-worker-local.js, lib/cmds/run.js, lib/dist.js, lib/launch-local.js, lib/worker.js, test/core/unit/before_after_hooks.test.js, test/core/unit/index.js
=> fix(core): run before/after hook once

test/unit/ssms-multi-process.test.js
- Increase the number of datapoints to 100k
- Increase number of workers from 4 to 7
- Add sanity checks: max should never be < p99, all values should be positive
=> test(ssms): update test with multiple instances of SSMS

core/lib/runner.js, lib/launch-local.js, lib/worker.js, test/core/unit/before_after_hooks.test.js, test/core/unit/processor.js
so it's loaded once for both workers and main thread's hooks
=> fix: load script processor in runner

lib/launch-local.js, test/core/unit/before_after_hooks.test.js
=> fix: clone payload before passing it to before or after hooks running in the main thread

lib/cmds/aws/create-test-bundle.js, lib/cmds/aws/delete-test-bundle.js, lib/cmds/aws/describe-test-run.js, lib/cmds/aws/list-secrets.js, lib/cmds/aws/list-tags.js, lib/cmds/aws/list-test-bundles.js, lib/cmds/aws/list-test-runs.js, lib/cmds/aws/list-tests.js, lib/cmds/aws/post-note.js, lib/cmds/aws/set-config-value.js, lib/cmds/aws/set-secret.js, lib/cmds/aws/stop-test.js
This wires up all of the commands in Artillery Pro into Artillery v2.
=> feat: wire up all AWS-specific commands from Pro

lib/report/index.html.ejs
Fix security [Code scanning issues](https://github.com/artilleryio/artillery/security/code-scanning) 
`index.ejs` loads scripts without error. Also tested locally with the following file:
``` html 
<!DOCTYPE html>
<html>
<head>
<title>Artillery report</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js"
integrity="sha384-scMuAXtFmPAlw0+pXLvnpHCt6VHh7AknTPdNrwiph5BA6MJWysg5WgSDl7r63txN"
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"
integrity="sha384-v7eExOYhwaHa3+GhP+lHytJsMcidazNdjiaggRhdbvVTVTCjweLpa23t37ZKxaCf"
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js" …
```
=> chore(deps): check integrity of scripts from untrusted sources

lib/report/index.html.ejs
Fixing up remaining styling gremlins.
=> fix: html report styling

core/lib/engine_http.js, package-lock.json, package.json, test/core/unit/engine_ws.test.js
=> dep: update async from v1 to v2

bin/run, lib/telemetry.js, package.json, test/lib/test_telemetry.js, test/testcases/command-run.bats
=> feat(telemetry): don't show notice if ARTILLERY_DISABLE_TELEMETRY is set

README.md
Minor suggestions on README.md 🔨
=> chore(grammar): improve grammar

lib/dist.js, test/cli/probe/index.js, test/core/unit/dist.test.js, test/scripts/with-dotenv/my-vars
=> fix: set maxVusers prop for each running worker

examples/browser-load-testing-playwright/browser-load-test.yml, examples/browser-load-testing-playwright/browser-smoke-test.yml, examples/browser-load-testing-playwright/package.json
Current scripts do not work as they are missing a `flow` property under `scenario`
=> fix: add needed flow prop to scripts

core/lib/phases.js, test/scripts/ramp.json, test/testcases/command-run.bats
Define a linear function f(t) = describing the 'ideal' VUs for a given time 
- Encapsulate it in `arrivalProbability(step)` that returns the probability [0,1] that we need to spawn a new arrival
- We set the interval between arrivals as the biggest one needed to reach `max(rampTo, rampFrom)` throughput
- In each step we `roll` and compare that to the function
closes ART-664
=> simpler rampup logic

packages/artillery/lib/dist.js, packages/artillery/test/unit/dist.test.js
See original report [here](https://github.com/artilleryio/artillery/discussions/1711)
`maxVusers` are less than expected for cases were one or more workers are idle (for example: `arrivalCount` is being used or `arrivalRate` is less than `#workers`)
This is caused because it is being distributed across all workers not only active ones for that phase.
This pr changes `maxVusers` distribution to only take into account workers that generate arrivals.
This means the total `maxVusers` value is going to be respected, but we still can have odd distributions based on expected arrivals, max virtual users, and workers.
For example: `arrivalRate=10, maxVusers=10, workers=7` is not ideal
=> fix(dist): distribute maxVusers value to active workers only

package-lock.json, package.json, packages/artillery-plugin-expect/lib/expectations.js, packages/artillery-plugin-expect/test/index.js, packages/artillery-plugin-expect/test/lib/formatters.js, packages/artillery-plugin-expect/test/run.sh
- Fix turbo
Plugin-expect:
- Fix tests not running (mostly paths?)
- Fix failing tests from using console.log instead of artillery.log
<!-- Closes ART-725 --!>
=> Fix test suite

packages/artillery/lib/telemetry.js, packages/artillery/test/lib/test_telemetry.js
We should disable ip capturing on posthog prior to merging this
```Project Settings -> Data capture configuration -> Discard client IP data```
=> feat: add usage ping if no telemetry is enabled

packages/artillery/lib/create-bom/create-bom.js, packages/artillery/lib/platform/aws-lambda/index.js, packages/artillery/package.json, packages/artillery/test/cloud-e2e/run-lambda.test.js, packages/core/test/core/unit/templates.test.js
=> feat(lambda): install third-party plugins and engines

packages/core/lib/phases.js
Continuation from [this](https://github.com/artilleryio/artillery/pull/1683) PR, as cases where duration=1s were not handled ([original issue](https://github.com/artilleryio/artillery/issues/1682)):
- Fix low worker arrival rate causing arrival periodTick to be Infinity for 1s ramps 
- Take into account arrival adjustment by worker (also for cases where duration=1s). This means total arrivals should be constant is amount of workers change
=> fix rampTo error Infinity interval error

package-lock.json, packages/artillery/test/cli/command-run.test.js
test for https://github.com/artilleryio/artillery/pull/1878
=> test(ramp): add test for 1s duration ramp

packages/artillery-plugin-publish-metrics/lib/newrelic/index.js
As part of creating a new PR to add events to New Relic, I noticed formatting was off on this reporter. 
As this will make the next PR difficult to review, I decided to make a separate PR to fix the formatting here and apply prettier.
=> style: formatting new relic reporter

packages/skytrace/src/commands/ping.ts
- Parse JSON responses and pass them as objects to expectation functions
- Ignore JSON parsing errors unless we actually need to use the response (e.g. to pretty-print or for a JSON-specific expectation)
=> fix(skytrace): improve handling of JSON responses

packages/artillery/bin/run, packages/artillery/lib/cmds/aws/create-test-bundle.js, packages/artillery/lib/cmds/aws/delete-test-bundle.js, packages/artillery/lib/cmds/aws/delete-test-run.js, packages/artillery/lib/cmds/aws/describe-test-run.js, packages/artillery/lib/cmds/aws/list-secrets.js, packages/artillery/lib/cmds/aws/list-tags.js, packages/artillery/lib/cmds/aws/list-test-bundles.js, packages/artillery/lib/cmds/aws/list-test-runs.js, packages/artillery/lib/cmds/aws/list-tests.js, packages/artillery/lib/cmds/aws/post-note.js, packages/artillery/lib/cmds/aws/run-db-migrations.js, packages/artillery/lib/cmds/aws/run.js, packages/artillery/lib/cmds/aws/set-config-value.js, packages/artillery/lib/cmds/aws/set-secret.js, packages/artillery/lib/cmds/aws/stop-test.js, packages/artillery/lib/cmds/dino.js, packages/artillery/lib/cmds/pro/deploy.js, packages/artillery/lib/cmds/pro/subscription.js, packages/artillery/lib/cmds/quick.js, packages/artillery/lib/cmds/report.js, packages/artillery/lib/cmds/run-fargate.js, packages/artillery/lib/cmds/run-lambda.js, packages/artillery/lib/cmds/run.js
=> dep: Update for new @oclif/core APIs

packages/types/package.json
Should trigger release for 0.1.0 of @artilleryio/types.
=> ci: release v0.1.0 @artilleryio/types

packages/types/package.json
=> ci: release v0.1.1 @artilleryio/types

packages/types/package.json
- Trigger a new patch release for `@artilleryio/types` to include #2051
=> ci: release v0.1.3 @artilleryio/types

packages/types/package.json
=> ci: release v0.1.4 @artilleryio/types

packages/artillery/lib/platform/cloud/cloud.js
Displays the test run URL at the end of the run, so users don't have to scroll up to get it. Especially useful for long tests, where it might not even be possible to scroll up.
_Note: As you can see in the screenshot I have the URL printing `onShutdown` after everything, including ensure checks. If desired, I can move that to a different location. Let me know in the review process if there's a preference here._
=> feat(cloud): show test run url at the end of the run too

packages/types/package.json
- #2089 
- #2090
- #2077 
- #2084
=> ci: release v0.1.5 @artilleryio/types

packages/types/package.json
Release with 
- https://github.com/artilleryio/artillery/pull/2122
=> ci(types): release v0.2.0 @artilleryio/types

packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2134
- https://github.com/artilleryio/artillery/pull/2135
=> ci: release v0.2.2 @artilleryio/types

.github/workflows/examples.yml, packages/types/schema/config/phases.js, packages/types/test/engine.arbitrary.test.ts, packages/types/test/examples.test.ts
Just a small PR incorporating a few remaining needed changes from https://github.com/artilleryio/artillery/pull/2083, with a few alterations.
Additionally, https://github.com/artilleryio/artillery/commit/be2da9417924ca43ac2859eb4c8a2b3478fb31fa fixes the Joi schema recently changed, as one of the newly ran examples tests were failing (proving they work 🥳).
---
Note: timeout of `using-data-from-csv` test was also increased, as it was often going close to 10min and sometimes surpassing it, causing unrelated failures.
=> test: improve schema tests

packages/artillery-plugin-memory-inspector/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2155
=> ci: release v1.1.0 artillery-plugin-memory-inspector

packages/types/schema/engines/common.js, packages/types/schema/engines/socketio.js
Missing descriptions/titles for SocketIO engine, to provide proper hover experience, as this is a popular engine.
=> feat(schema): addsocketio meta descriptions

packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2161
- https://github.com/artilleryio/artillery/pull/2154
- https://github.com/artilleryio/artillery/pull/2144
=> ci: release v0.3.0 @artilleryio/types

packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2168
- https://github.com/artilleryio/artillery/pull/2169
=> ci: release v0.4.0 @artilleryio/types

packages/commons/package.json, packages/core/package.json
=> chore: add license declaration to package.json

.github/workflows/npm-publish-skytrace.yml
Similar to https://github.com/artilleryio/artillery/pull/2029, resolves the issue for publish too.
=> ci(publish): add --ignore-scripts to skytrace publish

package-lock.json, packages/artillery/package.json
Increases platform-fargate version with the following features/fixes:
- fix(bom): change wrong variable name
- feat(cli): expose new scenario-name flag
- dep(playwright): increase playwright version in image
=> dep(artillery): update platform-fargate to 2.2.0

package-lock.json, packages/artillery-plugin-publish-metrics/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2211
- https://github.com/artilleryio/artillery/pull/2152
- https://github.com/artilleryio/artillery/pull/2153
- https://github.com/artilleryio/artillery/commit/82cb40bc5ff39e744d09093420b7c79623997527
=> ci: release v2.8.0 artillery-plugin-publish-metrics

package-lock.json, packages/core/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2158
- https://github.com/artilleryio/artillery/pull/2163
- https://github.com/artilleryio/artillery/pull/2101
=> ci: release v2.2.0 @artilleryio/int-core

package-lock.json, packages/artillery-engine-playwright/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2230 -> includes Playwright Breaking change
- https://github.com/artilleryio/artillery/pull/2233
- https://github.com/artilleryio/artillery/pull/2173
=> ci: release v1.0.0 artillery-engine-playwright

package-lock.json, packages/artillery/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2184
- https://github.com/artilleryio/artillery/pull/2212
- https://github.com/artilleryio/artillery/pull/2204
- https://github.com/artilleryio/artillery/pull/2203
- https://github.com/artilleryio/artillery/commit/8b3f0351477709fad018df79efcadbfc7094558c
Plus the following dependency updates with several features/fixes:
- https://github.com/artilleryio/artillery/pull/2244
- https://github.com/artilleryio/artillery/pull/2243
- https://github.com/artilleryio/artillery/pull/2242
- https://github.com/artilleryio/artillery/pull/2241
- https://github.com/artilleryio/artillery/pull/2240
- https://github.com/artilleryio/artillery/pull/2239
=> ci: release v2.0.0-38 of Artillery

packages/types/schema/engines/http.js, packages/types/schema/engines/playwright.js, packages/types/schema/plugins/publish-metrics.js
Solves a few unrelated minor schema issues. Should be merged without squashing, as all changes stand on their own.
=> fix: minor issues with extension schema

package-lock.json, packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2181
- https://github.com/artilleryio/artillery/pull/2270
=> ci: release v0.4.1 @artilleryio/types

packages/artillery/test/cli/command-run.test.js, packages/artillery/test/scripts/scenario-named/scenario.yml, packages/core/lib/runner.js
Reported here: https://github.com/artilleryio/artillery/issues/2313
Messed up originally and should've only updated index when it finds the scenario. 🤦‍♂️ 
=> fix(core): fix scenario-name feature to work with all scenarios

packages/artillery/lib/cmds/run-fargate.js, packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
- Add `--cpu` and `--memory` flags for convenience
- Update the table of valid CPU/memory configurations
Fixes #2280.
=> feat: CPU and memory configuration on Fargate

packages/artillery-plugin-fake-data/package.json
Releases the plugin: https://github.com/artilleryio/artillery/pull/2318
Note: just changed some characters in the `package.json` as a workaround, so it would trigger the workflow to release v1.0.0. 🤞
=> ci: release v1.0.0 artillery-plugin-fake-data

.github/workflows/npm-publish-artillery-types.yml, package-lock.json, packages/artillery-plugin-fake-data/index.js, packages/types/package.json, packages/types/schema/config.js, packages/types/schema/plugins/fake-data.js
Adds dynamic autocompletion for https://github.com/artilleryio/artillery/pull/2318 . This should help users identify the available functions quicker, if they are using the VS Code extension.
=> feat(schema): add artillery-plugin-fake-data to schema

package-lock.json, packages/artillery-plugin-fake-data/package.json
Need to up version so https://github.com/artilleryio/artillery/commit/b4c541e5d9b513af5b8e575730c912706d84b6cb will be available to consume by schema pkg.
=> ci: release v1.0.2 of artillery-plugin-fake-data

package-lock.json, packages/types/package.json
Includes:
- feat(schema): add artillery-plugin-fake-data to schema (https://github.com/artilleryio/artillery/commit/b1b2c8033f7bfa20cdf4ce784756b9a617084c1a)
- feat(schema): implement config.environments schema using pattern (https://github.com/artilleryio/artillery/commit/88412dce403ee2dec2daaa71ba3227ef4f75c937)
- feat(schema): schema for cookies, headers, form of http engine (https://github.com/artilleryio/artillery/commit/00d1028f978dfe2ad849400021350e8d671c6197)
- feat(schema): type schema for keyvalue of ws and socketio (https://github.com/artilleryio/artillery/commit/302d80f08158ccb973b010e82f795eedb1cacf0d)
=> ci: release v0.5.0 @artilleryio/types

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
Datadog does not provide HTTP endpoints for OTel. Traces have to be sent via Datadog Agent.
This change adds Datadog Agent as a sidecar (rather than baking it into the image #2366) with the configuration needed to enable tracing.
DD Agent config based on https://github.com/artilleryio/artillery/pull/2366
=> feat(artillery): add support for Datadog tracing on Fargate

package-lock.json, packages/artillery-plugin-metrics-by-endpoint/package.json, packages/artillery-plugin-metrics-by-endpoint/test/fixtures/scenario.yml, packages/artillery-plugin-metrics-by-endpoint/test/index.spec.js, packages/artillery-plugin-metrics-by-endpoint/test/index.unit.js
There were no tests for the plugin. Adding some.
Unit tests have nearly 100% coverage, so just added one simple acceptance test to make sure it works e2e.
=> test(plugins): add tests for metrics-by-endpoint plugin

examples/soap-with-custom-function/README.md, examples/soap-with-custom-function/package-lock.json, examples/soap-with-custom-function/package.json, examples/soap-with-custom-function/processor.js, examples/soap-with-custom-function/server/MyService.wsdl, examples/soap-with-custom-function/server/app.js, examples/soap-with-custom-function/server/package-lock.json, examples/soap-with-custom-function/server/package.json, examples/soap-with-custom-function/soap.yml
Adds example for using Artillery to test a SOAP service (leveraging custom functions).
=> feat(examples): add example for soap

package-lock.json, packages/core/package.json
Includes:
- [feat(core): error when unknown engine is used in before/after](https://github.com/artilleryio/artillery/commit/4baa50bb4e60dd96f7bee0562c2be9ed6d36cf16)
=> ci: release v2.3.0 @artilleryio/int-core

package-lock.json, packages/artillery-plugin-publish-metrics/package.json
Includes:
- [feat: add smart sampling for OTel tracing](https://github.com/artilleryio/artillery/commit/da207047bba92b472f0218db61c73d8ffb131e7d)
- [fix(publish-metrics): throw caught err in step handler](https://github.com/artilleryio/artillery/commit/67408d15401fdf1ff17aa0b14c50fc254d497519)
- [refactor(publish-metrics): modularise OTel reporter](https://github.com/artilleryio/artillery/commit/e8a69c3d37ada104298a9b70e01cb5a189098672)
=> ci: release v2.10.0 artillery-plugin-publish-metrics

package-lock.json, packages/artillery-engine-playwright/package.json
Includes:
- [feat(playwright): run VUs in new context rather than browsers by default](https://github.com/artilleryio/artillery/commit/c2a675c8a7be2129c7a9d8d1698910a88adc969d)
- [feat(playwright): track HTTP status codes](https://github.com/artilleryio/artillery/commit/0f9e351770d8ebbcc1ab389cac25b41360d54080)
=> ci: release v1.2.0 artillery-engine-playwright

package-lock.json, packages/artillery/package.json
Includes:
- [feat(cli): record publish-metrics reporters usage with posthog](https://github.com/artilleryio/artillery/commit/6fd477f5d0e4284e9479b94f4bca0798a256a011)
- [fix(lambda): require esbuild-wasm conditionally to fix lambda failure](https://github.com/artilleryio/artillery/commit/213bcb56d7acdc8daaaab9f7bc7852abb969face)
- [test(cli): fix validate-script before/after test to not require flow](https://github.com/artilleryio/artillery/commit/653daabc0c0ecd4befda25945a0611d498a72cfa)
- [fix(cli): allow engines without flow in before/after schema](https://github.com/artilleryio/artillery/commit/b140da16d63c27818c404fa732d1178dd7cc682d)
- [fix(fargate): fix configuration for Datadog agent](https://github.com/artilleryio/artillery/commit/fb0b4c6a7023a74db5f6968f17df7fa0d97592d6)
- …
=> ci: release v2.0.4 artillery

.github/workflows/run-tests.yml
Make it easier to run tests against branch, so a PR doesn't need to be created for running tests against experiments/incremental code changes. Especially relevant when we'll have `windows` tests which won't be simple to run locally.
=> ci(tests): add ability to run tests against arbitrary branch

.github/workflows/run-aws-tests.yml
=> ci(tests): change gh var for aws role

packages/artillery-plugin-publish-metrics/lib/open-telemetry/vendor-translators.js
Changing the `attributes` format of the Dynatrace and New Relic reporters tracing feature (introduced in #2418 ) from object:
```yaml
attributes:
testType: load
tool: Artillery
```
to array of strings:
```yaml
attributes:
- "testType:load"
- "tool:Artillery"
```
for consistency reasons, as the equivalent setting for the metrics and events in those reporters uses the string format. 
e.g. New Relic reporter config for metrics and events: 
```yaml
config:
plugins:
publish-metrics:
- type: newrelic
licenseKey: "{{ $env.NR_LICENSE_KEY }}"
region: eu
prefix: "artillery.publish_metrics_plugin."
attributes:
- "testType:LoadTest"
- "tool:Artillery"
event:
accountId: "{{ $env.NR_ACCOUNT_ID }}"
eventType: "Artillery_load_test"
attributes:
- "alertType:info"
- "priority:low"
```
=> refactor(publish-metrics): change vendor attributes format for consistency

package-lock.json, packages/core/package.json
Includes
- https://github.com/artilleryio/artillery/pull/2342
=> ci: release v2.3.1 @artilleryio/int-core

package-lock.json, packages/artillery-engine-playwright/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2425
- https://github.com/artilleryio/artillery/pull/2441
- https://github.com/artilleryio/artillery/pull/2461
- https://github.com/artilleryio/artillery/pull/2455 + https://github.com/artilleryio/artillery/pull/2465
=> ci: release v1.3.0 artillery-engine-playwright

package-lock.json, packages/artillery/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2421
- https://github.com/artilleryio/artillery/commit/257dba8787ee3b3d986cd5aa8a8633a98a3280dd, https://github.com/artilleryio/artillery/commit/614115f25981f322965454f5164fafa65d96914d, https://github.com/artilleryio/artillery/commit/f3ce7e841bd90b2abbda881e40e4184c67b7cfa8, https://github.com/artilleryio/artillery/pull/2459
- https://github.com/artilleryio/artillery/pull/2457
- https://github.com/artilleryio/artillery/commit/3f22c7bf03fb7af727eba52b2473a0e3da2278f6, https://github.com/artilleryio/artillery/commit/b3247ae9a1e71a27e01958be8f4d1c35ac324b5e, https://github.com/artilleryio/artillery/commit/d442d28f289ae7fa243940f03b1ea0cef4db3273
- https://github.com/artilleryio/artillery/pull/2431
- …
=> ci: release v2.0.5 artillery

.github/workflows/npm-publish-artillery.yml
Fixes issue https://github.com/artilleryio/artillery/actions/runs/7786609380/job/21231942244 🤦‍♂️
=> ci(publish): fix publish worklfow script

.github/workflows/npm-publish-artillery.yml
Reverts [temporary patch](https://github.com/artilleryio/artillery/pull/2472) to expected behaviour.
=> ci(publish): revert to only publishing when package json changes

package-lock.json, packages/types/package.json
Includes:
- [feat(schema): add useSeparateBrowserPerVU](https://github.com/artilleryio/artillery/commit/78d6a0d605e0709030a3151db37b1ddd781d6762)
- https://github.com/artilleryio/artillery/pull/2343
- https://github.com/artilleryio/artillery/pull/2441
- https://github.com/artilleryio/artillery/pull/2418
=> ci: release v0.6.0 @artilleryio/types

.eslintignore, .github/workflows/run-aws-tests.yml, package-lock.json, packages/artillery-engine-playwright/package.json, packages/artillery-engine-playwright/test/fargate.aws.js, packages/artillery-engine-playwright/test/fixtures/processor.js, packages/artillery-engine-playwright/test/fixtures/processor.ts, packages/artillery-engine-playwright/test/fixtures/pw-acceptance.yml, packages/artillery-engine-playwright/test/index.test.js
- Adds JS tests
- Adds TS tests
- Adds fargate test using TS
Note: review commit by commit.
=> test(playwright): add tests for artillery engine playwright

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
=> fix: pick up test ID override on Fargate

package-lock.json, packages/artillery-plugin-publish-metrics/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2505
=> ci: release v2.12.0 artillery-plugin-publish-metrics

package-lock.json, packages/artillery-engine-playwright/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2493
- https://github.com/artilleryio/artillery/pull/2488
- https://github.com/artilleryio/artillery/pull/2492
=> ci: release v1.4.0 artillery-engine-playwright

package-lock.json, packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2493
=> ci: release v0.7.0 @artilleryio/types

package-lock.json, packages/artillery/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2489
- https://github.com/artilleryio/artillery/pull/2485
- https://github.com/artilleryio/artillery/pull/2488
- https://github.com/artilleryio/artillery/pull/2499 + https://github.com/artilleryio/artillery/pull/2504
And:
- https://github.com/artilleryio/artillery/pull/2507
- https://github.com/artilleryio/artillery/pull/2506
=> ci: release v2.0.6 artillery

package-lock.json, packages/core/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2499
- https://github.com/artilleryio/artillery/pull/2522
=> ci: release v2.4.0 @artilleryio/int-core

package-lock.json, packages/artillery-plugin-publish-metrics/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2514
- https://github.com/artilleryio/artillery/pull/2533
- https://github.com/artilleryio/artillery/pull/2481
=> ci: release v2.13.0 artillery-plugin-publish-metrics

package-lock.json, packages/artillery/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2526
- https://github.com/artilleryio/artillery/pull/2522
- https://github.com/artilleryio/artillery/pull/2481
- https://github.com/artilleryio/artillery/pull/2534
- https://github.com/artilleryio/artillery/pull/2531
And:
- https://github.com/artilleryio/artillery/pull/2536
- https://github.com/artilleryio/artillery/pull/2537
- https://github.com/artilleryio/artillery/pull/2538
=> ci: release v2.0.7 artillery

package-lock.json, packages/artillery-plugin-memory-inspector/package.json
Includes:
- https://github.com/artilleryio/artillery/commit/ca451f730cbb7649c08e4c1711616930a611b902
=> ci: release v1.1.1 artillery-plugin-memory-inspector

package-lock.json, packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2525
=> ci: release v0.8.0 @artilleryio/types

packages/artillery/lib/launch-platform.js
Depending on the exact time a test completes (all workers finish) there may be more than one time period that hasn't been reported yet.
This PR makes sure that when we exit (flushAll is set), we emit reports for all outstanding periods.
=> fix: emit stats event for all periods for which there's data

package-lock.json, packages/artillery/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2585
- https://github.com/artilleryio/artillery/pull/2581
- https://github.com/artilleryio/artillery/pull/2565
And:
- https://github.com/artilleryio/artillery/pull/2586
=> ci: release v2.0.8 artillery

package-lock.json, packages/artillery-plugin-publish-metrics/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2607
- https://github.com/artilleryio/artillery/pull/2610
- https://github.com/artilleryio/artillery/pull/2555
- https://github.com/artilleryio/artillery/pull/2601
- https://github.com/artilleryio/artillery/pull/2597
=> ci: release v2.14.0 artillery-plugin-publish-metrics

package-lock.json, packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2555
- https://github.com/artilleryio/artillery/pull/2596
- https://github.com/artilleryio/artillery/pull/2607
=> ci: release v0.9.0 @artilleryio/types

package-lock.json, packages/artillery/package.json
Includes:
- https://github.com/artilleryio/artillery/commit/51886179a997f50786237dcdb73619de0710476c
- https://github.com/artilleryio/artillery/commit/3cec221bbdaa2d991f9fc0948ab380ea0befba88
- https://github.com/artilleryio/artillery/commit/3cec221bbdaa2d991f9fc0948ab380ea0befba88
- https://github.com/artilleryio/artillery/pull/2604
- https://github.com/artilleryio/artillery/pull/2597
- https://github.com/artilleryio/artillery/commit/0e0a3b5cca7bc04523287f4f09a0eac4ce03ccfd
- https://github.com/artilleryio/artillery/pull/2549
- https://github.com/artilleryio/artillery/pull/2613
And:
- https://github.com/artilleryio/artillery/pull/2615
- https://github.com/artilleryio/artillery/pull/2616
=> ci: release v2.0.9 artillery

examples/browser-load-testing-playwright/flows.js, examples/browser-playwright-reuse-typescript/e2e/helpers/index.ts, packages/artillery-engine-playwright/test/fixtures/processor.js, packages/artillery-engine-playwright/test/fixtures/processor.ts, packages/artillery/test/cloud-e2e/fargate/fixtures/adot/flow.js
Change in Artillery Website broke some examples and tests.
=> test(playwright): fix all references to docs page link in website

packages/artillery/lib/cli/common-flags.js
=> Clarify --tags flag

packages/artillery/lib/cmds/run.js
Add telemetry so we can track usage.
=> chore(telemetry): add telemetry for container lambda

.github/workflows/docker-ecs-worker-image.yml
Follow up of https://github.com/artilleryio/artillery/pull/2729, workflow is failing.
=> ci(docker): fix typo in workflow

package-lock.json, packages/artillery-engine-playwright/Dockerfile, packages/artillery-engine-playwright/package.json, packages/artillery/lib/platform/aws-ecs/worker/Dockerfile
Update engine to https://github.com/microsoft/playwright/releases/tag/v1.44.0
Doesn't seem to have any Breaking changes that would affect us.
=> dep(playwright): update Playwright to v1.44.0

.github/workflows/create-release-pr.yml, package-lock.json, packages/artillery/package.json
Include https://github.com/artilleryio/artillery/tree/main/packages/artillery-plugin-slack in the distribution.
=> feat: include Slack integration

package-lock.json, packages/types/package.json
Includes:
- https://github.com/artilleryio/artillery/pull/2658
- https://github.com/artilleryio/artillery/pull/2688
=> ci: release v0.10.0 @artilleryio/types

.github/workflows/npm-publish-artillery-types.yml
Fixes copy/paste bug introduced in https://github.com/artilleryio/artillery/pull/2651.
=> ci(types): fix publish workflow for types

packages/artillery/test/cloud-e2e/lambda/lambda-ensure.test.js
Adds ensure test, similar to Fargate.
=> test(lambda): add ensure test for lambda

packages/artillery/lib/cmds/run.js
Validation for the flag to prevent any typos in values.
=> fix(cli): add validation for platform flag

.github/workflows/run-distributed-tests.yml
https://github.com/artilleryio/artillery/pull/3247 didn't account for a change in directory that's done in this step.
=> ci(test): fix relative path to npm script

.github/workflows/run-tests.yml, .github/workflows/scripts/get-all-packages-by-name.js, packages/commons/package.json
Parallelises test suite through Github Actions. This makes it easier to parse through failures in logs.
=> ci(test): parallelise test suite using gh actions

package-lock.json, packages/artillery-engine-playwright/Dockerfile, packages/artillery-engine-playwright/package.json, packages/artillery/lib/platform/aws-ecs/worker/Dockerfile
Update to newest Playwright release (https://github.com/microsoft/playwright/releases/tag/v1.45.3). Includes a bug fix for tracing.
=> dep(playwright): update Playwright to v1.45.3

packages/artillery/lib/cmds/run.js, packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js, packages/artillery/lib/util/prepare-test-execution-plan.js
Send additional metadata to Artillery Cloud when recording is enabled.
=> feat: send additional metadata to Artillery Cloud

packages/artillery/lib/cmds/run-fargate.js, packages/artillery/lib/cmds/run.js
=> feat: update status page link

package-lock.json, packages/artillery-engine-playwright/Dockerfile, packages/artillery-engine-playwright/package.json, packages/artillery/lib/platform/aws-ecs/worker/Dockerfile
Update to the latest version of Playwright.
Follows same pattern as https://github.com/artilleryio/artillery/pull/3363/files
Why the change is needed, and any details to help code reviewers.
-->
=> chore: Update Playwright to 1.49.0 version

package-lock.json, packages/artillery-engine-playwright/package.json, packages/artillery/lib/platform/aws-ecs/worker/Dockerfile
=> dep: update to Playwright v1.49.1

package-lock.json, packages/artillery-plugin-expect/package.json, packages/artillery/package.json, packages/commons/package.json
Node v22 is current active LTS release
=> feat: update recommended Node version to v22.13.0

package-lock.json, packages/artillery-engine-playwright/package.json, packages/artillery/lib/platform/aws-ecs/worker/Dockerfile
Upgrade to latest Playwright release.
=> feat: Upgrade Playwright to v1.51.0

packages/artillery/lib/cmds/run-fargate.js, packages/artillery/lib/cmds/run.js, packages/artillery/lib/platform/cloud/cloud.js
This will help debug issues with connectivity.
=> feat: print error when unable to connect to cloud

package-lock.json, packages/artillery-engine-playwright/package.json, packages/artillery/lib/platform/aws-ecs/worker/Dockerfile
Upgrade to latest version of Playwright.
=> dep: upgrade to Playwright v1.52.0

packages/artillery/lib/platform/aws-ecs/legacy/util.js
Add the following regions to the list of regions where Fargate tests may be run:
- us-gov-east-1, us-gov-east-2 - AWS GovCloud
- il-central-1 - Israel
- cn-north-1, cn-northwest-1 - China
Related: https://github.com/artilleryio/artillery/discussions/3513
=> feat: add more AWS Fargate regions

packages/artillery/lib/platform/az/aci.js
=> fix(azure): argument must be cast to string

packages/artillery/lib/platform/az/aci.js, packages/artillery/lib/platform/az/aqs-queue-consumer.js
=> fix: Azure message processing throughput

packages/artillery/test/cloud-e2e/fargate/memory.test.js
The test has been failing intermittently.
=> test: increase amount of memory for memory use stress test

packages/artillery/test/cloud-e2e/fargate/memory.test.js
=> test: increase resources for both configs

packages/artillery/lib/platform/aws-ecs/worker/check-license.mjs, packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker, packages/artillery/lib/platform/az/aci.js
=> feat: Azure ACI updates

packages/core/lib/engine_http.js
=> refactor(core): avoid promisifying async "function" steps

package-lock.json, packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js, packages/artillery/lib/platform/aws-lambda/index.js, packages/artillery/lib/platform/aws-lambda/lambda-handler/a9-handler-index.js, packages/artillery/lib/platform/cloud/api.js, packages/artillery/lib/platform/local/worker.js, packages/artillery/lib/stash.js, packages/artillery/package.json
Add support for using Artillery Cloud Stash API.
=> feat: Artillery Cloud Stash API integration
