lib/report/index.html.ejs

MM is a two digit month representation (e.g. August -> "08"), whereas mm
is a two digit minute representation.

:bug: Format string conflates dates/minutes

---

bin/minigun
lib/commands/dino.js
lib/commands/quick.js
lib/commands/run.js
package.json

This came up while @xicombd was writing something using minigun.
It is unshibelike to not say anything, but this PR adds the `--quiet`/`-q` option to the command line, which can also be passed through javascript.
Although it might not be so useful on the command line, scripts using minigun as a library will want to stop it from writing to stdout.

Quiet option

---

lib/commands/run.js
package.json

Why this:
```json
{
"config": {
"target": "http://127.0.0.1:3000",
"phases": [
{ "duration": 120, "arrivalRate": 10 }
],
"defaults": {
"headers": {
"content-type": "application/json",
"x-my-service-auth": "987401838271002188298567"
}
}
},
"scenarios": [
{
"flow": [
{ "get": {"url": "/test"}}
]
}
]
}
```
If you can have this:
```yml
config:
target: 'http://127.0.0.1:3000'
phases: 
- duration: 120
arrivalRate: 10
defaults: 
headers: 
content-type: application/json
x-my-service-auth: '987401838271002188298567'
scenarios:
- flow:
- get:
url: "/test"
```
> Some people can't type more than three double quotes per minute
>
> -- <cite>Winston S. Churchill</cite>

Support yaml

---

README.md

ab is old, single threaded and very basic, wrk allows some basic lua scripting as well and I find it much more stable. 
`ab` also has the issue that on certain OS X installations it is broken.

Recommend wrk instead of ab for http testing.

---

.eslintrc

It was making `npm run is_linted` fail:
```
➜  minigun git:(master) npm run is_linted
> minigun@1.3.2 is_linted /Users/xicombd/Code/minigun/minigun
> find . -name '*.js' | grep -v node_modules | grep -v coverage | xargs eslint
/Users/xicombd/Code/minigun/minigun/node_modules/eslint/lib/config.js:76
throw e;
^
YAMLException: Cannot read config file: /Users/xicombd/Code/minigun/minigun/.eslintrc
Error: duplicated mapping key at line 35, column 29:
"handle-callback-err": 2,
^
```

Remove duplicated key from .eslintrc

---

lib/commands/run.js
lib/report/index.html.ejs

Relates to #34 
Adds markers to each time based graph at the beginning of each phase. Labels are defined in the config, e.g.
```json
{
"config": {
"target": "http://localhost:3000",
"phases": [{
"duration": 20,
"arrivalRate": 10,
"label": "ramp 10"
},
{
"duration": 20,
"arrivalRate": 20,
"label": "ramp 20"
}],
"defaults": {}
},
"scenarios": [{
"flow": [{
"get": {
"url": "/"
}
}]
}]
}
```
Phases that aren't marked with a label get annotated with the phase number, e.g. 'Phase 1', 'Phase 2' etc.

Addition of phase information to reports

---

lib/report/index.html.ejs

As requested in #41, uses `name` instead of `label`

Use phase 'name' key instead of 'label'

---

.artilleryrc
README.md
lib/commands/quick.js
lib/commands/run.js
package.json
test/test.sh

This allows you to specify config default values for the `run` command using a `.minigunrc` file on your home folder or in any other [location supported by `rc`](https://github.com/dominictarr/rc#standards). 
The included `.minigunrc` serves as an example and is used for the test as well.
Let me know what you think :)

Use rc for default config values

---

lib/commands/run.js

Invalid file format message was always complaining about JSON even if the file was YAML.

Invalid file message is now adjusted to the file format.

---

bin/artillery
lib/commands/quick.js
lib/commands/run.js
package.json
test/test.sh

This PR improves `artillery quick`:
- add "-c" flag to specify a fixed number of arrivals
- add "-n" flag to specify the number of messages to send

quick mode improvements

---

bin/artillery
lib/commands/quick.js
lib/commands/run.js
package.json
test/test.sh

"-n" not always defined unless there's a longhand alternative. This
seems to be an (intermittent?) issue in Commander:
https://github.com/tj/commander.js/issues/541

Fix quick mode - need a longhand variant for "-n"

---

lib/commands/run.js
lib/report/index.html.ejs
test/test.sh

Hey Hassy,
When a report is run for a test that produces some number of errors, the percentages shown for different flows start to look a little weird:
I think the percentages should be derived from all scenarios created, not just those completed, which should make the percentages add back up to 100%.
What do you think?

Report percentage by scenarios created not completed

---

lib/runner.js
lib/worker.js

When a worker terminates unexpectedly, we should not continue.
Also a possible cause of: https://github.com/shoreditch-ops/artillery/issues/238

Fix: shutdown when a worker process terminates unexpectedly

---

lib/worker.js
test/scripts/files.json
test/test.sh

After https://github.com/shoreditch-ops/artillery-core/pull/148 landed in master, it's now time to add support to the CLI.
As a reference, the copy-pasted intended usage:
Include them in config:
```yaml
config:
files:
- "@./path/to/file"
- "@../path/to/other/file"
```
Reference them from within your scenario
**Single File**
```yaml
post:
url: "/test"
body: "@./path/to/file"
```
**Multiple Files - Multipart Form**
```yaml
post:
url: "/test"
formData:
foo: "@./path/to/file"
bar: "@../path/to/other/file"
```

Add file upload feature

---

lib/commands/run.js

- Refactor `run()` breaking it up into several smaller functions
- Handle `config.environments`

Refactor: break up run() into several functions

---

.artilleryrc
lib/commands/run.js
test/test.bats

- The -o flag is now required for a JSON log file to be created
- Rename the default file format option to "logFilenameFormat"

feat: Create a JSON log file only if requested

---

lib/commands/run.js
test/scripts/pets.txt
test/scripts/single_payload_options.json
test/test.bats

NOTE: Re-opening after rebasing. Addresses feedback from other PR.
As some of our payload files contain data with commas, which are passed to the endpoint on the URL, this is an expedient way to make the payload processing in Artillery more flexible.
Verified this will work for us.
Thanks,
~Greg

feat: Allow for options to be passed through via config.payload.options

---

lib/runner.js
test/testcases/errors-and-warnings.bats

Wait for continuous high CPU usage of N seconds before printing the warning (10s by default).

feat: Wait for continuous high CPU usage before warning

---

lib/commands/run.js
lib/util.js

Add "-v" option to "run" command to allow for scenario variables
to be set at run time, for example:
```
artillery run -v color=red,height=120 test.yaml
```
Makes variables "color" and "height" available in the script (with
the respective values of "red" and "120").

feat: Allow for scenario variables to be passed in with "-v" option

---

core/lib/engine_util.js

The number of iterations may now be set with something like:
```
- flow:
- loop:
- log: "Hello world!"
count: "{{ iterations }}"
```

fix: Allow for templates to be used in loop's count

---

core/lib/engine_util.js

The first argument to template() may be undefined if the calling
code passes in the result of reading a non-existing attribute on
an object like here:
https://github.com/shoreditch-ops/artillery/blob/715371ae517d728eca972a6220728359ca6a49ac/core/lib/engine_socketio.js#L234
Fixes https://github.com/shoreditch-ops/artillery/issues/495

fix: Handle undefined argument to template()

---

core/lib/engine_socketio.js
core/lib/engine_ws.js

Since the logic in actually handled by the `utils` engine, I've just added the `whileTrue` property in step definition.
Must fix #468.

Add whileTrue condition in WebSocket and Socket.io engines.

---

lib/commands/run.js

Add `maxErrorRate` option to `config.ensure` to make Artillery exit with
a non-zero status code if the ratio of failed to successful scenarios
is higher than the value specified.
For example, exit with non-zero code if any errors occur:
```yaml
config:
ensure:
maxErrorRate: 0
scenarios:
```
Both OS-level errors such as ECONNRESET, and errors returned from
hooks will be taken into account.

feat(run): Add config.ensure.maxErrorRate option

---

core/lib/engine_util.js

Fixes https://github.com/shoreditch-ops/artillery/issues/549
Extractors will need to be refactored to allow for an error to be returned (and subsequently made visible to the user). Failing silently and returning an empty string when the JSONPath expression is invalid is not ideal.

fix(util): Handle cases when the JSONPath expression is not valid

---

core/lib/engine_http.js

Added a check in Artillery HTTP Engine to check for ignore value
If the check is true, then Artillery will proceed with next request
This allows invalid requests to be skipped rather than exit scenario

Allows skipping of request in beforeRequest - #564

---

lib/commands/run.js
package.json

Add `skipEmptyLines`, `cast`, `skipHeaders` and `delimiter` options.
- `skipEmptyLines` (default `true`) -- skip any empty lines in the CSV file
- `cast` (default `true`) -- convert values to native types (e.g. numbers)
- `skipHeader` (default `false`) -- skip the header row when populating variables
- `delimiter` (default `,`) -- set the delimiter

feat: Add extra options for config.payload

---

lib/dispatcher.js
lib/util.js
test/scripts/hello.json
test/scripts/processor.js

1. Export `template()` from `artillery/utils`
2. Experimental: create a global `artillery` object to be used by plugins, custom JS code, and engines.

Make template() available externally

---

lib/util.js
test/scripts/local-urls.csv
test/scripts/multiple_payloads.json
test/testcases/command-run.bats

Payload `path` field may be templated, with access to
- $environment -- containing the name of the environment (if set)
- $processEnvironment -- containing the process environment vars
Ref: https://github.com/shoreditch-ops/artillery/issues/505

feat: Allow for payload path to be templated

---

.circleci/config.yml

- Use Node.js 10
- g++ and jq are already pre-installed in the image
- Get rid of pushd/popd - the default shell is "sh" which does not
support those

ci: Fix CircleCI build configuration

---

core/lib/phases.js
test/core/unit/phases.test.js

The rampTo option can now also be set to a value lower than arrivalRate, and it will ramp from the starting arrivalRate down to the rampTo value.
Implements #205

feat: Support ramp-down as well as ramp-up

---

lib/commands/run.js

CSV parsing was breaking with version 4.3.0 of csv-parse, which introduced some validation refinements. Changing the from_line parameter to 1 when not skipping headers, and 2 when skipping headers fixes the problem. Fixes #622

Fix to start csv-parse from_line parameter from 1.

---

README.md
lib/commands/run.js

```js
from_line: typeof payloadSpec.skipHeader === true ? 2 : 1
```
The above always evaluates to `1`, as `typeof payloadSpec.skipHeader` is `boolean`, which doesn't `=== true`.

 fix: Remove faulty "typeof"

---

README.md

This PR adds the Spectrum link which currently does not exist on the docs.

docs: Add Spectrum link

---

core/lib/engine_http.js

- Make sure all redirects are followed by default (not just after `GET` requests)
- Debug output improvements - show cookies, only show capture info if defined

HTTP engine improvements

---

core/lib/engine_http.js

Fixes #512
The solution runs a simple sanity check on the URL after all templating has been done and custom functions that may re-write the URL have been run. See the bug report for reasons why this specific error isn't caught by existing error-handling code.
Always passing the callback to `request.js` which is another possible solution has the drawback of `request.js` loading the entire response into memory (to provide as an argument to the callback function), which is problematic with many concurrent requests which return large response payloads.

fix(http): Return an error early if URL is not valid

---

core/lib/runner.js
core/lib/schemas/artillery_test_script.json
test/core/scripts/before_test.json
test/core/test_capture.js

Adds a "Before" section to the artillery test schema. This feature enables configuring a flow which will run once before the test and capture variables into the context that can be used in later scenarios in the test.
This is a very useful feature as it allows the user to easily add a before requests flow using the syntax of artillery, without having to load external JS files.
A relevant use-case that this feature can solve: https://github.com/artilleryio/artillery/issues/629

feat: Run a before test flow

---

core/lib/engine_http.js
core/lib/engine_socketio.js
core/lib/engine_util.js
test/core/scripts/captures.json
test/core/scripts/captures3.json

Allow the user to turn off the default strict-capture behavior,
which aborts the scenario if any of the capture actions fail.
Non-strict capture can be set by either:
- Setting config.defaults.strictCapture to false to make all
captures non-strict
- Setting "strict" attribute on a capture action to false, to
make that particular capture non-strict.
Fixes #812

feat(http): allow non-strict captures

---

package-lock.json
package.json

These updates resolve vulnerabilities present in dot-prop and lodash within this project, and resolves related issue #865 .
As a result of updating @commitlint, Husky required an upgrade as well. The changes made to the commit lint hook reflect the changes necessary as a result of this major bump. 
No core functionality has changed, and tests still pass as expected. Please advise what I should bump the version to, and if that should be done in this pull request.

fix: resolve dot-prop and lodash vulnerabilities

---

core/lib/engine_http.js
package.json
test/tinyproxy.conf

Add support for using forwarding proxies via HTTP_PROXY and HTTPS_PROXY
environnment variables like Request.js [1]
1. https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

feat(http): add support for forwarding proxies

---

core/lib/engine_util.js
package-lock.json
package.json
test/core/unit/templates.test.js
test/core/unit/util.test.js

See #904 
This PR fixes #904
- the first two commits clean existing tests (remove dead code and add missing dep, that was creating warnings)
- then I have a test commit
- then the fix
- ✅ I read contributing.md
- ✅ Commit should respect given convention 
- ✅ I make the PR small (but if you want the first two commits 4acd507 and 624abad, which are fix / clean of the actual tests before any work, I can split the PR)
- ✅ I did some test
- ✅ I opened an issue, as requested

Fix: prevent sanitize form converting null/undefined to ''

---

lib/commands/index.js
lib/commands/run.js
lib/dispatcher.js

- Add support for adding extension points via the global `artillery` object
- Add a `beforeExit` extension point to run code before Artillery exits
- Add a way to suggest Artillery's exit code from plugins
- Remove current `config.ensure` code (to be replaced by a plugin)

feat: allow plugins to run code before Artillery exits

---

core/lib/engine_socketio.js

To the best of my knowledge, the current implementation doesn't allow us to use different config (ie.: query params) in each test connection. This can prevent certain use cases from being properly supported as commented here: https://spectrum.chat/artillery-io/general/how-to-add-dynamic-query-string-to-target-in-ws-engine~d86f0f53-506f-42ee-93de-b30aa2f01f09
With this PR, you could do the following:
``` yaml
config:  
socketio:
transports: ["websocket"]
...
scenarios:
- name: Socket connection
engine: socketio
socketio:    
query: "userId={{$randomString()}}" # each connection will have a different user id
flow:
- think: 3
```

Allow scenarios to override socketio configs

---

core/lib/phases.js
test/core/unit/phases.test.js

Allows for (eg: ENV-based) phase configuration values which are strings
by checking their definedness and casting them to numbers as necessary.
Previously, implementation was breaking under some (eg: rampTo) string
value configs. Addresses GH #977

feat: cast string-valued phase configs

---

.dockerignore
Dockerfile

This pull request contains a few updates to the Dockerfile for Artillery:
- The base image has been updated to `node:12-alpine`, since Artillery now requires Node.js 12 and above.
- The `.dockerignore` file has been modified to exclude all files except the ones needed for the Artillery CLI to work inside the Docker image. This helps keep the built image as slim as possible and avoids accidentally copying unnecessary files over when they're added in the future.
- The build process was slightly modified to first copy the `package.json` and `package-lock.json` files into the image, then install dependencies. This will help speed up the build process by avoiding running `npm install` if the dependencies haven't changed.

Update Dockerfile to use Node.js 12 and some cleanup to help build process

---

.circleci/config.yml
.circleci/docker-build.sh
.circleci/npm-publish.sh

This pull request contains a few updates to the CI scripts to help automate the Docker build and NPM publishing workflows.
By default, CircleCI doesn't execute workflows for any pushed tags unless specified, so pushing any Git tags never triggered the CI process. It's now updated to trigger those workflows when any tag starting with `v`, which is the current naming convention for releases.
I also updated the Docker build and NPM publish scripts that get executed with these CI workflows:
- The conditional check for `CIRCLE_BRANCH` was removed, since tagged pushes won't have this information.
- The command to check that the Docker image is working properly was changed, since `artillery quick` doesn't seem to valid command anymore. It's now going to use the `artillery dino` command, just to …

Update CI scripts for building Docker image and publishing NPM package

---

.circleci/config.yml

A few days ago I submitted an update to CircleCI to build and publish a Docker image and NPM package when a version is tagged (#997). However, I noticed this wasn't working as intended because I misunderstood how CircleCI runs different workflows.
This pull request fixes the issue by splitting up the CircleCI configuration into two separate workflows:
- When pushing any branch, it will run the `test` workflow, which will only run the test suite. CircleCI will run this workflow for all branches, and ignore all tags (which is CircleCI's default behavior).
- When pushing any tag starting with `v`, it will run the `publish` workflow. It will first run tests, and if they pass it will build and publish the Docker image for that version, and also publish the package on NPM. CircleCI will only …

Split CircleCI into two separate workflows for tests and publishing

---

core/lib/engine_util.js
test/core/unit/templates.test.js

Preserves a situation where we have keys that could contain periods in it.
For example, `{ "hello.world": 1 }` would be templated as `{ "hello": { "world": 1 } }`, which could cause problems. One scenario I've encountered is when this effect mangles the request body for a request that expects keys that contain periods.

fix(template): retain keys with periods

---

core/lib/engine_util.js
test/core/unit/templates.test.js

Apologies for bringing in a PR so soon. This PR resolves an edge case when the path is something like `hello.world["hello.world"]`.
Beforehand, the template `{ hello: { world: { "hello.world": true } } }` would generate the object `{ hello: { world: { "hello.world": true } }, "hello.world": true }`. This fix ensures that the key isn't duplicated.

test(template): add case for when the dotted key appears as actual path

---

lib/console-reporter.js

This fixes #982 and further log errors from `report` empty object.

fix: set default to empty object

---

core/lib/engine_util.js

Fix #1027: Don't fail capture on false boolean values

---

core/lib/runner.js
core/lib/schemas/artillery_test_script.json
test/core/scripts/after_test.json
test/core/test_capture.js

There is already a (seemingly undocumented) way to run a flow before the actual test scenarios using the "[before](https://github.com/artilleryio/artillery/issues/842#issuecomment-765496311)" hook, which was added in https://github.com/artilleryio/artillery/commit/37bbe3b9319bf60063db32dbed369f57dd8d102f.
This MR addresses a similar need that seems to be requested by others as well (see https://github.com/artilleryio/artillery/issues/842#issuecomment-803206740 and https://github.com/artilleryio/artillery/issues/751) by adding a way to run a flow after the test scenarios have finished running. This can, for example, be useful to clean up test-only related data,

feat: allow running an after test flow

---

core/lib/runner.js
test/core/scripts/after_test.json
test/core/test_capture.js

this fixes a bug introduced by merging #1084 where the context vars from a scenario were not passed to the `after` hook, breaking the tests

fix: pass scenario context vars

---

.eslintrc
bin/artillery
lib/cmds/report.js
lib/cmds/run.js
lib/telemetry.js
lib/util.js
package-lock.json
package.json
test/lib/index.js
test/lib/test_telemetry.js
test/lib/test_util.js

This PR adds telemetry functionality to collect anonymous usage information to better understand how artillery is doing in the wild. It is enabled by default, and it can be disabled by setting the `ARTILLERY_DISABLE_TELEMETRY` environment variable to `true`. 
A warning message is printed the first time a test is run and on the help screen.
setting the `ARTILLERY_TELEMETRY_DEBUG` environment variable to `true` will print the telemetry data instead of sending it. 
What it collects:
- Artillery version
- OS identifier
- whether artillery runs in CI or not
What it does **not** collect:
- Anything that's personally identifiable, like IP addresses 
it currently sends data only when a test is run.
more details here: https://artillery.io/docs/resources/core/telemetry.html

Feat add telemetry

---

core/lib/engine_http.js

Steps to reproduce
1. yaml set headers and processor
2. beforeRequest function executed
3. first argument(requestParams) has headers
Actual result
- requestParams.headers is always empty
Expected result
- requestParams.headers include ones from yaml headers spec
Possible application
- ~pass csv payload to processor~ (this can be done with context)
1. ~yaml load user ids from csv~
2. ~yaml set headers with user id variable~
3. ~beforeRequest processor gets dynamic user id and produce JWT~
4. ~target application (requiring JWT auth) handle dynamic users~
- pass global default headers to processor
Description
- open issues seems not be to relative.
- git blame shows those lines were from quite old code. so I think that this might be an unexplored bug.
- after this modification, npm run test …

fix: pass spec headers to beforeRequest processors

---

core/lib/engine_util.js

Changed `params.match.lenth` to `params.match.length`

Fixed typo in engine_util.js

---

Dockerfile

This pull request updates the `Dockerfile` to update the `PATH` inside of the image when building the image and include the Artillery binary path.  This will allow for an easier way to access the binary when using the image directly, such as in a CI/CD environment.

Set path to Artillery when building Docker image

---

test/lib/test_util.js

`updateArtilleryConfig` is currently spied instead of being stubbed: running tests would affect the actual configuration file

fix: replace spy with stub in test utils

---

.circleci/config.yml

fixes the publish workflow by [explicitly adding](https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag) filter tags to its jobs so it runs the required additional steps when a tag is pushed

fix(ci): add filters to publish workflow

---

lib/cmds/run.js

This adds the ability to run a script in "solo" mode, i.e. run a script with just one virtual user.
This is handy for debugging and testing your test scripts, and also for running functional tests. At the moment, you have to include a separate environment definition, with a phase definition that creates exactly one user.
This also means that it's now possible to run just a scenario on its own (no `config` required), with something like:
```sh
artillery run --target http://my-api.acme-corp.dev --solo scenario1.yml
```

feat(run): add solo mode

---

core/lib/engine_ws.js
test/core/unit/engine_ws.test.js

adds support for a new action in a websocket flow that can be used to customise each websocket connection parameters. 
`connect` _must_ be the first step in the flow and it can be a string, a function or an object.
**as a string:**
```yaml
config:
target: "ws://target:8080"
variables:
token:
"abcde"
scenarios:
- name: "WS Test"
engine: ws
flow:
- connect: "{{ target }}/?token={{ token }}"
- send: "hello"
```
**as a function:**
```yaml
config:
target: "ws://target:8080"
processor: "./functions.js"
variables:
token:
"abcde"
scenarios:
- name: "WS Test"
engine: ws
flow:
- connect:
function: "connectHookHandler"
- send: "hello"
```
the function should have the following signature:
```javascript
function connectHookHandler(params, context, callback) {
// same as the example above
params.target …
```

Websocket "connect" action

---

core/lib/engine_util.js
test/core/scripts/loop_nested_range.json
test/core/test_loop.js

Original issue link: #683
This allows complex response objects to be used directly as loop over targets without the need to restructure them or otherwise duplicate values as top level context.vars properties. My use case merges data from multiple scenario steps to be used in a later loop, and allowing this greatly simplifies the logic.

feat: allow looping over object paths

---

.eslintrc
package.json

- Add Prettier + config
- Add npm scripts to lint + check style
Prettier/eslint are configured to stay close to current code style.
Will apply style/lint fixes in a separate PR.

style: add code formatting & linting rules

---

lib/cmds/quick.js
lib/cmds/run.js

This PR adds `quick` back to Artillery v2.
The `-r` option has been removed as the use-case for it in the context of `quick` is rare - unless `-c` is used with a high value, what ends up being tested is the TCP stack, not performance of the backend server.

feat: add quick command

---

.circleci/config.yml
core/lib/runner.js
lib/launch-local.js
lib/worker.js
package.json
test/core/plugins/artillery-plugin-httphooks/index.js
test/core/plugins/artillery-plugin-httphooks/package.json
test/core/unit/before_after_hooks.test.js
test/testcases/plugins/plugins-processor.test.js
test/testcases/plugins/processor.js
test/testcases/plugins/script.json

fixes a regression bug introduced in `2.0.0-8` and reverted in `2.0.0-9` where plugins could not attach functions to the test script if `processor` and `before` were both present

fix: processor and plugins with 'before' hook 

---

lib/dist.js
test/core/unit/dist.test.js
test/core/unit/index.js

fixes `arrivalCount` by assigning it to one worker and replacing it with a pause phase for the others.

fix: execute arrivalCount phase in one worker

---

lib/cmds/run.js

Add tracking for:
* whether third-party engines are used
* if so, which open-source / community engines are used
* whether the ensure plugin is used

feat: track usage of built-in & community engines

---

lib/dist.js
test/core/unit/dist.test.js

fix: keep original load phase name when replacing arrivalCounts with pauses

---

core/lib/engine_ws.js
test/core/index.js
test/core/test_ws_match_wait.js

It does not seem possible to `capture` a message from the server except as a response to a send.  This PR makes an alias of the `send` step called `wait` purely for readability purposes and also checks for a `payload` before sending anything, allowing a solo `capture` step to be defined.
The current ws engine also has an undocumented `match` feature, but you cannot use it without at least an empty capture.  This PR checks for either `capture` or `match` being defined rather than just `capture`.
e.g.
```
flow:
- send:
payload:
type: handshake
capture:
json: "$.user_id"
as: "user_id"
- think: 2
- send:
payload:
type: text
text: "unittest-20220420"
match:
json: "$.type"
value: typing
- wait:
match: 
json: "$.text"
value: what is your name?
- think: 2
- send:
payload:
type: text
text: "{{ …
```

feat: allow solo capture step with ws engine

---

package-lock.json
package.json

The upgrade broke a test [1]. Reverting until we can look into the
underlying issue and fix it properly.
This reverts the change in e51e3a5369f8632480dae4a39a993adb34cd5748.
1. E.g.: https://app.circleci.com/pipelines/github/artilleryio/artillery/526/workflows/8e7b73cc-f0e3-4438-b6fe-5fe0cf4cc292/jobs/1062?invite=true#step-109-48

dep: downgrade async from 2.6.4 to 1.5.2

---

lib/cmds/run.js

The "histograms" field contains data for the raw DDSketch object,
which is unnecessary for intended uses of JSON reports, and can
signficantly inflate the size of generated JSON, especially for
longer tests.
The "summaries" field contains percentile values for time windows
calculated from those histograms.

feat: remove "histograms" field from JSON report

---

lib/cmds/probe.js
package-lock.json
package.json

* Pretty-print JSON when `-q` is used
* Add support for querying HTML/XML with Cheerio
* `-q` will try to guess whether to run JMESPath or Cheerio. `--jmespath` and `--cheerio` are also supported.

artillery probe improvements

---

core/lib/is-idle-phase.js

When the `arrivalRate` is set to a value lower than the number of workers, the distribution logic will create workers with `arrivalRate: 0`.  Because the default isIdlePhase logic only checks for `arrivalRate === 0` to cull workers, if a `rampTo` is defined and set to a value greater than the number of workers, any workers that have a starting `arrivalRate: 0`, but a `rampTo > 0` will get culled, along with their distributed load.
This is most noticeable with `arrivalRate: 1` as all workers except the initial one will be culled, resulting in just one worker, with a distributed value (1/workers) for `rampTo`
This simple fix checks that no `rampTo` is defined if `arrivalRate === 0`

fix: check for rampTo when starting arrivalRate is 0 for a worker

---

lib/cmds/run.js
package-lock.json
package.json
test/scripts/with-dotenv/my-vars
test/scripts/with-dotenv/with-dotenv.yml
test/testcases/command-run.bats

Add a `--dotenv` flag which can be used to load environment variables from a `.env` file.

feat: add --dotenv flag

---

core/lib/readers.js
core/lib/runner.js

Setting the "name" property on a CSV payload will make all rows available to the VU, under the variable with that name. The type of the value is an array of objects, where each object has properties corresponding to the "fields" spec of the CSV payload.
Example:
```yaml
config:
target: https://www.artillery.io
payload:
- path: ./request-response.csv
name: data
fields: [url, code]
plugins:
expect: {}
scenarios:
- flow:
- loop:
- get:
url: "{{ $loopElement.url }}"
followRedirect: false
expect:
statusCode: "{{ $loopElement.code }}"
over: "data"
```

feat: add ability to make all rows in a CSV payload available to each VU

---

core/lib/engine_http.js
test/scripts/with-dotenv/my-vars

This PR is a follow up to https://github.com/artilleryio/artillery/commit/9791e3aace66bd58416a6e6ee509f8192240ad9d.
- Refactor the code that processes responses to **not** callback to `async`
- Account for the case when we have a redirect with a request that does not require a response processor

fix(http): fix multiple callbacks on redirects

---

lib/platform/aws-lambda/index.js
lib/platform/aws-lambda/lambda-handler/index.js

- Send back a message when the Artillery process can't be started
- Replace `exec` with `spawn` and print Artillery's output as it becomes available to make debugging easier

fix: improve error handling in Lambda workers

---

core/lib/engine_http.js

fix(http): prevent multiple callbacks when a capture/match fails

---

core/lib/engine_http.js

Almost the same thing as https://github.com/artilleryio/artillery/pull/999
Since we are using `decompressResponse` and `on('data')` is added to it, `on('end')` should also be executed on the decompressResponse... but it is being executed on raw response causing a race condition, so when response end happens, response data didn't happen yet, and we end up with empty body string.
This PR makes the handle response use decompressResponse for everything instead of mixing raw response object and the decompress response object.
Fixes https://github.com/artilleryio/artillery/issues/1562

fix(http): handle response decompression properly

---

core/lib/engine_http.js
test/core/unit/engine_http.test.js

This PR improves our handling of redirect chains.
We currently run response processors on every response, so e.g. a `capture` can fail for the first response but succeed for the second response, leading to multiple callbacks to `async.waterfall` being invoked.
This PR changes the logic to only run response processors on the last request in the chain.
It also refactors the code to get rid of `async.waterfall`.

fix: redirect chains with capture/afterResponse hooks

---

core/lib/engine_http.js
test/core/test_cookies.js

config.http.cookieJarOptions may be set to customize the behavior
of the underlying ToughCookie instance.
See available options in ToughCookie docs:
https://github.com/salesforce/tough-cookie#cookiejarstore-options

feat: allow customization of cookie parsing behavior

---

core/lib/phases.js
lib/dist.js
test/core/unit/dist.test.js
test/core/unit/phases.test.js

See #1589.
Setting an arrival rate lower than the workers being user to run the test, resulted in `rampTo` property being distributed across all workers alongside an incorrect value for `arrivalRate`
This generated an unexpected distribution of requests:
The root cause for this is that having a `rampTo` and no `arrivalRate`, defaulted to `arrivalRate` being 1.
Example:
using `arrivalRate:1; rampTo:25` and running with 7 workers resulted in:
arrival rate distribution for each worker:
```
[
1, 0, 0, 0, 0, 0, 0
]
```
rampTo distribution for each worker:
```
[
4, 4, 4, 4, 3, 3, 3
]
```
When this got to the execution logic, arrival rate was being updated to 1 [here](https://github.com/artilleryio/artillery/blob/master/core/lib/phases.js) causing the initial load to be higher than expected, so …

fix: rampTo behaviour when arrivalRate is less than amount of workers

---

test/testcases/command-run.bats

Compare values to expected total and use 20% as threshold instead of comparing multiple workers vs single workers results.
We are currently running on [`Medium`](https://circleci.com/docs/configuration-reference/#docker-execution-environment) instances with two cores

test: fix flaky ramp up test

---

core/lib/is-idle-phase.js
core/lib/runner.js
test/core/unit/dist.test.js

Stat aggregation waits for all workers to emit the `stats`, but sleeping workers did not.
If this happened in the last phase of the test, there was a race condition where one possible scenario was the test ending before final report was printed.
Added emit to sleeping worker phases, refactored `isIdlePhase` so that sleeping workers are not taken into account as needed workers to build report.
- Short tests are going to emit the final report properly as we get rid of the race condition where report aggregation and app shutdown are competing
- Short tests are going to finish sooner (3-4s in my machine but its tied to number of workers)
Closes ART-642

fix: test with no explicit phases do not create final report in distributed mode

---

test/scripts/ramp.json
test/testcases/command-run.bats

Update script to reflect a case which caused previous versions to send abnormal traffic (v2.0.0-22 for example)
Check against that particular case so it can run independently of ramp probability

fix flaky test 

---

lib/console-reporter.js

This fixes the issue where Artillery reports an elapsed time that's longer than the actual running time of all VUs in the test.
This is particularly noticeable for short tests (say under 30s) running on AWS Lambda with a large number of workers. The time it takes to spin everything up for the test can be considerably longer than the running time of VUs, making the reported elapsed time particularly surprising.

fix(console-reporter): count elapsed time from first recorded metric

---

lib/platform/aws-lambda/index.js
lib/queue-consumer/index.js

Create a pool of SQS consumers instead of just one. This leads to a speed up when processing messages in load tests with many (50+) workers.

feat: use a pool of SQS consumers

---

packages/artillery/test/cli/run-lambda.test.js

fix typo on lambda test
- lambda runs are throwing an error but it wasn't getting caught in CI
- `A Lambda function has exited with an error. Reason: ArtilleryError` (but was still printing the summary)
- source: `an update to int-core on main hasn't been published to npm`
When that is fixed this should run properly

test(lambda): fix test check

---

packages/artillery/lib/platform/aws-lambda/index.js

Fixes #1681 
Thank you willjk!

chore: switch to 'invoke' as 'invokeAsync' has been deprecated

---

packages/artillery/lib/platform/aws-lambda/index.js

Lambda:
Now follows `memory-size` obtained from user (still defaults to 4096 if no option present).
```
artillery run
--platform aws:lambda 
...
--platform-opt memory-size=2048 hello.yaml
```
Results in the following lambda properties:

fix(lamda): replace hardcoded memorySize with actual parameter

---

packages/artillery/lib/platform/aws-lambda/index.js

- Tested default values ok
- Throws `InvalidParameterValueException` exception when  params do not exist on aws

fix(lamda): convert security-group-ids and subnet-ids strings to arrays

---

.github/workflows/npm-publish-artillery.yml

Existing CircleCI-based workflow won't work with the new monorepo
structure anymore, as it relies on pushing a tag, and is not
monorepo-aware.
This action will run when all of the following conditions are met:
1. Branch is "main"
2. Commit message starts with: "ci: release v", e.g.: "ci: release v1.2.3"
3. The commit modifies packages/artillery/package.json

Package publishing with GitHub Actions

---

packages/artillery/lib/dist.js
packages/artillery/test/cli/command-run.test.js
packages/core/lib/phases.js

Refactor rampTo logic to be deterministic. This means: no more probability is used.
Total requests are now equal to: duration * (rampto+arrivalRate)/2
Arrivals for each second of a phase are calculated beforehand and ticks adjusted to reach desired throughput.
Arrivals are distributed evenly across all workers.
Explanation: given a second where 4 workers generate 5 arrivals:
- Each worker:
-   gets 1.25 'arrivals' for that period
-   sets the current arrival as 1 (as .XX arrivals are not a thing)
-   based on the pending 0.25 each worker determines if it needs to add an extra arrival:
rest >= 0.25 -> worker1 bumps rate by one
rest >= 0.50 -> worker2 bumps rate by one
rest >= 0.75 -> worker3 bumps rate by one
So every 'extra' arrival results in a worker taking 'ownership' of it. Again, the …

refactor(ramp): deterministic version

---

packages/core/package.json

To be honest I'm not 100% sure this is the right change, but when installing artillary globally (in my CI), it errors out with 
```
error Couldn't find any versions for "commons" that matches "*"
```
I cannot imagine that you really wanted to load [this library](https://www.npmjs.com/package/commons), but rather reference your own.

fix: update 'commons' dependency to '@artilleryio/int-commons'

---

packages/artillery-plugin-expect/lib/expectations.js
packages/artillery-plugin-expect/test/index.js

I've added an additional expectation case/keyword for expect plugin named `notStatusCode`. It checks if response status code is different than the one/s specified.
This was done to address the #1522 in the issue tracker.
In some cases users want to test that the returned status code is different than certain status code/s, rather than equal to one.
It was done by creating a new `expectNotStatusCode` function in the file where other expectations are created, and exporting it with them. It follows the same 'template' as other expectation functions - returns the `result` JS object that has `expectation`, `ok`, `expected` and `got` properties. 
Since this function is very similar to `expectStatusCode` one, the code is repetitive and could be extracted into a separate function that would be …

Issue 1522 expect plugin feature

---

package-lock.json
packages/artillery/package.json

Removing oclif/dev-cli as it's no longer supported by the authors. This is preventing from me being able to import this library within my organization.
All tests pass!
```
npm run test
> artillery@2.0.0-29 test
> export ARTILLERY_TELEMETRY_DEFAULTS='{"source":"test-suite"}' && tap --no-coverage --timeout=300 test/unit/*.test.js test/cli/*.test.js && bash test/lib/run.sh && node test/testcases/plugins/*.test.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
PASS  test/unit/ssms-buckets.test.js 1 OK 9.723ms
PASS  test/unit/dist.test.js 13 OK 10.251ms
SKIP  test/cli/run-lambda.test.js > no tests found 226.087ms
PASS  test/cli/command-report.test.js 1 OK …
```

fix: removed deprecated package oclif/dev-cli

---

packages/core/lib/engine_http.js

This PR fixes issue #1741. 
The `requestInfo` object which is logged by the `debug` function was not templating the querystring. 
I have simply added the templating function to the part of the code that checks for the existence of `qs` in order to add it to `requestInfo`. This templating function is exactly the same that gets used for templating the main code.
Because this was just an output from debug, I have not added an automated test case for it. 
I have recreated the setup from the issue above locally and verified that `DEBUG=http` now outputs the templated string correctly.

fix: show templated qs in debug output

---

packages/core/lib/engine_http.js
packages/core/test/core/unit/engine_http.test.js

The issue was that we were computing the url after setting the cookies if it was templated. This led to the cookies being set on '' domain in the cookie jar leading to it not being set on the request properly. The fix is to move the logic of url computation before setting the cookies. Tests are also added for the same so that we can detect if it would break in future due to code changes.
Fixes #1824

fix: Cookies will work when url is a $loopElement

---

packages/core/lib/engine_http.js

Ref: https://github.com/artilleryio/artillery/issues/1799
The end event handler does not seem to be fired for requests in a redirect chain unless a data handler is attached.

fix(http): set a data handler to make the end event handler fire

---

packages/artillery/lib/dist.js
packages/artillery/test/unit/dist.test.js

Ref #1221
This is a fix for a bug where the payload would get copied for each worker, and therefore each CSV row will get duplicate calls.
In my case, it meant that, when running artillery on unique historical data, it would create 1 new request and hit cache from the rest of the workers.
It would be nice to have this bug at least documented in docs, but I noticed that arrival rates are already divided between workers, so in the same place, the payload could be divided as well.
I have split this task into 2 commits:
* First refactoring the `diviedWork` functionality so that it's more readable and adding the ability to more easily update it without changing it's behavior.
* Then, adding the functionality for dividing payload between workers.

fix: Distribute csv payload across workers

---

packages/artillery/lib/report/index.html.ejs

Show `count` instead of `ms` as y-axis title for counter charts in HTML reports

fix: y-axis title for counter charts

---

packages/artillery-plugin-publish-metrics/README.md
packages/artillery-plugin-publish-metrics/index.js
packages/artillery-plugin-publish-metrics/lib/newrelic.js
packages/artillery-plugin-publish-metrics/lib/newrelic/README.md
packages/artillery-plugin-publish-metrics/lib/newrelic/index.js
packages/artillery-plugin-publish-metrics/test/config-newrelic-api.yaml

New Relic target for `artillery-publish-metrics` plugin. Supports sending metrics to New Relic through **Metric API**. 
`NewRelicReporter` class that has the plugin `config` from test script and `events` as properties. On every `'stats'` event it takes metrics from the `stats` object, formats and packs them into `HTTP POST` request in format recognised by New Relic Metric API, and sends the request using `got`  library. 
Configuration options for users are:
- `licenseKey` -- license key must be provided,
- `region` -- two regions available for New Relic, `us` and `eu`, defaults to `us`. Each region has its own endpoint so it is required to set region as `eu` if users New Relic account hosts data in the EU data center.
- `prefix` -- prefix for metric names created by Artillery; defaults to …

feat: new relic publish metrics plugin target

---

packages/artillery-plugin-apdex/index.js
packages/artillery-plugin-apdex/package.json
packages/artillery-plugin-ensure/index.js

Add support for Apdex [1] scores to Artillery.
- Threshold may be set via `config.apdex.threshold`
- Each HTTP request is compared against the threshold and classified as "satisfied", "tolerated" or "frustrated"
- Total number of each type of request is reported via `apdex_satisfied`, `apdex_tolerated`, and `apdex_frustrated` metrics
- Apdex score is calculated and reported at the end of the test run, along with a summary ("good" / "fair" / "poor")
- `ensure` checks may use the `apdex` variable in threshold & condition expressions
1. https://en.wikipedia.org/wiki/Apdex

feat: add initial version of apdex plugin

---

packages/artillery/lib/platform/aws-lambda/index.js

`platformOpts.lambdaRoleArn` always returns undefined. Test scripts always try to create or reuse the default Lambda role. The user-specified Lambda role needs to be fetched from the `platformConfig`.

fix(artillery): get lambdaRoleArn from platformConfig

---

package-lock.json
packages/artillery/lib/cmds/aws/run.js
packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/platform/aws-ecs/ecs.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/lib/platform/aws/aws-ensure-s3-bucket-exists.js
packages/artillery/lib/platform/aws/aws-get-account-id.js
packages/artillery/lib/platform/aws/constants.js
packages/artillery/package.json

This PR adds support for scaling out & running distributed load tests using AWS ECS - with either [serverless Fargate](https://aws.amazon.com/fargate/) or classic ECS/EC2.
The new `artillery run:fargate` command takes an Artillery YAML script, plus optional `--region` and `--count` flags and runs the test in the specified region using `count` load generators. For example:
```
artillery run:fargate my-script.yml --region us-east-1 --count 50
```
Supported AWS regions:
- `us-east-1`
- `us-west-1`
- `eu-west-1`
- `eu-central-1`
- `ap-south-1`
- `ap-northeast-1`
A service-linked IAM role is created for ECS/Fargate tasks: https://github.com/artilleryio/artillery/compare/feat/ecs-fargate-support?expand=1#diff-6317e683cf78993a2d259330f80089ea7ac4bdca8f18a572b99a9ec778833b66R85
All permissions …

feat: ECS/Fargate support for distributed testing

---

packages/artillery-plugin-metrics-by-endpoint/README.md
packages/artillery-plugin-metrics-by-endpoint/index.js

Resolves #1945
Adds 2 new configuration options for the `metrics-by-endpoint` plugin; `stripQueryString` and `ignoreUnnamedRequests`. Both of these should help in reducing the number of unique metrics being produced by the plugin for larger more complex test suites.

Feat: Add new configuration to metrics-by-endpoint

---

packages/artillery/lib/platform/cloud/cloud.js

This PR fixes a behaviour in Artillery Cloud whereby "Untitled Test" appears for a few seconds when the test starts, by sending the test metadata together with the `testrun:init` event.
Notes:
- In doing so, we are also able to remove the `testrun:addmetadata` event, which is no longer needed, since it's sent in the init;
- Additionally, Artillery Cloud already sets `status` to `INITIALIZING`, so the `changestatus` event is unneeded.
This was tested against a new version of Artillery Cloud expecting the new metadata information to be sent, and is working appropriately.

fix(cloud): send metadata with testrun init event

---

.github/workflows/docker-publish-artillery.yml

Tag Docker images built for versioned releases as `latest`.

ci: tag Docker images with latest for versioned releases

---

packages/artillery-plugin-metrics-by-endpoint/README.md

To keep in line with other plugins, the documentation should be on the website, to prevent drift in documentation.

docs(plugins): move documentation for metrics-by-endpoint to website

---

packages/core/package.json

The `socket.io` package is only used by tests.

dep(core): move socket.io to devDependencies

---

packages/artillery/lib/cmds/run.js
packages/artillery/lib/util.js
packages/artillery/test/cli/command-run.test.js
packages/artillery/test/cli/variables-from-external-files.test.js
packages/artillery/test/scripts/scenario-config-different-folder/__processor__/index.js
packages/artillery/test/scripts/scenario-config-different-folder/config/config-processor-backward-compatibility.yml
packages/artillery/test/scripts/scenario-config-different-folder/config/config.yml
packages/artillery/test/scripts/scenario-config-different-folder/scenario.yml
packages/artillery/test/scripts/scenario-payload-with-envs/config/artillery-config.yml
packages/artillery/test/scripts/scenario-payload-with-envs/data/my-data.csv
packages/artillery/test/scripts/scenario-payload-with-envs/scenario.yml

Fixes https://github.com/artilleryio/artillery/issues/1961
This was happening because checkConfig gets called twice when you pass in a scenario + config. In that situation, if you have `environments`, the first time `checkConfig` gets called, it correctly creates the `payload` in the root `config` and replaces those paths. 
However, it doesn't do the same to `config.environments.payload`. So the second time `checkConfig` is called, the `_.merge` overrides the payload path with the `config.environment.payload` unresolved path, causing the issue.
The PR addresses that by ensuring that it no longer gets called twice.
This was tested with the test scripts provided in the issue (very helpful), against Artillery Local.
Two things are missing:

fix(artillery): update payload path when using environments

---

packages/artillery/lib/platform/cloud/cloud.js

- Show the value of `requestId` field in the response if there
- `_event()` does not throw anymore so that we can centralize error logging
- Got's default behavior of throwing on 4xx & 5xx responses is now turned off so that we can access the response when we need to

feat: include unique request ID in error messages for Cloud

---

packages/artillery-plugin-publish-metrics/lib/newrelic/README.md
packages/artillery-plugin-publish-metrics/lib/newrelic/index.js
packages/artillery-plugin-publish-metrics/test/config-newrelic-api.yaml

Events feature for the New Relic reporter of `artillery-publish-metrics` plugin. Supports sending events marking the start and the end of a test to New Relic through **Event API**.
To handle sending events to New Relic's Event API, the `sendEvent` method is implemented, which formats the `HTTP POST` request and utilizes the `got` library to send it. The `sendEvent` method is called when the first `phaseStarted` event occurs to send the event for the test's start. Additionally, it is also utilized within the existing `cleanup` method to send the event marking the test's end.
The `startedEventSent` property acts as a toggle, storing the state of the test. It is checked before sending the event to ensure that the start event is only sent upon the first occurrence of the `phaseStarted` event. …

feat: enable sending events to new relic

---

examples/browser-load-testing-playwright/advanced-custom-metric-for-subflow.yml
examples/browser-load-testing-playwright/browser-load-test.yml
examples/browser-load-testing-playwright/browser-smoke-test.yml
examples/browser-load-testing-playwright/flows.js
examples/browser-load-testing-playwright/pages.csv

These examples weren't displaying web vital metrics by default. 
The reason was the Artillery Playwright engine looks for `window.location.href` as the url, and tries to match that with the `target` to decide on whether to show them or not. Since navigating to the website directs to `www`, that check was failing, and so no extended metrics were showing.
_Note:_ I also fixed the `cloudWaitlistSignupFlow` which wasn't working properly. I used playwright's codegen as the previous one for an updated exmaple.

fix(examples): use correct url so that all web vital metrics display

---

packages/artillery-plugin-publish-metrics/lib/mixpanel.js

Related to #1888 
Mixpanel reporter update. Old reporter wasn't working anymore due to changes in Artillery's `stats` event configuration. I've adjusted it so it breaks down the v2 report format into properties and sends them to Mixpanel.
I've tested manually with different scripts and combinations to make sure everything is formatted properly and that the events arrive as they should to Mixpanel and in those tests I did not notice any issues.
I do have to note that I am not a Mixpanel user and therefore do not have further insight into what exact information and in which format would be most beneficial to send. For instance if maybe sending information per scenario and not per reporting period would be better.
The previous version just sent the intermediate reports at every reporting …

fix: use artillery v2 report format

---

packages/core/package.json

Update our fork of Datadog's sketches-js to latest version.
https://github.com/artilleryio/sketches-js

dep(artillery): upgrade @artilleryio/sketches-js to 2.1.0

---

packages/artillery-plugin-expect/test/run.sh

These tests are sometimes failing in CI despite no issue.
Additionally, in local execution, any two consecutive runs of this test suite will cause issues.
- **Adds a timeout to Ava. Ava defaults to 10s - Increasing to 30s**: The reason for this is I noticed in some of the CI failures there were timeouts, so this might be the reason for the random failures. I ran the tests locally many times and could not reproduce issues, whilst before I added the timeout, I was randomly getting failures.
- **Removes container after stopping it:** Two consecutive local runs were failing because a container with the name `mockingjay` already existed. This removes the container after execution.
Ran many times locally without issues. Hopefully the CI runs below will be green :).

test(expect): add timeout to test and remove container in cleanup

---

packages/artillery-plugin-ensure/index.js

Ensure plugin was not running checks at the end if config is passed like this:
```
plugins:
ensure:
thresholds:
- http.response_time.p99: 100
- http.response_time.p95: 75
```
This happened since the `beforeExit` ext was not looking for the second input option.
Tested with:
```yaml
config:
target: http://asciiart.artillery.io:8080
phases:
- duration: 10
arrivalRate: 1
plugins:
ensure:
thresholds:
- http.response_time.p99: 100
- http.response_time.p95: 75
scenarios:
- flow:
- get:
url: "/dino"
```
Also tried other variations (ensure outside of `plugins`), and no checks. All worked appropriately.

fix(ensure): check in beforeExit for both ensure plugin interfaces

---

.github/workflows/run-tests.yml
package-lock.json
packages/artillery-plugin-expect/package.json
packages/artillery-plugin-expect/test/index.js
packages/artillery-plugin-expect/test/lib/formatters.js
packages/artillery-plugin-expect/test/run.sh

- Ava had unexpected behaviour with timeouts in the tests. While this may be desirable if used correctly, it is different than how other tests behave in the repo
- To be consistent and use a single framework across the repo
- Use the opportunity to use a newer version of tap to see if its debuggability has improved
Note: This PR also adds `FORCE_COLOR: 1` to tests in CI and `--color` to these particular tests. This ensures that `tap` uses the base reporter rather than the ugly raw output which is very hard to debug. This makes the experience in CI equivalent to the local experience shown in screenshots below. It's much better because:
- Shows test failure at the end;
- Doesn't show all the output from successful tests, polluting the screen;
- Shows colours, which allow you to easily spot …

test(expect): move from ava to tap

---

packages/commons/engine_util.js

This [logic](https://github.com/artilleryio/artillery/pull/1922) was breaking when a `regex` without groups was done. Tests were not catching it due to the issue in local/ci setup of not using `*`, which is why it started being caught here https://github.com/artilleryio/artillery/pull/2005
Given that this branch doesn't contain the changes in https://github.com/artilleryio/artillery/pull/2005 yet, the automated tests in CI won't run against the right version, so it will be a false positive. However, I ran the same change against the branch in that PR, and all tests are passing. 👍

fix(commons): only check for match group if there are groups

---

packages/artillery-plugin-publish-metrics/README.md
packages/artillery-plugin-publish-metrics/index.js
packages/artillery-plugin-publish-metrics/lib/dynatrace/index.js
packages/artillery-plugin-publish-metrics/test/config-dynatrace.yaml

Dynatrace target for `publish-metrics` plugin. Supports sending metrics to Dynatrace's Metric API v2.
`DynatraceReporter` is initialised within the `publish-metrics` `Plugin` class.
It subscribes to `stats` event to access the metrics for each reporting period, and then it formats those metrics into the payload to be sent with `HTTP POST` request to Dynatrace's Metric API endpoint. It uses `got` library to send the request.
**Configuration:**
- To send metrics to Dynatrace, set `type` to `dynatrace`.
- `apiToken` -- required. The Access Token with `metrics.ingest` value
- `envUrl` -- required. The Dynatrace environment URL.
- `prefix` -- prefix for metric names created by Artillery; defaults to artillery.
- `dimensions` -- a list of `name:value` strings to use as dimensions for all …

feat: dynatrace reporter

---

.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-skytrace.yml

Skytrace publish has been failing for a while on `build` step, since it requires a `devDependency` that isn't available unless install is run.

ci(skytrace): install before build/publish so deps are available

---

.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-artillery-engine-playwright.yml
.github/workflows/npm-publish-artillery-engine-posthog.yml
.github/workflows/npm-publish-artillery-plugin-apdex.yml
.github/workflows/npm-publish-artillery-plugin-ensure.yml
.github/workflows/npm-publish-artillery-plugin-expect.yml
.github/workflows/npm-publish-artillery-plugin-metrics-by-endpoint.yml
.github/workflows/npm-publish-artillery-plugin-publish-metrics.yml
.github/workflows/npm-publish-artillery.yml
.github/workflows/npm-publish-int-commons.yml
.github/workflows/npm-publish-int-core.yml
.github/workflows/npm-publish-skytrace.yml

We now use Node 18.x+ everywhere else, including platform-fargate.
This was causing an `npm install` in the publish scripts for Skytrace to fail. Took the opportunity to update it everywhere else in the publish scripts.

ci(publish): use node version 18.x

---

packages/artillery/lib/util.js
packages/artillery/test/cli/command-run.test.js
packages/artillery/test/scripts/scenario-cli-variables/processor.js
packages/artillery/test/scripts/scenario-cli-variables/scenario-with-other-nested-config.yml
packages/artillery/test/scripts/scenario-cli-variables/scenario-with-variables.yml
packages/artillery/test/scripts/scenario-with-cli-variables.yml

Solves https://github.com/artilleryio/artillery/issues/1560 by templating all config parameters taking into account `flags.variables` too.

fix(artillery): template config vars after flag vars have been added

---

.github/workflows/npm-publish-artillery-types.yml
packages/types/package.json

- The `types` package needs to have its dependencies installed in order to be released. 
- Adds a `prepublishOnly` script to the `types` package so its built and tested before publishing.

chore: add install step to types release

---

.github/workflows/npm-publish-all-packages-canary.yml

CI was still failing: https://github.com/artilleryio/artillery/actions/runs/5795602657/job/15707505909
The reason is the git hooks which require an `npm install` on the root of the repo. As these hooks are unneeded before publish, adding `--ignore-scripts` here.

ci(publish): add --ignore-scripts to skytrace install on canary

---

packages/artillery-plugin-publish-metrics/lib/newrelic/index.js

`accountId` needs to be set only when user wants to send events to New Relic, it is not required for sending metrics.
`eventsAPIEndpoint` configuration that uses `accountId` was not scoped properly to events, causing reporter to error even when `event` feature was not used, preventing sending the metrics to New Relic.
Scoping configuration of `eventsAPIEndpoint` to only run when `event` has been set in the reporters config and `accountId` has been provided.

fix(publish-metrics): new relic accountid configuration

---

.github/workflows/npm-publish-artillery-types.yml
packages/types/definitions.ts
packages/types/package.json
packages/types/test/simple.test.ts

- Sets the `--access public` flag on the `npm publish` command for the `@artilleryio/types` package (fixing https://github.com/artilleryio/artillery/actions/runs/5799049948/job/15718160240) 
- Removes the HTTP flow compliance from the `websocket` engine and adds it to the `socketio` engine.

ci: release v0.1.2 @artilleryio/types

---

packages/skytrace/package.json

This is currently failing CI with:
```
TypeError: command.args.filter is not a function
``` 
As this Oclif feature is not currently being used for anything (we aren't auto-generating the docs anyway), I'm removing it for now, and we can fix this later (together with overall updating of oclif packages in Skytrace) when we want to actually auto-generate the docs.

chore(skytrace): remove readme from prepack script

---

packages/types/LICENSE
packages/types/package.json

Adds a `LICENSE` file as well as the `"license"` field in `package.json` for the `@artilleryio/types` package.

fix(types): add license

---

packages/artillery-plugin-publish-metrics/lib/dynatrace/index.js
packages/artillery-plugin-publish-metrics/test/config-dynatrace.yaml

Events feature for the Dynatrace reporter of the `publish-metrics` plugin. Supports sending events marking the start and the end of a test to Dynatrace through Event API.
**Configuration for users:**
Set `event` under Dynatrace configuration to send events.
- `eventType` -- the type of the event. It can be one of the values listed [here](https://www.dynatrace.com/support/help/dynatrace-api/environment-api/events-v2/post-event#request-body-objects). Defaults to `CUSTOM_INFO`
- `title` -- the title of the event. Defaults to `Artillery_io_Test`.
- `send` -- set to `false` to turn off the event. By default, if an event is configured, it will be sent.
- `entitySelector` -- string. The [entity selector](https://www.dynatrace.com/support/help/dynatrace-api/environment-api/entity-v2/entity-selecto …

feat: send events to dynatrace

---

packages/types/package.json

- Addresses a slow CI job at https://github.com/artilleryio/artillery/actions/runs/5819306125/job/15777434812
There's really nothing to take close to 30 seconds in these tests, even taking CI environment into consideration. We should look at migrating to a modern test runner like Vitest that's both fast and encourages better testing practices than `tap`.

chore(types): increase tap test timeout

---

packages/artillery-plugin-apdex/LICENSE
packages/artillery-plugin-memory-inspector/LICENSE

Licenses had been correctly set in the `package.json`, but best to add it to the package too, to be consistent with other ones too.

chore(plugins): add missing licenses

---

.github/workflows/run-tests.yml

Sets up the automation to post a Slack message upon failed GitHub workflows.

chore: post slack message on failed ci

---

packages/artillery/lib/platform/cloud/cloud.js

Sending exit code to cloud so the dashboard has information about the CLI exit code to display in the future.
Tested with Fargate, Lambda and Local with successful exit code and failure (using ensure plugin).

feat: send exit code to artillery cloud

---

packages/core/lib/engine_http.js
packages/core/test/core/unit/engine_http.test.js

Fix for #2034  
Http engine would not encode the query string properly if one of the `qs` properties set in the script is as an array.
I used the `URLSearchParams` instance, and passed the query object directly into it as it formats the objects containing arrays properly.

fix(http): add support for array values of qs parameters

---

packages/artillery-plugin-publish-metrics/index.js

In doing a performance analysis of Artillery, I noticed that reporters that weren't chosen to be in use could still have a somewhat heavy memory footprint. Some of the reporters (like Lightstep) actually appended things to the global object.
Making this change should reduce the initial memory of Artillery when using this plugin by about 10-15% (depending on the reporter used).
Tested with the Datadog reporter extensively.

fix(publish-metrics): conditionally require reporters to improve memory

---

packages/artillery-plugin-publish-metrics/lib/dynatrace/index.js
packages/artillery-plugin-publish-metrics/lib/honeycomb.js
packages/artillery-plugin-publish-metrics/lib/lightstep.js
packages/artillery-plugin-publish-metrics/lib/mixpanel.js
packages/artillery-plugin-publish-metrics/lib/newrelic/index.js
packages/artillery-plugin-publish-metrics/lib/prometheus.js
packages/artillery-plugin-publish-metrics/lib/splunk/index.js

Making the `publish-metrics` reporters' behaviour consistent - all reporters will fail the test early if required config setting is not provided by user (e.g. API key). 
The exceptions for this are `Datadog` and `Cloudwatch` reporters as Datadog defaults to default settings and Cloudwatch pulls from the users environment, not the script. 
Currently, if a user doesn't set a required config key (e.g. an API token), reporters behave in various ways.
Some don't let the user know at all and let the test continue, others just log a message that can easily be missed while test is running, and then some let the test fail with error when attempting to send the data.
If a user sets the `publish-metrics` plugin with its `type` in a script I believe that that shows clear intent to send the test data …

feat(publish-metrics): fail early if required config missing

---

packages/core/lib/engine_http.js
packages/core/test/core/index.js
packages/core/test/core/test_cookies.js
packages/core/test/core/test_headers.js
packages/core/test/core/test_think.js

Addresses https://github.com/artilleryio/artillery/issues/2036. The intention was always to have `config.http.defaults`.
_Note: I gave priority to `config.http.defaults` over `config.defaults` in the code since that is the preferred option._
Automated tests were added for all the options except `capture`. I am having some issues with the existing capture tests (I'm not sure they're failing when they're supposed to), so I may address this specific test separately. This change should be pretty transparent though, as the actual options remain the same as before, and I'm merely adding a new way to set them.

feat: add config.http.defaults to cli

---

packages/types/definitions.ts
packages/types/test/simple.test.ts

Fixes some of the discovered issues with `@artilleryio/types` definitions. See the commits for detailed log of changes.

fix(types): improve conformance to the specification

---

package-lock.json
packages/artillery-plugin-ensure/package.json
packages/artillery-plugin-ensure/test/fixtures/scenario.yml
packages/artillery-plugin-ensure/test/index.spec.js
packages/artillery-plugin-ensure/test/index.spec.mjs

As far as I could tell, there was a single ensure test in the repo, as part of an expect test. As this is an important part of the CLI (including Cloud), I'm adding tests there. 
Pulled this up in priority, as I'm working on related ensure work and may need to make a change in this part of the code, but I didn't want to do it without any tests.
_Note: I disabled coverage because we don't have it anywhere else in the repo, but actually these tests (accidentally) gave it about 90% coverage. It's only not 100% because of debug logs and error cases that would be best suited to unit tests._

test(ensure): add tests for ensure plugin integration with artillery run

---

package.json

The Prettier config we have produces the wrong YAML formatting. This fixes it.

chore: force double-quotes in yaml

---

packages/artillery-plugin-ensure/package.json

A version with fix https://github.com/artilleryio/artillery/commit/d1136f37d492d61e91a41334549a08196980b26c was never released, and fargate uses this package, which is why it wasn't picking up the change.

ci: release v1.1.5 of artillery-plugin-ensure

---

.github/workflows/run-tests.yml

Since our `run-tests` workflow also triggers on pull requests to `main`, we get notifications for test failures for changes that may still be in progress. 
- Set an explicit `github.ref == 'refs/heads/main'` condition to the notification job so it only notifies about failures in `main`.

chore: post slack notifications only on failures in main

---

packages/artillery-plugin-expect/test/pets-fail-test.yaml
packages/artillery-plugin-expect/test/pets-test.yaml
packages/artillery-plugin-expect/test/run.sh

- Discovered in https://github.com/artilleryio/artillery/actions/runs/5925989155/job/16066519224
- Sets `9099` as the new port for Mockingjay in tests.
We seem to encounter a flaky test behavior due to multiple tests attempting to establish a connection to the same port. When that happens, the test fails since the port is already in use.

chore: change mockingjay port to 9099

---

packages/types/definitions.ts
packages/types/package.json
packages/types/plugins/expect.ts
packages/types/test/engine.http.test.ts
packages/types/test/engine.socketio.test.ts
packages/types/test/engine.websocket.test.ts
packages/types/test/examples.test.ts
packages/types/test/helpers.ts
packages/types/test/plugin.expect.test.ts
packages/types/test/simple.test.ts

fix(types): implies default "http" engine, fixes request "cookies" and "match"

---

packages/artillery-plugin-publish-metrics/lib/honeycomb.js

Fixing a wrong operator in Honeycomb reporter's check for required settings.
Either `apiKey` or `writeKey` are required, not both.

fix(publish-metrics): change operator in honeycomb reporter

---

package-lock.json
packages/artillery-plugin-ensure/index.js
packages/artillery-plugin-ensure/package.json
packages/artillery-plugin-ensure/test/index.spec.js

- Sets coloured output on `fail`/`ok` messages in checks
- Fixes ordering of checks so that they are grouped: passing checks are displayed first, and failing checks after (before they could alternate, depending on the type of check, for example)
Example:

feat(ensure): add colored output to checks

---

package-lock.json
packages/artillery-plugin-publish-metrics/lib/datadog.js
packages/artillery-plugin-publish-metrics/test/config-api.yaml
packages/artillery-plugin-publish-metrics/test/index.js

This new feature is related to this opened issue: https://github.com/artilleryio/artillery/issues/2066. Thx ;)

Add application key property to artillery publish-metrics type datadog

---

packages/artillery/test/cli/command-run.test.js

There's a flaky test in CI that fails occasionally. I believe this will be hard enough to debug, but what doesn't help is that it shares its name with another test, making it impossible to pinpoint the culprit, since the TAP stack trace is not pointing to the exact file when there's a timeout.
Changing this first so we can have a better chance to isolate the problem and fix it.

chore(artillery): change repeated test names

---

packages/types/definitions.ts
packages/types/test/plugin.expect.test.ts

- Fixes an issue that errored when an array of expectation metrics is provided to the `expect` property on individual requests.

fix(types): support array of expectation metrics

---

package-lock.json
packages/core/lib/phases.js
packages/core/package.json
packages/core/test/core/scripts/arrival_phases_time_format.json
packages/core/test/core/test_arrivals.js
packages/core/test/core/unit/phases.test.js
packages/types/definitions.ts

This will allow users to specify all time formats supported by https://www.npmjs.com/package/ms, bringing us more in line with other Load test frameworks. This is quite useful especially in load test scripts that have long durations
e.g. instead of:
```yaml
phases:
- duration: 1800
arrivalRate: 1
rampTo: 50
name: "Phase 1"
- duration: 10800
arrivalRate: 50
```
users can now specify:
```yaml
phases:
- duration: 30m
arrivalRate: 1
rampTo: 50
name: "Phase 1"
- duration: 3h
arrivalRate: 50
```
which is much more readable.
Note: this also addresses https://github.com/artilleryio/artillery/issues/2065.
Previously, when a test was started with an invalid duration, it would run endlessly. That is now caught as well, and errors:
(there's a stack trace below it too)
I didn't spend too much time on …

feat(core): support multiple time formats in artillery cli

---

package-lock.json
packages/artillery-plugin-publish-metrics/package.json

`libhoney` was using a dependency that included a security vulnerability, which was causing `npm audit` to report several Critical vulnerabilities in our repo. They've now removed that dependency and released a version with the fix, so we can upgrade ourselves, so we don't have any critical vulnerabilities in the repo.

dep(publish-metrics): update Honeycomb client

---

packages/artillery/lib/platform/cloud/cloud.js

Displays more meaningful error when user sends an invalid `--key` and receives a 401 from the Cloud API.

fix(cloud): display api key error when invalid key is set

---

packages/artillery/package.json

There's a particular test in the suite that keeps failing due to a timeout. Now that I've changed its title to distinguish which one, I can see it's the last test in the suite to run. My theory is that maybe the problem is not the test at all, but sometimes the runtime of the suite is being pushed beyond 5 minutes in CI (and happens to always fall on that test because it's the last one to run).

test(artillery): increase timeout of suite

---

packages/types/definitions.ts

During testing I've discovered a typo in one of the request properties: `followRedirects` doesn't exist, the property must be `followRedirect`. This fixes the issue.

fix(types): rename "followRedirects" to "followRedirect"

---

packages/types/definitions.ts

Adds missing type definitions for `config.http.defaults`.

fix(types): annotate "config.http.defaults"

---

examples/browser-load-testing-playwright/browser-smoke-test.yml
examples/browser-load-testing-playwright/flows.js
examples/browser-load-testing-playwright/pages.csv

As per https://github.com/GoogleChrome/web-vitals/issues/180, very simple scenarios can sometimes be too fast for certain metrics like `LCP` and `CLS` to be able to be caught in time. For this reason, I've added the `page.reload()` function (instead of adding additional things like clicks that go to other pages).
In our case, even `TTFB` and `FCP` weren't consistently showing, which is why I also added waiting for an element beforehand.

refactor(examples): make playwright smoke example have more interaction

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json

Updating Playwright version. This will release a canary which can then be used to test and release Fargate.
Release details: https://playwright.dev/docs/release-notes#version-137
Since our previous version (1.34.3), only the following breaking change was released:
- [Playwright Core name change](https://github.com/microsoft/playwright/releases/tag/v1.35.0) - **shouldn't affect us as we don't use this directly**
- Tested against all Playwright examples
- Tested against a small script ran against Artillery Cloud

dep(playwright): update playwright version to 1.37.1

---

.github/workflows/run-tests.yml

This Github Action gives out a lot more information for free, so we don't have to format it all ourselves.
Pinned to a specific version so we can control version increases better, for security, since it's a third party action.

ci(test): change to better formatted slack notification github action

---

examples/using-data-from-csv/csv/urls.csv
examples/using-data-from-csv/website-test.yml

This example was broken due to redirects from the `https://artillery.io` website:
```
--------------------------------
Summary report @ 14:15:27(+0000)
--------------------------------
errors.ERR_TOO_MANY_REDIRECTS: ................................................. 300
(...)
vusers.created: ................................................................ 300
vusers.failed: ................................................................. 300
```
- Moved it to the asciiart website to keep it more inline with other examples, as it also has 3 paths we can demonstrate the same thing with. 
- Added ensure and expect checks so that this will fail CI if something is wrong, as the example was currently being used in CI, but failing without warning.

fix(examples): artillery cli using data from csv example

---

.github/workflows/examples.yml

This will serve as a small acceptance test for our Artillery Cloud integration, while also giving us more tests to test against the Dashboard. Win-win.
I added tags and notes so we get a couple of features of the dashboard used in there too.
_Note: the note has markdown space escape character to prevent it from into an issue when sending an initial note with the GH action + workflow combo. We can investigate later if there's something we need to do differently in the GH action to account for this, as it's not the best experience when sending this sort of user input that contains spaces from the Action._

ci(examples): make gh action examples report to artillery cloud

---

package-lock.json
packages/artillery-plugin-publish-metrics/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js
packages/artillery-plugin-publish-metrics/package.json

Open Telemetry reporter that supports sending traces from Artillery to external monitoring and observability systems using Open Telemetry Protocol (OTLP) implemented over HTTP transport system. It uses the following Open Telemetry JS exporters [http/json](https://www.npmjs.com/package/@opentelemetry/exporter-trace-otlp-http) and [http/protobuf](https://www.npmjs.com/package/@opentelemetry/exporter-trace-otlp-proto)
**Configuration:**
- In `publish-metrics` config set `type` to `open-telemetry`.
- `serviceName` -- **required** the name of service that data belongs to, defaults to `Artillery-test`
- `tracing` -- set to configure and send traces
- `endpoint` -- OTLP ingest endpoint (exporters  default to `http://localhost:4318/v1/traces`)
- `headers` -- headers in `key: value` pairs that are …

feat(publish-metrics): implement otel reporter with tracing support

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js

When removing the `prefix` option for metric names, the prefix in rate names was overlooked.

fix(publish-metrics): remove undefined prefix from rate names

---

packages/artillery-plugin-publish-metrics/lib/dynatrace/index.js

Related to this [discussion](https://github.com/artilleryio/artillery/discussions/2064#discussioncomment-6968472)
In Dynatrace reporter, `endpoint` that had an existing path (e.g. in managed instances) wasn't being joined correctly. 
Changed to using `path.join()` within creating the URL's to resolve this

fix(publish-metrics): use path.join to append path to endpoints

---

packages/types/schema/config.js
packages/types/schema/plugins/apdex.js
packages/types/schema/plugins/ensure.js
packages/types/schema/plugins/expect.js
packages/types/schema/plugins/metrics-by-endpoint.js
packages/types/schema/plugins/publish-metrics.js

Not all built-in plugins allow you to use `config.<plugin-name>` to set config options. As far as I know, only `ensure` and `apdex` do. The schema assumed that all of them did.

fix(schema): correct the plugins allowed in root config

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js

Currently the OTel reporter does not print out errors if any occur due to OpenTelemetry catching them internally with their `DiagAPI`.
This PR implements the `DiagConsoleLogger` which gets activated and set on `debug` log level when `DEBUG` is used for OTel reporter.
Related to #2128 discussion

fix(publish-metrics): enable diag logger for debug

---

packages/commons/engine_util.js

Fix for #2125 
The `extractRegExp` function was not considering the integer index of the group in the regular expression as a group identifier, only [named groups](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Named_capturing_group) were considered.
Implemented the integer index consideration.
Tested manually. As no tests exists for `engine_util` yet, the tests implementation will be added in a separate PR when created.

fix(commons): match regex groups by integer index

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js

`otlp-grpc` exporter does not support `headers` as its config option. So currently when `headers` are set in combination with `otlp-grpc` exporter for `metrics` it will throw an error, and headers can be set only through environment variables. 
When `headers` are set in test script along with `otlp-grpc` exporter for `metrics`, they will be passed to the exporter as `metadata` rather than `headers` as `otlp-grpc` exporter supports `metadata`  which can basically serve the same purpose as headers - API keys and such can be set with it.

fix(publish-metrics): set headers as metadata for otel-grpc

---

examples/http-socketio-server/http-socket.yml
examples/http-socketio-server/package-lock.json
examples/http-socketio-server/package.json
examples/socket-io/README.md
examples/socket-io/package-lock.json
examples/socket-io/package.json
examples/socket-io/socket-io.yml
packages/artillery/lib/util/validate-script.js

Addresses 3 things:
- Fixes `examples/socket-io` example to use socketio v3 as well as the correct Artillery interface for `acknowledge` and `response` (as per change in: https://github.com/artilleryio/artillery/pull/1112)
- Changes `examples/http-socketio-server` example to use socketio v3 server, and creates a scenario for it with proper Artillery interface (to keep it in-line with other examples that include their own scenario)
- Fixes critical path (currently broken!) runtime schema validation which currently results in the error `Scenario validation error: "scenarios[0].flow[2]" must have 1 key` when running with the correct Artillery interface.
I used the new examples to test this, as well as an HTTP example and the automated tests to verify that it didn't break existing …

fix: socketio validation schema and examples

---

examples/socket-io/app.js
examples/socket-io/socket-io.yml
packages/artillery/lib/util/validate-script.js

With `namespace` being a valid option too, there are a max of 3 keys in this object, not 2.
I also updated the example to include this, which also helps users understand how to use `namespace`.

fix(validate-script): socketio runtime schema max value

---

packages/artillery-plugin-publish-metrics/lib/dynatrace/index.js

In Dynatrace reporter,  gracefully handle cases in which the metric name does not meet the Dynatrace Ingest API's  [requirements for metric key](https://www.dynatrace.com/support/help/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key).
One case in which this could be needed is when `metrics-by-endpoint` plugin is used alongside this reporter. `metrics-by-endpoint` plugin by default creates metric names that contain URL strings, and therefore characters that are unsupported by Dynatrace Ingest API. This can be avoided by using `useOnlyRequestNames` setting provided by `metrics-by-endpoint` and setting the `name` value for all requests to a string that meets the Ingest API's requirements.
Another case is user setting custom metrics that do not meet said …

fix(publish-metrics): warn user when metric name invalid

---

packages/types/schema/engines/common.js
packages/types/schema/engines/http.js
packages/types/schema/engines/socketio.js
packages/types/test/engine.socketio.test.ts

Follow up of https://github.com/artilleryio/artillery/pull/2149.
Implements the right schema in our JSON schema to be used by the VS Code extension.

fix(schema): implement correct socketio ack and response in json schema

---

packages/artillery-plugin-memory-inspector/README.md
packages/artillery-plugin-memory-inspector/index.js
packages/artillery-plugin-memory-inspector/package.json
packages/artillery-plugin-memory-inspector/test/index.spec.mjs
packages/artillery/lib/cmds/run.js

Currently, this defaults to bytes, which makes it very hard to read the data. This gives more control over it.
Also sends telemetry data for the plugin, so we can see if there's interest in it.

feat(memory-inspector): allow memory units to be specified

---

packages/artillery/lib/util/validate-script.js

When running this valid `Socketio` interface (since this PR: https://github.com/artilleryio/artillery/pull/1112):
```yaml
flow:
- emit:
- "join"
- "lobby"
```
You would get this error `Scenario validation error: "scenarios[0].flow[0].emit" must be of type object`.
Tested with a scenario locally. Automated tests for this will be added as part of another PR, as I'm adding tests for socketio in `artillery` package soon (only exist in `core`, which makes things like this fall through the cracks).

fix(socketio): allow emit to be array of strings in validate-script

---

packages/types/schema/engines/common.js

Small fix as you can do:
```yaml
match:
- json: "$.0"
value: "something"
- json: "$.1"
value: "Hello!"
```
And this was being detected as invalid by the VS Code extension.

fix(schema): allow match joi schema to be an array too

---

packages/types/schema/engines/playwright.js

Quick fix, as I forgot to add this before. Noticed it when using the extension.

fix(schema): add extendedMetrics to playwright engine schema

---

packages/artillery-engine-playwright/index.js

Gives users an abstraction to facilitate breaking their Playwright scenario into a series of steps and capture transaction timers for each of them, with an API that should be familiar to Playwright users.
```js
async function loginSearchAndLogout(page, userContext, events, test) {
//1. simply add this line to your scenario function, or use test.step below instead
const { step } = test;
const userid = userContext.vars.userid;
const recordid = userContext.vars.recordid;
//2. wrap any logic you have in steps 
//(sometimes you might already have something like this done from existing playwright tests)
await step("landing_page", async () => {
await page.goto('https://internaltesturl.com/landing');
await page.getByLabel('id-label').fill( `${userid}` );
await …
```

feat(playwright): add step transaction function to user context for custom metrics

---

packages/artillery-plugin-apdex/index.js
packages/artillery-plugin-apdex/package.json
packages/artillery-plugin-apdex/test/fixtures/processor.js
packages/artillery-plugin-apdex/test/fixtures/scenario.yml
packages/artillery-plugin-apdex/test/index.spec.js

Solves https://github.com/artilleryio/artillery/issues/2193. Apdex has actually had this issue all along when using a processor. 
It happens because in the parent thread, the processors are not available as an array, that's an implementation detail of workers only.
In the case of this specific plugin, part of the logic has to run only on the parent thread, and the rest of the logic has to run in workers.
Automated testing was implemented.
The implemented test replicates the issue:
https://github.com/artilleryio/artillery/actions/runs/6455923510/job/17524361652?pr=2195
https://github.com/artilleryio/artillery/actions/runs/6456170500/job/17525111146?pr=2195

fix(apdex): run apdex logic correctly in workers

---

packages/artillery/lib/launch-platform.js

This fixes the issue with `phaseStarted`/`phaseCompleted` events receiving an incorrect phase spec.
This is happening because we "split" the original phase definition to give each worker thread a subset of the total workload, e.g. a phase definition with `arrivalCount` of 20, becomes 4 phases with `arrivalCount` of 5 each when running on a system with 4 CPUs. We currently emit one of those split phase definitions with global `phaseStarted` &  `phaseCompleted` events.

fix: include original phase definition in phaseStarted/phaseCompleted events

---

packages/artillery/lib/launch-platform.js

After this PR (https://github.com/artilleryio/artillery/pull/2203), emitted phase events are now pulled from the original script, but this only includes phase names, not indexes. Sometimes phases don't have names, and the index is an alternative way to identify which phase we are on. 
_Note: This will also be relevant to a fix needed for Fargate, where this index is needed for deduplication of messages._

fix(artillery): include index in phases emitted

---

package-lock.json
packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js
packages/artillery-plugin-publish-metrics/package.json

Multiple improvements to OTel reporter tracing feature for the HTTP engine:
- Each request is its own root span and a separate trace with no information on which scenario it belongs to
- No insight on individual request phases except for `responseTimeMs` attribute
- Request spans have `http_request_started` and `http_request_ended` events
- Errors are set as a `status` on spans
Individual trace:
- Scenarios are the root spans with all requests that are executed as a part of each scenario nested inside them as their child spans
- Each request is broken down further into the following child spans (they represent the request phases respectively as they are recorded in the `got`  [`response.timings.phases`](https://github.com/sindresorhus/got/blob/main/source/core/response.ts) object): 
- …

feat(publish-metrics): increase trace visibility for OTel reporter

---

packages/artillery-plugin-apdex/index.js
packages/artillery-plugin-apdex/test/index.spec.js

Related to #2209
Making `apdex` plugin show all 3 metrics in the report even if their count is 0 (even if no metrics were frustrated/satisfied/tolerated) just like we do for `vusers.failed`. This is needed so that when the `threshold` for the given `apdex` metric is set in the `ensure` plugin, the `ensure` does not fail the check for metrics whose count is 0.

fix(apdex): show all metrics in report

---

packages/artillery-plugin-apdex/index.js

Emitting metrics with 0 explicitly before the check. 
Reverting mistake from last PR.

fix(apdex): emit metrics with zero explicitly

---

packages/artillery/lib/console-reporter.js
packages/core/lib/ssms.js

Some users may be interested in observing the difference between `mean` and other statistics, as we've received as feedback. As we expose a lot of other statistics, we can easily expose this one too.
---
_Open question: should we change `ensure` to include this in the legacy conditions?_

feat(core): add mean to calculated histogram metrics

---

packages/artillery/lib/cmds/run-lambda.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/test/cli/command-run.test.js
packages/artillery/test/scripts/scenario-named/scenario.yml
packages/core/lib/runner.js

Originally requested here https://github.com/artilleryio/artillery/discussions/1929, this is a useful feature for people who are saving multiple scenarios in the same file. Especially useful once you start having complex scenarios with weights, but still want the ability to run them individually on demand, a requirement I've had myself in the past.
~Note: CLI flag name (`--name`) could be changed to something else, like `--byName`. Please suggest something else if you think it makes more sense.~
_Note: Flag name is now --scenario-name after some internal discussions. Please make other suggestions if other ideas pop up._

feat(artillery): add ability to specify scenario to run by name

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json

Updating Playwright version. This will release a canary which can then be used to test and release Fargate.
Release details:
- https://github.com/microsoft/playwright/releases/tag/v1.39.0
- https://github.com/microsoft/playwright/releases/tag/v1.38.1
- https://github.com/microsoft/playwright/releases/tag/v1.38.0
Since our previous version (1.37.1), the following breaking changes were released:
- **Playwright no longer downloads browsers automatically:** this affects Artillery's engine. However, we can now use the [workaround described here](https://github.com/microsoft/playwright/releases/tag/v1.38.0) of installing the browser directly in the dependency via `@playwright/browser-chromium`. Despite this being listed as the `not recommended` option, I believe this is the most sensible option …

dep(playwright): update playwright version to 1.39.0

---

packages/artillery-engine-playwright/Dockerfile

Related to https://github.com/artilleryio/artillery/pull/2230, where this was removed. The playwright image (`mcr.microsoft.com/playwright:v1.39.0`) actually still contains all the browsers, regardless of what we install in the package, so we still need to manually remove them.

fix(docker): remove playwright browsers from image

---

packages/core/lib/engine_http.js

Currently we are swallowing those errors, because we only show err.code, and don't log with debug anything else: `ee.emit('error', taskErr.code || taskErr.message);`
So the user only gets `ERR_GOT_REQUEST_ERROR` in the report, with no other clues. We have a user experiencing that here: https://github.com/artilleryio/artillery/discussions/958#discussioncomment-7339572

fix(http): add debug log when got errors

---

packages/artillery/lib/util.js
packages/artillery/test/cli/command-run.test.js
packages/artillery/test/scripts/with-process-env/processor.js
packages/artillery/test/scripts/with-process-env/with-env.yml
packages/artillery/test/scripts/with-process-env/with-processEnvironment.yml

Solves https://github.com/artilleryio/artillery/issues/2258
Automated tests were added before introducing the change.

fix(artillery): template variables coming from env var correctly

---

packages/core/test/core/unit/templates.test.js

This test occasionally fails, but presumably only in CI. This could be due to the machine being attributed in CI occasionally not being powerful enough. 
- This PR makes the CI templated max time be 50% longer (let me know if you think this should be another value).
- We also add the time taken to the error log, so we can actually see how much it is taking in case it keeps failing. This will let us adjust the values better.

test(core): make templates test have longer max time in ci

---

packages/core/lib/engine_socketio.js
packages/core/test/core/run.sh
packages/core/test/core/scripts/hello_socketio_with_args.json
packages/core/test/core/targets/socketio_args.js
packages/core/test/core/test_misc.js
packages/types/schema/engines/socketio.js

A porting of the popular (and really good) third-party engine (https://github.com/ptejada/artillery-engine-socketio-v3) to Artillery Core was done back in July 2021 in https://github.com/artilleryio/artillery/pull/1112.
However, shortly after that, updates were done to the engine that were never ported over to Artillery, which left the job incomplete. This update in particular makes a lot of sense, because it gives support for multiple arguments to be easily asserted on, which is something that can be done when emitting SocketIO events.
Essentially, it gives the ability to do things like:
```yaml
- emit: ["message", "chat_room_1", "Hey there!"]
response:
on: message
args:
- chat_room_1
- Hey there!
```
**This is for use by the Artillery team. Please leave this in if you're contributing to …

feat(socketio): add args+on for event validation of any amount of args

---

packages/artillery-engine-playwright/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js

Tracing support for the Playwright Engine through OpenTelemetry reporter (publish-metrics plugin).
Tracing is implemented in 2 ways:
- Span is created for each `step` function call. (The `step` function is provided inside the `test` object argument of the processor `flow` function)
- Span is created for each `framenavigated` event where the main frame's `page.url()` changes, and is active until the next main frame change, portraying the time spent on each page. 
Each of these spans is nested within the root scenario span, creating an individual trace per scenario/VU run.
- Web vitals are added as attributes and events on corresponding `pageSpan`  as they happen, 
-  When `extendedMetrics` setting is set to `true`, other metrics emitted by the engine (`dominteractive`, …

feat(playwright): add trace support for playwright with otel reporter

---

packages/artillery-plugin-ensure/index.js
packages/artillery-plugin-ensure/package.json
packages/artillery-plugin-ensure/test/fixtures/processor.js
packages/artillery-plugin-ensure/test/fixtures/scenario-custom-metrics.yml
packages/artillery-plugin-ensure/test/index.spec.js
packages/artillery-plugin-ensure/test/utils.unit.js
packages/artillery-plugin-ensure/utils.js

This PR is a rework of https://github.com/artilleryio/artillery/pull/2180.
Originally reported here: https://github.com/artilleryio/artillery/discussions/2166#discussioncomment-7110325, ensure is currently broken for most Playwright test assertions that include urls. The problem is more general though - any metric that includes special characters can hit this (such as custom metrics, created by name and metrics by endpoint).
As it's hard to predict what patterns can fall into this (as it depends on how the package filtrex is handling it), rather than going with an approach of replacing specific patterns, we hash all metricNames in the expression and variables, and use that with filtrex.
Unlike the previous PR, the source of truth for metric names now comes from the list of metrics …

fix(ensure): improve handling of metric names with special chars

---

package-lock.json
packages/commons/engine_util.js
packages/commons/package.json
packages/core/test/core/scripts/thinks_http.json
packages/core/test/core/test_think.js

- Complements https://github.com/artilleryio/artillery/pull/2084 by allowing think times to also work similarly, causing less confusion (like for example this discussion: https://github.com/artilleryio/artillery/discussions/2222).
- Also fixes the `think_time` tests which were not doing anything (`t.ok('stats should be empty', report.codes === {});` doesn't work, as the first argument is meant to be the assertion, not the msg. Also `report.codes === {}` doesn't work as a check either)

feat(core): allow multiple time formats in think times

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js
packages/core/lib/engine_http.js

- Fix vu.uuid attribute setting  
- Set attributes available in the beforeRequest hook before the request so they are available if an error occurs before the response
- Use `SemanticAttributes` object when setting attributes on spans. This ensures consistency across different instruments and systems.
- Add `HTTP_REQUEST_CONTENT_LENGTH`, `HTTP_USER_AGENT` and `HTTP_FLAVOR` semantic attributes to the request spans
- Parse URL to remove possible authentication details from the URL as required by convention:
- Add span error message along with the code for response status of 400 or more

fix(publish-metrics): fix vu.uuid and improve attribute handling

---

.github/workflows/examples.yml

I had originally used `--key` on this one example to allow for us testing that path. However, since in forks the GH secret is not available, it errors when trying to use it. 
By using the environment variable directly, it will just not send to cloud when that's not available, allowing the tests to still run.

fix(ci): remove --key flag from example run

---

packages/artillery/lib/util/validate-script.js
packages/core/lib/engine_socketio.js

The commits give more details, but in summary this PR fixes a couple of bugs around response matching so the tool behaves as the schema/docs indicate it should.
I've also broadened what `response.data` will accept (https://github.com/artilleryio/artillery/commit/22f1e569654230b47a8cde15390697e69a571aea), because:
- This currently wasn't supported
- As this feature was broken, it's unlikely anyone's depending on the current strict behavior
- IMO it's a good compromise between simplicity (no change to config) and additional functionality (matching multiple responses + substring instead of exhaustive match). Alternatives would include allow regular expressions + a specific setting for multiple messages, but I think this is a good starting point 😄 
Please let me know if I can provide more …

Socket.io engine fixes + more flexible `response.data` behavior

---

packages/artillery/lib/cmds/run.js
packages/artillery/lib/console-reporter.js
packages/artillery/lib/util.js
packages/artillery/test/cli/command-run.test.js

Collecting per-url metrics by default by loading the `metrics-by-endpoint` plugin by default behind the scenes.
- Creating `addDefaultPlugins` function that takes the final version of the script and adds the  default plugins and their config if they are not already listed on the script. (For now we only add `metrics-by-endpoint` by default but the function is created with extensibility in mind.)
The `metrics-by-endpoint` plugin  is set on the script with the two config settings: 
- `suppressOutput` - a newly created setting, used to exclude plugin created metrics from console
- `stripQueryString` - existing setting, removes query string from endpoint
- `addDefaultPlugins` is then called in the `prepareTestExecutionPlan` function as a last modification to the script.
- The final script is …

feat(artillery): collect per url metrics by default

---

packages/artillery/lib/platform/cloud/cloud.js

Leverages https://github.com/artilleryio/artillery/pull/2293 to initiate a `gracefulShutdown` of type `earlyStop` when Cloud API has set status of the test to `CANCELLATION_REQUESTED`.
A couple of things that could use opinions:
- I've set a 5 second timer on the interval. Please let me know if that's too long.
- Set a custom exit code to 8. No particular reason other than it being the number given in CP for this status - once we have a taxonomy for exit codes, we can change it if needed.

feat(artillery): implement stopping test from artillery cloud

---

packages/artillery-plugin-expect/index.js

Exclude failed expectation errors (present when `reportFailuresAsErrors` is set to true) from errors being logged to console with `expectationsPluginOnError` function.
Currently expect plugins `onError` hook function - `expectationsPluginOnError` logs the `'Error: {error message}'` string ( 'Error' being logged in red chalk), on every error. As `'not ok'` is already logged in red chalk for failed expectations, having additional 'Error' logged in red chalk is unnecessary. 
- The `expectationsPluginOnError` function was dormant until #2298 due to `onError` hook not functioning properly 
- [] Does this require an update to the docs?

refactor(expect): exclude failures from errors logged

---

packages/artillery/lib/platform/cloud/cloud.js

Noticed a couple of errors in the Artillery Cloud backend due to calling `/status` endpoint before test run exists in the DB. Since the stop test button only appears after the init event has completed, then we only need to start polling for `/status` at that point too.

fix(cloud): set status interval after testrun init event

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Treat the argument to `--memory` as number of GB if <= 120, and as MiB otherwise.

feat: allow setting memory on Fargate as just a number

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js

Improvements to OTel reporter:
- Ensure tracer is set only once per test rather than on every scenario run
- Remove mistakenly duplicated code - custom attributes are set on the span twice (they just replace the first ones set - no user facing change)

refactor(publish-metrics): set tracer once per test 

---

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

This PR refactors the shutdown code for ECS/Fargate to bring it closer to what local runs already do.
- Expose shutdown functionality via `global.artillery.shutdown()`
- Run `beforeExit` and `onShutdown` hooks inside the new `gracefulShutdown` function
- Centralize all shutdown logic in that function
- Ctrl+C stops the test straightaway now without needing to press it twice

refactor: graceful shutdowns on ECS/Fargate

---

package-lock.json
packages/artillery/lib/platform/cloud/cloud.js

Helps visualise better that the test run has stopped, in case there's a lot of logs between when it was requested, and when it finishes cancellation (e.g. high VU + expect).

refactor(cloud): add final log to cli when test run cancelled

---

packages/types/schema/config.js
packages/types/schema/engines/http.js
packages/types/schema/engines/socketio.js
packages/types/schema/engines/websocket.js
packages/types/schema/joi.helpers.js
packages/types/test/helpers.ts

- Adds `buildArtilleryKeyValue` to be reused throughout schema for adding arbitrary key:value pairs
- Adds correct typing for `environments` from config
- Adds correct typing for `cookies`, `headers`, `form` for http engine (`formData` and `qs` left out for now)
- Adds correct typings for some additional properties in ws and socketio engine
Tested directly with VS Code extension debugger. Example autocomplete of `environments`:

feat(schema): use proper schema for environments and arbitrary keyvalue

---

packages/artillery/package.json
packages/artillery/test/cli/_helpers.js
packages/artillery/test/cli/command-report.test.js
packages/artillery/test/cli/command-run.test.js

A step towards making these more readable and actionable on failures. 
Removes unneeded deleteFiles from within test assertions, and instead sends reports to a temporary directory. I'd like to also break out multiple conditional assertions into its own assertion, but that can be done later.

test(cli): send report files to tmpdir

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/platform/aws-ecs/ecs.js

fix(artillery): create default SSM parameters for ECS/Fargate tests

---

packages/artillery/lib/platform/aws-lambda/index.js

The dependencies became direct dependencies of Artillery when @platform/fargate was moved into the monorepo. They are not needed for workers running on AWS Lambda.
Fixes #2337

fix(artillery): reduce bundle size on AWS Lambda

---

packages/artillery/lib/platform/aws-ecs/legacy/util.js

This allows ECS/Fargate tests to be used in:
- `eu-west-2`
- `eu-west-3`
- `us-east-2`
- `us-west-2`
- `ca-central-1`
- `ap-east-1`
- `ap-northeast-2`
- `ap-southeast-1`
- `ap-southeast-2`
- `ap-northeast-1`
- `me-south-1`

feat(artillery): enable 11 more AWS regions for ECS/Fargate

---

.github/workflows/docker-ecs-worker-image.yml

At some point we'll enable this in branches too, but right now it this is a simple way to just trigger the workflow against a branch on demand, to get an ECR image to test against.

ci(docker): allow arbitrary building of worker image

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js

Fix for #2365 
When using `test.step` helper along with OTel tracing in a Playwright scenario, VUs that failed do not count toward `vusers.failed`.
The reason they are not counted is due to caught errors being debugged and not thrown from the reporters `step` method.

fix(publish-metrics): throw caught err in step handler

---

packages/types/schema/plugins/metrics-by-endpoint.js

- Fixes the `metricsPrefix` option to be the correct `metricsNamespace`
- Adds some information (description, titles, defaults) to the plugin

feat(schema): improve metrics-by-endpoint schema

---

package-lock.json
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/lib/platform/local/artillery-worker-local.js
packages/artillery/package.json
packages/artillery/test/cli/run-typescript.test.js
packages/artillery/test/scripts/scenarios-typescript/error.yml
packages/artillery/test/scripts/scenarios-typescript/lodash.yml
packages/artillery/test/scripts/scenarios-typescript/processor.ts

Adds support for typescript processors in run and run-fargate.
Some of the decisions that were explored and ended up being made:
- Disable for now in `aws:lambda` due to an issue with bundle sizes. Will be explored again later. As this is primarily for Playwright Typescript support, and Playwright does not run in Lambda, this is not urgent;
- Using `esbuild-wasm` as it is cross-platform compatible. Regular `esbuild` also works and installs the platform specific binary, but this is more future-proof for when we do provide Lambda support. This can easily be changed;
- For now using `global.artillery.hasTypescriptProcessor`. This can be changed a little bit later by refactoring some of the logic in `run`, but right now it felt unnecessary to tackle immediately.

feat(cli): add typescript support by bundling processor with esbuild

---

packages/artillery/test/cli/run-typescript.test.js

Enable test I accidentally disabled testing something. This test still ran successfully against all the logic, so no problem, but needs to be enabled for future runs.

test(cli): enable wrongly commented out TS test

---

packages/artillery-engine-playwright/index.js
packages/types/schema/engines/playwright.js

Switch to using browser contexts rather than browsers for VU isolation.
This is the same approach as that used by the Playwright Test Runner: 
https://playwright.dev/docs/browser-contexts
Previous behavior of using a new browser per VU can be enabled by setting `config.engines.playwright.useSeparateBrowserPerVU` to true.
----

feat(playwright): run VUs in new context rather than browsers by default

---

packages/artillery/lib/cli/common-flags.js
packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/cmds/run-lambda.js
packages/artillery/lib/cmds/run.js

With Fargate now in this repo, it's easier to consolidate common flags together. This prevents drift in descriptions and missing flags implemented in commands (e.g. Fargate doesn't have --variables, which has been reported as an issue).

refactor(cli): consolidate common run flags in same file

---

packages/artillery/lib/cli/common-flags.js
packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/cmds/run-lambda.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Solves https://github.com/artilleryio/artillery/issues/2261

feat(cli): expose --variables flag in fargate

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/cmds/run-lambda.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

- [feat(cli): add missing fargate flag descriptions](https://github.com/artilleryio/artillery/commit/ed4759ba97fb1eab6ab9fa0cf1974a7f58790336)
- [refactor(cli): move fargate flag descriptions inline](https://github.com/artilleryio/artillery/commit/550ed100cf586f3dafc79c797884b49db15da975)
- [fix(cli): make --secret fargate flag hidden](https://github.com/artilleryio/artillery/commit/078fda76a2e2001651660964fea69fab3a5ab720) (this might actually be meant to be deleted?)
- [feat(cli): set supported fargate regions as options to --region flag](https://github.com/artilleryio/artillery/commit/960b5ae505221bf0cbf7f840a5c5562923af65c6)
- [refactor(cli): set default fargate region in cli](https://github.com/artilleryio/artillery/commit/81e02ca5555a7f4590d003bf5a455be5baf74d3e)

feat: improve fargate cli flag descriptions and usage

---

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Fix for 2 Issues in the Fargate Datadog agent container setup:
1. Fixing a typo in the 'DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT' variable for the Datadog Agent
2. Adding a placeholder key for the `DD_API_KEY` variable to stop Fargate tests that don't need `datadog-agent` to break:
- Currently the Datadog agent container is built and runs on every Fargate test, even when users are not trying to send data to Datadog. This is causing tests that don't need datadog-agent to break, since the Datadog agent container exits without the Datadog API key set.

fix(fargate): run datadog agent only when datadog api key is configured

---

packages/artillery/lib/cmds/run.js

We [uninstall `esbuild-wasm` from Lambda](https://github.com/artilleryio/artillery/blob/0d6a000892bcf8d78e54b2cfb5178c2f768fc52d/packages/artillery/lib/platform/aws-lambda/index.js#L294) to prevent bundle size from increasing, as it's close to the limit. As a result, Lambda tests fail when they try to require the package on the top. 
As a workaround, conditionally requiring it only when TS usage is needed solves this. When bundle size is no longer an issue, we can revert this.

fix(lambda): require esbuild-wasm conditionally to fix lambda failure

---

packages/artillery/lib/cmds/run.js

Extending `sendTelemetry` function to send `publish-metrics` reporters used in order to get insights into which reporters are most popular with users.

feat(cli): record publish-metrics reporters usage with posthog

---

.github/workflows/run-aws-tests.yml
packages/artillery/test/cli/_helpers.js
packages/artillery/test/cloud-e2e/lambda/run-lambda.test.js

Debugging some CI AWS failures in https://github.com/artilleryio/artillery/pull/2407 proved quite challenging.
This PR exposes `ARTILLERY_CLOUD_ENDPOINT` and `ARTILLERY_CLOUD_API_KEY` when running the tests, so they will be sent to the cloud. It also adds `GITHUB_REPO` and `GITHUB_ACTOR` so we can add some additional tags to the tests for additional context.
*Note: this won't apply to this PR, as workflow changes (the passing of the variables) don't get reflected due to the usage of `pull_request_target`.*

test(aws): send aws tests to artillery cloud dashboard

---

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Only the arn of the leader task was being sent to cloud. This sends the arn of other created tasks too, as they're created.

fix(fargate): send taskArns of non-leader tasks to cloud

---

packages/core/lib/runner.js
packages/core/test/core/unit/context_functions.test.js

There are two issues with the current `$randomString` function:
- It will sometimes return a different length than specified, due to trailing zeroes
- It actually doesn't work for large lengths (n>10 I believe). It just always returns up to 10 chars
I tried and benchmarked quite a few possible variations of the function (e.g. using `crypto.randomBytes`, `lodash` utilities, etc). This solution was by far the fastest I got, even surpassing the existing function. 
Notes:
- This solution allows capital letters, but we can remove that if we want (I believe the previous solution didn't).
- Defaults to length=10 if no length is specified to keep it backwards compatible, since the previous function implicitly did this
- Added thorough unit test that checks for the regression. I also ran it with …

fix(core): make randomString deterministic and allow larger values

---

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker

Two changes here:
1. Explicitly exclude `node_modules_stream.zip` from being synced into workers, and wait for `node_modules.zip` to be available as intended instead.
2. Add a short wait in between launching a lead worker and launching more workers. This gives the lead task some time to finish pre-packing dependencies, but still allows other workers to provision in parallel should pre-packing take a while (which would be the case for tests with large dependency trees).
Fixes https://github.com/artilleryio/artillery/issues/2427

fix: improve task startup logic for Fargate

---

.github/workflows/run-tests-windows.yml
packages/artillery/package.json
packages/artillery/test/cli/run-typescript.test.js
packages/artillery/test/cloud-e2e/fargate/run-fargate.test.js
packages/artillery/test/unit/create-bom.test.js

We need some tests in Windows in order to fix a recent issue.
However, getting all tests to run on Windows proved more challenging than anticipated, and they run for quite long. I don't want to introduce instability to the CI pipeline, which is now fairly stable.
As a compromise, I'm introducing a workflow to run some windows smoke tests that I've narrowed down as seemingly stable. This will allow us to test the bug fix by running the `workflow_dispatch` against the branch with the fix, and will give us a workflow to run windows tests easily whenever needed.
Then we can work on iteratively getting more tests to run on windows, and introduce it to the pipeline later.
Notes:
- Some adjustments were made to tests and pipelines in order to be able to run. Some of them, like the TS assertion …

ci(test): add workflow for manually triggering windows tests

---

.github/workflows/run-tests-windows.yml

Quick follow up of https://github.com/artilleryio/artillery/pull/2430. In some cases the worker image needs to be overridden.

ci(test): allow ECR_IMAGE_VERSION to be set on windows tests

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/base.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js
packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker

Fix for OTel traces arriving inconsistently (in number and format) to observability platforms when running in Fargate 
Two different issues were observed, and usually at least one would happen:
1. All traces properly formed with the correct attributes and status, but some traces missing
2. Traces not properly formed - missing parent root spans, incorrect span status (errors not set on spans)
*Note: the issues would not happen on local runs, and issue 2. seems to only happen on Datadog.*
The issues seem to be a result of multiple factors:
- The wait for pending traces was not implemented in Playwright tracing possibly leading to triggering the `traceProvider ` shut down prematurely.
- In large tests with many traces the `maxExportBatchSize` and eventually the `maxQueueSize` could be …

fix(publish-metrics): otel tracing bug

---

packages/artillery-engine-playwright/index.js
packages/types/definitions.ts
packages/types/schema/engines/playwright.js

As discussed in #2438 
Introduces the ability to configure the selector by exposing the same variables that playwright.config.ts usually exposes in use. Similar to defaultNavigationTimeout and defaultTimeout.
I would have added tests but I could find an existing setup for the playwright engine to contribute to.
Resolves: #2438

feat(playwright): Added testIdAttribute configuration to playwright engine

---

.github/workflows/docker-ecs-worker-image.yml
.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-artillery.yml
.github/workflows/scripts/replace-worker-version-in-js-file.js
packages/artillery/lib/platform/aws-ecs/legacy/constants.js

Creates script to replace `DEFAULT_IMAGE_TAG` dynamically, and makes some changes to workflows to support it:
- https://github.com/artilleryio/artillery/commit/1be86387f1ebb6a3a2d1baad43c59f3a0b51633a: starts running docker publish as part of the npm publish. This is to prevent race condition where npm build might be pushed (with tests starting to use it) before publish is done.
- https://github.com/artilleryio/artillery/commit/7d6e8c9f2daf0f6e1fea0e24703cdcd5d45b9feb, https://github.com/artilleryio/artillery/commit/7e1810322bc0896099e36f17534aa122453359ad: add replace script and use it in canary/artillery publishes
- https://github.com/artilleryio/artillery/commit/219bff26a8950baf4c2566854b9c1f41f5894117: also publish worker image on canary publishes, since it is no longer doing so with …

ci: use the right docker image version in published artillery versions

---

.github/workflows/npm-publish-all-packages-canary.yml

Follow up of https://github.com/artilleryio/artillery/pull/2456
- `needs: publish-fargate-worker-image` is needed, or otherwise the two workflows will run in parallel. I had put it in the main publish, but forgot it in canary!
- Typo in path

ci(publish): fix path and missing needs workflow step

---

packages/artillery/lib/platform/aws-lambda/index.js

Uninstalls `artillery-plugin-publish-metrics` in Lambda tests, making it incompatible with Lambda tests for the short term (until we are able to move to Lambda container images).
I tested this locally. Without the uninstall I am also getting bundle size issues, with the install I don't. The Lambda test running in CI should also confirm this.

fix(lambda): disable publish metrics in lambda due to bundle size

---

packages/artillery-engine-playwright/index.js

This prevents a common annoyance where you run in headful mode locally to see what your script is doing and forget to turn it off before trying a run on Fargate.

feat(playwright): force headless mode when running in the cloud

---

packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/lib/platform/aws-ecs/legacy/create-test.js

Paths to send to s3 are built based on a windows file system, but they are ran in ubuntu in the AWS containers. We need to account for that and convert the paths if needed.

fix(fargate): convert to posix paths before sending files to s3

---

packages/artillery-engine-playwright/index.js

Follow up to #2455. Actually force headless mode when running on Fargate.

fix: set headless mode on Fargate if not already set

---

packages/artillery/lib/platform/aws-ecs/ecs.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/lib/platform/aws/aws-ensure-s3-bucket-exists.js

- Sets s3 lifecycle policy for Fargate (https://github.com/artilleryio/artillery/commit/e314fbe63b69b1502a08a209ac27197daf5d5c12) and Lambda tests (https://github.com/artilleryio/artillery/commit/48c76f9318ee2ccbd668417fbdfa77c499c3da4a)
- A small refactor (https://github.com/artilleryio/artillery/commit/46fd00072008d641f043b5de130b1c6b3d1e0b29) was done for Lambda to reuse utilities that were already there, and seemed to already account for Lambda region nuance. This way it automatically uses the created `setBucketLifecyclePolicy` function
*Note: as usual, best to review this PR commit by commit (using the commits I listed above).*
Please review the following:
- Actual lifecycle rules chosen. I chose 2 days for things containing test data, to give some time for people to be able to …

feat(cli): put s3 bucket lifecycle policy for aws tests

---

packages/artillery/lib/platform/aws/aws-cloudwatch.js

As seen in https://github.com/artilleryio/artillery/issues/2486, there might be missing permissions in the role being used to run artillery CLI, which would cause a confusing `warning` with a stack trace, despite the test continuing to run. This makes the `warning` message more easy to understanding.
The `warning` will look something like this now:
```
Launching workers... [11:58:44]
Waiting for Fargate... [11:58:45]
⠇ 
User: arn:aws:sts::ACCOUNT_ID:assumed-role/ROLE_NAME/SESSION_NAME is not authorized to perform: logs:PutRetentionPolicy on resource: arn:aws:logs:us-east-1:ACCOUNT_ID:log-group:artilleryio-log-group/artilleryio-cluster:log-stream: because no identity-based policy allows the logs:PutRetentionPolicy action
WARNING: Missing logs:PutRetentionPolicy permission to set Cloudwatch …
```

fix(fargate): improve cloudwatch retention policy user facing logs

---

packages/artillery/lib/platform/aws-ecs/legacy/plugins/artillery-plugin-sqs-reporter/index.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws-ecs/legacy/sqs-reporter.js

Currently Fargate doesn't listen to these events and consume them. This PR makes the events available to the CLI command, deduplicates them [in a similar way to launch platform implementation](https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/launch-platform.js#L69-L70), and then emits the corresponding Artillery Cloud event so `phaseStarted`/`phaseCompleted` appears correctly in the Cloud.
Has been tested against Artillery Cloud and phases appear correctly. Check screenshot:

fix(fargate): propagate phase events to cli and cloud

---

packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/lib/platform/aws-lambda/lambda-handler/index.js
packages/artillery/lib/platform/local/artillery-worker-local.js
packages/artillery/lib/platform/local/worker.js
packages/artillery/lib/util.js
packages/artillery/lib/util/generate-id.js
packages/core/lib/runner.js

This PR makes the test run ID of the current test run available as `$testId` template variable. The variable can be used in:
- `config` section as `{{ $testId }}`
- in scenarios as `{{ $testId }}`
- custom JS code as `vuContext.vars.$testId`
Works locally, and in cloud tests (AWS Lambda and AWS Fargate).

feat: make test run id available as $testId template variable

---

packages/artillery-plugin-publish-metrics/lib/cloudwatch.js
packages/artillery-plugin-publish-metrics/lib/dynatrace/index.js
packages/artillery-plugin-publish-metrics/lib/newrelic/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/metrics.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/base.js
packages/artillery-plugin-publish-metrics/lib/prometheus.js
packages/artillery-plugin-publish-metrics/lib/splunk/index.js
packages/artillery-plugin-publish-metrics/lib/util.js

Create `sleep` utility and use it throughout the plugin for all intentional delays

refactor(publish-metrics): create sleep utility for publish-metrics

---

packages/artillery-plugin-publish-metrics/lib/util.js

Fixing `sleep` function definition. Follow up to #2498

fix(publish-metrics): fix sleep init

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/metrics.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/base.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/http.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js

Adding the `test_id` attribute to all traces and metrics exported via OTel reporter.
Note:
- Only added to the `opentelemetry` reporter as it is the simplest. Can add in other reporters in another PR

feat(publish-metrics): add test id to all traces and metrics

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/metrics.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/base.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/http.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/vendor-translators.js

When `DEBUG` is set to a vendor-specific reporter (from `publish-metrics`) if that reporter is using OTel in the background we want to log OTel reporters debug logs as well.
e.g. When user uses the Datadog reporter for tracing and sets `DEBUG=plugin:publish-metrics:datadog`, we want to log debug logs from OTel reporter as well as OTel is the one running the tracing.
- OpenTelemetry's internal diagnostic handler will run if `DEBUG` is set to any reporter, not just `open-telemetry`
- Artillery's `debug` will be dynamically set for metrics and traces, using the `type` property from config set to the reporters name.
In config translator functions `type` is set on both `traces` and `metrics` part of config so that classes responsible for metrics and traces can set the debug accordingly. …

fix(publish-metrics): route debug correctly for publish metrics reporters

---

.eslintignore
examples/browser-playwright-reuse-typescript/README.md
examples/browser-playwright-reuse-typescript/test/e2e/.gitignore
examples/browser-playwright-reuse-typescript/test/e2e/helpers/index.ts
examples/browser-playwright-reuse-typescript/test/e2e/playwright.config.ts
examples/browser-playwright-reuse-typescript/test/e2e/tests/get-issues.spec.ts
examples/browser-playwright-reuse-typescript/test/performance/processor.ts
examples/browser-playwright-reuse-typescript/test/performance/search-for-ts-doc.yml

Adds an example for reusing a Playwright+Typescript codebase as Artillery tests.
The example also makes use of target as `baseURL`.

feat(examples): add example for reusing pw typescript tests

---

.github/workflows/docker-ecs-worker-image.yml
.github/workflows/run-aws-tests.yml

I just noticed that all image versions generated by AWS tests seem to be pointing to the `main` branch ref 💀 (https://github.com/artilleryio/artillery/actions/workflows/run-aws-tests.yml). I actually believe it is currently overriding the latest image in main. So the tests run against the right version of the code (which is why they pass), but the main branch image version gets overridden each time.
Important to fix ASAP.
P.S. This hasn't affected any `production` CLI release versions - fortunately there were pushes between each release and the next commit that had `run-aws-tests` each time.

ci(worker): fix broken ecs worker image version push

---

.github/workflows/run-aws-tests.yml

Follow up of https://github.com/artilleryio/artillery/pull/2527. Also need to update `ECR_IMAGE_VERSION` that is passed to the tests to the now correct value (branch `github.event.pull_request.head.sha`).
This is why AWS tests are [failing](https://github.com/artilleryio/artillery/actions/runs/8103062515/job/22146983419) in https://github.com/artilleryio/artillery/pull/2522

ci(tests): pass correct ECR_IMAGE_VERSION to aws tests

---

packages/artillery-plugin-memory-inspector/index.js
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/lib/platform/local/index.js
packages/artillery/lib/platform/local/worker.js
packages/artillery/package.json
packages/artillery/test/cli/async-hooks-esm.test.js
packages/artillery/test/cli/run-typescript.test.js
packages/artillery/test/cloud-e2e/fargate/fixtures/ts-external-pkg/processor.ts
packages/artillery/test/cloud-e2e/fargate/run-fargate.test.js
packages/artillery/test/scripts/scenario-async-esm-hooks/helpers.mjs
packages/artillery/test/scripts/scenario-async-esm-hooks/test.yml
packages/artillery/test/scripts/scenarios-typescript/processor.ts
packages/core/lib/engine_http.js
packages/core/lib/engine_ws.js
packages/core/lib/runner.js

This PR add support for using async functions as hooks in HTTP and WebSocket engines, and the ability to load ES modules via `config.processor`.
**Hooks:**
- `beforeRequest`, `afterResponse`, `beforeScenario`, `afterScenario`, and `function` hooks in the HTTP engine
- `function` hook in the WebSocket engine
**ESM:**
- If the extension of a processor file is `.mjs`, it will be [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)'ed rather than `require()`'d.
----
----
Fixes #1269 #1384

feat: async hooks and ESM

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/test/cloud-e2e/fargate/run-fargate.test.js

https://github.com/artilleryio/artillery/pull/2301 introduced a bug where `--launch-config` would no longer correctly set `memory` and `cpu`.
---
Funny enough, the `memory-hog` test (which was added later after that PR) was correctly catching this error, which is why it was failing - it had been wrongly modified to expect the non-zero code. #trustTheTests
I added some tests proving the fix and the feature work, leveraging the same `memory-hog` test.

fix(cli): remove cpu/memory flag defaults to fix launch-config override

---

packages/artillery-engine-playwright/test/fargate.aws.js
packages/artillery-engine-playwright/test/fixtures/processor.js
packages/artillery-engine-playwright/test/fixtures/processor.ts
packages/artillery-engine-playwright/test/fixtures/pw-acceptance.yml
packages/artillery-engine-playwright/test/index.test.js

Possibly due to contention of resources on CI, sometimes it's not able to find the element in time. Increasing the timeout should help for now. Will monitor the test.

test(playwright): refactor to use artillery website to be more reliable

---

.github/workflows/run-aws-tests.yml

Needed for https://github.com/artilleryio/artillery/pull/2481
Spoke with @bernardobridge and he mentioned these need to be in `main` before the workflow in my branch has access to it, as changes to this particular workflow won't be reflected unless in `main` first

ci(test): make datadog keys available to test runs

---

packages/types/schema/config.js

- Adds missing `config.bundling.external`
- Improves description of processor

fix(schema): add missing typescript information in schema

---

packages/artillery-engine-playwright/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js

Fix for #2529 
Before https://github.com/artilleryio/artillery/pull/2418, Playwright tracing only worked with OTeL, but now it can work with other reports that use OTeL behind the scenes.
We now check for a `OTEL_TRACING_ENABLED` variable set by the otel reporter instead, which should be in control of whether tracing is needed (which also reduces the coupling between the PW engine and publish-metrics).
Tested locally and with Fargate. Automated tests for this as not very easy (as it depends on platform integrations), so can be added separately.

fix(playwright): ensure engine knows when tracing is enabled

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json
packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

Updating to latest Playwright version. Includes [1.42.0](https://github.com/microsoft/playwright/releases/tag/v1.42.0) and [1.42.1](https://github.com/microsoft/playwright/releases/tag/v1.42.1)
Things that were updated and could break backward compatibility apply to `@playwright/test`. `1.42.1` also includes some fixes to things broken by `1.42.0`.

dep(playwright): update Playwright to v1.42.1

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/cloud/cloud.js
packages/artillery/test/cli/errors-and-warnings.test.js

This PR improves error handling & reporting when a test is recorded to Artillery Cloud.
The CLI will print more specific error messages when API key is not provided, or is invalid, and when Artillery Cloud can't be reached.
The CLI will stop the test run early now if the API key is missing or is invalid.

feat: improve error handling & messages when recording to Artillery Cloud

---

.github/workflows/run-aws-tests.yml
.github/workflows/scripts/get-tests-in-package-location.js
packages/artillery-engine-playwright/package.json
packages/artillery/package.json

The current `run-aws-tests` runs take close to 40 minutes, and it will only grow. This PR adds the ability to parallelise that leveraging [Github Actions matrix jobs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs), making each job run each test file in isolation. We use this rather than parallelising at test runner (tap) level to improve the readability and our ability to debug the output.
We accomplish this by:
- Adding the `.github/workflows/scripts/get-tests-in-package-location.js` script, where we specify a list of locations we wish to parallelise for this purpose, and it outputs the files that need to be parallelised.
- With the above setup, any new file added in a relevant location will automatically become parallelised (i.e. result in an additional …

ci(test): add ability to parallelise aws tests

---

.github/workflows/run-aws-tests.yml

Follow up of https://github.com/artilleryio/artillery/pull/2544.
If one of the tests fail, it's still valuable to see whether others pass, rather than cancel them (especially now that they are running in parallel).

ci(test): stop failing fast on matrix aws jobs

---

packages/artillery/lib/cmds/run.js

Adding `apdex` to the list of official plugins in `sendTelemetry` as it was missing.

fix(cli): add apdex to official plugins for telemetry

---

packages/artillery-plugin-metrics-by-endpoint/index.js

Extend `metrics-by-endpoint` to track errors such as `ETIMEOUT` by request URL.
Example hello-world run:

feat: add ability to track errors by URL with metrics-by-endpoint

---

examples/artillery-plugin-hello-world/index.js
examples/artillery-plugin-hello-world/test.yml

This was happening due to the usage of `strict`, which would run into this [`TypeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_assign_to_property). 
Solution was either to remove `strict` or change the processor line to something like
```js
script.config.processor = script.config.processor ? new String(script.config.processor) : {};
```
To prevent additional overhead for those writing a plugin, went with removing strict.

fix(example): make custom plugin work when adding a processor

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Make values available as early as possible for any code that may need them.
Fixes #2582

fix: load values from a dotenv file earlier

---

packages/artillery/lib/console-reporter.js

I had tested this when implementing https://github.com/artilleryio/artillery/pull/2084, but with `1min`, so didn't notice that it appended the `s` at the end (`1mins`).
Fixed now to account for all cases.

fix(cli): log duration with time units when specified

---

package-lock.json
packages/artillery-engine-playwright/index.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/cloud/cloud.js
packages/artillery/package.json

This PR adds the following:
* Capture Playwright traces for failing VUs and store them on the filesystem (locally or in Fargate workers)
* Upload them to Artillery Cloud (an account with an API key is required)
This is early experimental support for it and not something ready for production use yet.

feat: initial Playwright tracing support

---

packages/artillery/lib/telemetry.js
packages/artillery/test/lib/test_telemetry.js
packages/skytrace/src/telemetry.ts

Posthog captures the IP Address by default and there is no direct setting for disabling this, however an override can be set for the IP address by providing $ip property, which is what we have in our code:
```yaml
... 
eventPayload = {
event,
distinctId: data.distinctId || 'artillery-core',
properties: {
...data,
version: artilleryVersion,
os: process.platform,
isCi: isCI,
$ip: null,
}
};
...
```
However it seems that Posthog evaluates the `null` as if no `$ip` property override is provided and therefore captures and sets it. 
Changing the value to a truthy value fixes this. 
PR Template

fix(cli): set ip override to truthy value

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/base.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/http.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker
packages/artillery/lib/platform/aws-lambda/lambda-handler/index.js

- The spans are counted with the custom `counter` event, and will show in the console reports as well as the final report under `plugin.publish-metrics.spansExported` metric name
- On `done` event span count and the destination (observability platform that spans are exported to) are sent to Posthog as an event called `otel-span-count` with `spansExported` and `destination` properties and will be aggregated on Posthog
- The destination will be either:
-  reporter `type` if vendor specific reporters are used, 
- a destination recognised from the `endpoint` (as one of `lightstep`, `honeycomb`, `new-relic`, `dynatrace` or `grafana`) if configured through the OTel reporter
- `custom` if configured through the OTel reporter but not recognisable from the `endpoint` 
Since we need telemetry to be …

feat(publish-metrics): record the number of spans sent 

---

packages/artillery-plugin-publish-metrics/index.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/translators/vendor-adot.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/translators/vendor-otel.js
packages/artillery-plugin-publish-metrics/test/unit/adot-translators.js
packages/artillery/lib/platform/aws-ecs/ecs.js
packages/artillery/test/cloud-e2e/fargate/adot.test.js
packages/artillery/test/cloud-e2e/fargate/cw-adot.test.js
packages/artillery/test/cloud-e2e/fargate/dd-adot.test.js
packages/artillery/test/cloud-e2e/fargate/fixtures/adot/adot-cloudwatch.yml
packages/artillery/test/cloud-e2e/fargate/fixtures/adot/flow.js
packages/artillery/test/cloud-e2e/fargate/fixtures/adot/helpers.js
packages/types/schema/plugins/publish-metrics.js

Implementing tracing support for the Cloudwatch reporter. The reporter will use OpenTelemetry reporter in the background for tracing, and traces will be exported to AWS X-Ray.
Cloudwatch agent (or ADOT) installation  is required for local runs, but for Fargate runs the ADOT sidecar will be dynamically configured to send traces to AWS X-Ray.
```yaml
plugins:
publish-metrics:
- type: cloudwatch
sendOnlyTraces: true
traces: 
sampleRate: 0.5
useRequestNames: true
annotations:
tool: "artillery"
```
Unit tests added on `publish-metrics` side and an e2e test added on the `cli` side
- **Important:** Users that wish to use this feature with Fargate runs and had already ran Artillery tests on Fargate in the past will need to **delete the `'artilleryio-ecs-worker-role'` IAM role and the …

feat(publish-metrics): implement tracing for the cloudwatch reporter

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/translators/vendor-adot.js

Tweaking the ADOT config settings for the Datadog reporter.
- At times, when sending traces to Datadog in Fargate test runs, some traces would not reach Datadog. (Discovered through intermittently failing Datadog-ADOT e2e test)
- The spans reach the ADOT container but the last batch does not seem to get exported with the Datadog exporter.
- This seems to happen due to the Fargate task being terminated before the `batch` processors `timeout` interval has passed, causing the last batch of data to be dropped.
- Changing the `batch` processors `timeout` interval from `10s` to `2s` seems to fix the issue, as the `2s` seems short enough for batch to be sent to the exporter, and exported before the `terminate` signal is sent to ADOT.
- The solution was tested by running the original e2e test on …

fix(publish-metrics): adjust adot settings for datadog

---

packages/types/schema/scenario.js

Currently, `before` with `engine: playwright` is showing as red in the VS Code Extension. As `before` is not properly typed yet, I'll temporarily remove the `required` field for `flow`. 
Long term, we will look to consolidate the `scenarios` and `before/after` section into something reusable, so that `before/after` can be properly typed.

fix(schema): make flow not required for now

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/base.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/http.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/translators/vendor-otel.js
packages/artillery-plugin-publish-metrics/package.json
packages/artillery-plugin-publish-metrics/test/unit/tracing.js
packages/types/schema/plugins/publish-metrics.js

- Based on discussion [here](https://github.com/artilleryio/artillery/discussions/2592).
- Implementing `replaceSpanNameRegex` config option in tracing for all reporters that will allow replacing patterns in span names by specifying the regex pattern and the replacements string.
- This is mostly provided for the purpose of quantization, allowing users to group spans that contain randomised patterns but are, for the purpose of analysis, essentially the same.
```yaml
plugins:
publish-metrics:
- type: honeycomb
apiKey: "{{ $env.HC_API_KEY }}"
dataset: "my-service"
replaceSpanNameRegex:
- pattern: get_user_[a-zA-Z0-9]+
as: get_user_id
```
- In the example above page span in Playwright tracing `Page: https://get_user_jd83rh47fhfaAjh7snjqh` would be changed to `Page: https://get_user_id`.
- …

feat(publish-metrics): implement replaceSpanNameRegex setting

---

packages/artillery-plugin-publish-metrics/test/unit/adot-translators.js

A fix for `adot-translators` unit tests.
- Change made in https://github.com/artilleryio/artillery/pull/2610 needs to be reflected in the unit tests. No errors happened when this PR was merged due to tests not being connected properly at the time. 
- Tests were connected properly in https://github.com/artilleryio/artillery/pull/2607. This PR caused errors to show only [on merging](https://github.com/artilleryio/artillery/actions/runs/8521256202/job/23339036592), as the initial pre merge tests ran prior to the other (datadog-adot fix) PR being merged.

fix(publish-metrics): adjust tests to reflect adot changes

---

packages/artillery/lib/platform/cloud/cloud.js

A bit of a bruteforce solution but seems to work well.
* Wait for 10s before attempting to upload a new trace file
* Wait for up to 30s for all in-flight uploads to be completed

fix: reduce likelihood of incomplete uploads

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json
packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

Updating to latest Playwright version. Includes [1.43.1](https://github.com/microsoft/playwright/releases/tag/v1.43.1) and [1.43.0](https://github.com/microsoft/playwright/releases/tag/v1.43.0)
These releases don't seem to introduce breaking changes, only new API's.

dep(playwright): update Playwright to v1.43.1

---

packages/artillery/test/cloud-e2e/fargate/fixtures/adot/flow.js

Changing the flow of CloudWatch ADOT e2e Playwright test. 
The test flow was using the `Join Artillery Cloud early access waitlist` button which will soon be removed, so a different flow  is used instead.

refactor(test): change cw test flow

---

packages/artillery-plugin-expect/test/index.js
packages/artillery-plugin-expect/test/parallel.yml
packages/artillery-plugin-metrics-by-endpoint/test/fixtures/scenario-parallel.yml
packages/artillery-plugin-metrics-by-endpoint/test/index.spec.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/http.js
packages/artillery/test/cli/command-run.test.js
packages/artillery/test/scripts/scenario-with-parallel/processor.js
packages/artillery/test/scripts/scenario-with-parallel/scenario.yml
packages/core/lib/engine_http.js

- To make `publish-metrics` tracing work correctly with the `parallel` scenario setting, we map request level spans to request id's so we are able to appropriately manage them.
- To be able to accomplish this request `uuid` has been made available to all request hooks through `requestParams`
- Request level spans are opened and set on the `vuContext` in the `beforeRequest` hook, and then pulled from the `vuContext` and closed in the `afterResponse` hook.
- The change in this PR will ensure that:
- The request span set on `vuContext` will not get overriden  in parallel runs (where multiple `beforeRequest` hooks run before the `afterRequest` hooks are triggered)
- The appropriate request span is accessed for closing in the `afterResponse` hook
**CLI**
- Request `uuid` variable is created …

feat(publish-metrics): map request spans to req ids

---

packages/artillery-engine-playwright/index.js

This was probably mistakenly removed in https://github.com/artilleryio/artillery/commit/51886179a997f50786237dcdb73619de0710476c
Stack traces are very useful in Playwright tests (due to usage of expect, etc), so this brings that functionality back, regardless of using extended tracing or not.

fix(playwright): add back showing errors and stack trace in console

---

.github/workflows/create-release-pr.yml

Follow up of https://github.com/artilleryio/artillery/pull/2642, missed the need to update the actual package name when doing --workspace

ci: fix using actual package name

---

.github/workflows/create-release-pr.yml
.github/workflows/npm-publish-all-packages.yml

`skytrace` has an ongoing bug due to using an old version of oclif. This should be fixed in the npm scripts (we have a couple of workarounds for it in places now). 
Disabling it for auto releases for now and creating a ticket to address this separately.
```
> oclif readme && git add README.md
TypeError: command.args.filter is not a function
npm ERR! code 1
npm ERR! path /home/runner/work/artillery/artillery/packages/skytrace
npm ERR! command failed
npm ERR! command sh -c oclif readme && git add README.md
```

ci(skytrace): temporarily remove skytrace from release automation

---

.github/workflows/docker-publish-artillery.yml

Follow up of https://github.com/artilleryio/artillery/pull/2651 to allow workflow to be triggered from a `workflow_dispatch` (either directly here, or from another workflow that was workflow_dispatch and calls this one)

ci(docker): add workflow dispatch to docker publish

---

packages/types/schema/plugins/publish-metrics.js

New Relic and Dynatrace reporters had wrong type specified for `attributes` in VS code extension

fix(schema): fix attribute types for nr and dynatrace reporters

---

packages/artillery/lib/cmds/run.js

Sending target URL to Cloud  by adding it to `test:init` events `metadata` in `run.js`.
`ArtilleryCloudPlugin` will then take the metadata and send it to Cloud in its `testrun:init` event as seen [here](https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/platform/cloud/cloud.js#L51)
**Note**
- The target URL is pulled from a final script version that already went through all parsing and templating so that it works with any available way to provide the target URL and any overrides
**Testing:**
Tested manually with:
-  `--target` flag override, 
- target value as a variable
- target value as env var
- using `environments`
- Logged the metadata object sent in `testrun:init` event from `cloud.js`
Correct target was sent every time

feat(cli): send target url to cloud

---

examples/multiple-scenario-specs/README.md

The command "artillery probe" doesn't seem to exist, but "skytrace probe" does and produces the pictured output.

Change artillery probe to skytrace probe in README.md

---

packages/artillery/lib/cmds/run-fargate.js

Fixes [`--task-role-name` flag](https://www.artillery.io/docs/reference/cli/run-fargate#fargate-specific-flags).
Solves https://github.com/artilleryio/artillery/pull/1937#discussion_r1540962905

fix(cli): make --task-role-name work on fargate

---

packages/artillery-engine-playwright/index.js

Emitting errors from the Playwright engine. This means that errors will show up in reports, and (for recorded tests) on Artillery Cloud dashboard as well.
For simplicity errors are divided in 2 groups:
-  `Assertion` errors caused by `expect` will be recorded as `pw_failed_assertion.{expectation}`
- Any other errors will be recorded as `{error.message}`
The error messages have been cleaned by removing any ANSI codes as well as any additional lines - just the first line is used
**Testing:**
Tested manually by causing multiple different failed assertions and errors types.
**Note:**
- Error handling logic of the Playwright engine in general should be reexamined and addressed in a separate PR in necessary.

feat(playwright): emit errors

---

packages/artillery-plugin-expect/index.js

Expect plugin scenario level configuration is meant for expectations only. If an unsupported expectation is used, the following error will appear:
With this PR a helpful message is logged instead:  `Expect Plugin: Expectation <name> is not supported`, and only valid expectations are added to `results` preventing the error.

refactor(expect): log msg when unsupported expectation is used

---

.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-all-packages.yml
package-lock.json
packages/artillery-plugin-slack/LICENSE.txt
packages/artillery-plugin-slack/index.js
packages/artillery-plugin-slack/package.json
packages/artillery/lib/cmds/run.js
packages/types/schema/config.js
packages/types/schema/plugins/slack.js

Integrating with Slack  via  `slack` plugin, allowing users to receive a Slack message with a basic test overview.
The message will contain the following information:
- Whether test has passed or failed
- Test duration
- Link to the test in Artillery Cloud if recorded
- VUs completed / created
- Errors
- `ensure` plugin checks if set
---
_Failed test with errors and both passed and failed `ensure` checks:_
---
_Successful test with no `ensure` checks and no errors present:_
Users need to create and provide the Slack webhook URL as shown in the first 3 steps [here](https://api.slack.com/messaging/webhooks#getting_started)
```yaml
config:
plugins:
slack:
webhookUrl: "{{ $env.SLACK_WEBHOOK_URL }}"
```

feat(slack): implement slack integration

---

packages/artillery-engine-playwright/test/fargate.aws.js
packages/artillery-engine-playwright/test/fixtures/processor.ts
packages/artillery-engine-playwright/test/fixtures/pw-acceptance-ts.yml
packages/artillery-engine-playwright/test/fixtures/pw-acceptance.yml
packages/artillery-engine-playwright/test/index.test.js
packages/artillery-plugin-ensure/test/index.spec.js
packages/artillery/test/cloud-e2e/fargate/ensure-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/expect-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/memory.test.js

If the CLI exits with a zero exit code when it's supposed to be a `non-zero`, then it will never make it to the `catch (output)` part, and will simply pass (as it doesn't run through any of the expectations).
This fixes that for all tests that use this pattern.
Note: Also fixed a couple of other things wrong with tests that this uncovered.

test(cli): add expectation to correctly have non-zero exit code

---

.github/workflows/docker-ecs-worker-image.yml
.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-all-packages.yml
.github/workflows/run-aws-tests.yml

Follow up of https://github.com/artilleryio/artillery/pull/2693 and https://github.com/artilleryio/artillery/pull/2708, since there was still a bug. 
Simplifies the logic by making things explicit. In the previous iteration it was too hard to figure out when the commit sha would be used or not, and also which sha. Now the caller workflows determine that, making it easier to follow.

ci(publish): explicitly set ecs worker image overrides

---

packages/artillery-engine-playwright/index.js
packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/cloud/cloud.js

- Write Playwright traces to `/tmp/$testRunId` instead of just `/tmp`
- This should fix `ENOSPC` errors on Fargate due to running out of file watchers
- Use Chokidar's built-in API for detecting when a file is no longer changing, instead of hardcoded wait of 5 seconds

fix: write Playwright traces to a unique directory

---

.github/workflows/docker-ecs-worker-image.yml
.github/workflows/npm-publish-specific-package.yml

`pull_request_target` (from Run AWS workflow) makes it so that the `if: ${{ github.ref == 'refs/heads/main' }}` check doesn't work correctly. It wasn't possible to test on the previous branch, as changes have to be in the workflow first, but https://github.com/artilleryio/artillery/pull/2718 has failed workflows due to this. We can test in that branch once we merge this.

ci(publish): ensure correct version overrides

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/http.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js

- The change to request spans in #2628  was not reflected in the `onError` hook. Due to this request spans with errors were not appropriately closed and were therefore not exported. All the error data was still shown in the scenario span but the request span was missing
- Before when an error happens, it would be recorded on the span it belongs to and on the root span of the trace the original span belongs to. 
- Now the error will be recorded on the root (scenario) span only when it happens during the scenario but outside of any child spans (e.g. outside any requests in a scenario but still during that scenario execution)
- This will allow for better automatic parsing and displaying of data on observability platforms, showing a realistic number of errors that happened during a specific …

refactor(publish-metrics): improve error and outlier handling in traces

---

packages/artillery-engine-playwright/index.js
packages/artillery/lib/platform/cloud/cloud.js

- Reduce the cooldown period for collecting recordings to 1-5m (down from 5-10m)
- Increase the number of VUs that may be recording concurrently to 3 (up from 1)
- Track collected/discarded recordings with `browser.traces_collected` and `browser.traces_discarded` metrics
- Allow customization of tracing behavior (**internal use only ⚠️ - may change without notice**)

feat: Playwright tracing configuration

---

package-lock.json
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/lib/platform/aws-lambda/dependencies.js
packages/artillery/package.json

The node versions we support as per our engines constraint already have a built in function for determining if a module is built in.
This removes the dependency and uses the built in function instead.

feat: remove is-builtin-module

---

.github/workflows/docker-ecs-worker-image.yml

Still broken after https://github.com/artilleryio/artillery/pull/2730, just making this a single line like before, as this is hard to test.

ci(docker): build docker image in single line command

---

packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/test/cloud-e2e/lambda/fixtures/quick-loop-with-csv/blitz.yml
packages/artillery/test/cloud-e2e/lambda/fixtures/quick-loop-with-csv/helpers.js
packages/artillery/test/cloud-e2e/lambda/run-lambda-container.test.js

Follow up of https://github.com/artilleryio/artillery/pull/2674. We have a way to host private ECR image and make it accessible to others.
This will need a workflow to create one for CI (tests will be improved then), and the ECR repo will need the right permissions.

feat(lambda): use artillery-hosted ECR image

---

packages/artillery/lib/platform/aws-lambda/dependencies.js

Quick fix, bug introduced in https://github.com/artilleryio/artillery/pull/2674 . Fixing this in case we keep zip file for now and it gets forgotten.

fix(lambda): revert console log to debug log

---

packages/artillery/test/cli/command-run.test.js
packages/artillery/test/scripts/scenario-named/scenario.yml
packages/core/lib/runner.js

Addresses https://github.com/artilleryio/artillery/issues/2673 by allowing regex or exact match. I think this allows the maximum flexibility for the flag without breaking any existing workflows.

fix(core): allow scenario name exact match without using regex

---

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Fargate mainline/canary will be broken by https://github.com/artilleryio/artillery/pull/2693 with:
This should solve it, it's the same we use to create the Lambda function name now. Thanks @InesNi for noticing this.

fix(fargate): replace special characters in task name

---

packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/lib/util.js
packages/artillery/test/unit/before_after_hooks.test.js
packages/core/lib/runner.js

This will be useful when it's necessary to reference a path in the test config, but it's not one we know to resolve automatically (e.g. processors and payloads). 
One known use case right now is the Playwright Engine's `storageState`. Our current [example](https://github.com/artilleryio/artillery/tree/main/examples/browser-playwright-reuse-authentication) to reuse authentication by leveraging storageState is broken, and this is one way to fix it.
Note: I first cleaned up existing logic a little bit (https://github.com/artilleryio/artillery/commit/9da818aaa852fb68bc2a2613fdb591fa324ffc26), so best to review commit by commit.
I intend to add an automated test, but didn't have time yet. I've tested manually against Fargate and locally (using the example), and it works.

feat(cli): expose dirname utility to test scripts

---

examples/browser-playwright-reuse-authentication/README.md
examples/browser-playwright-reuse-authentication/flow.js
examples/browser-playwright-reuse-authentication/scenario.yml

Use `$dirname` introduced in https://github.com/artilleryio/artillery/pull/2614 to properly resolve the `storageState` path in local and distributed runs, fixing the example.

fix(examples): use dirname to fully resolve storageState in example

---

package-lock.json
packages/types/package.json

There was a CI bug when publishing https://github.com/artilleryio/artillery/pull/2744, so upping the version again, as this is internally used only anyway.
Includes:
- https://github.com/artilleryio/artillery/pull/2658
- https://github.com/artilleryio/artillery/pull/2688

ci: release v0.11.0 @artilleryio/types

---

packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/test/cloud-e2e/lambda/run-lambda-container.test.js

This will predominantly be used for internal purposes, allowing us to teardown the function immediately after testing. Tests have been modified to do that, although when we add more tests we may want to also test keeping the function between runs.

feat(lambda): allow tearing down of lambda container via env var

---

packages/artillery/lib/create-bom/create-bom.js
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/lib/platform/aws-lambda/dependencies.js
packages/artillery/lib/platform/aws-lambda/lambda-handler/a9-handler-dependencies.js
packages/artillery/lib/platform/aws-lambda/lambda-handler/a9-handler-index.js
packages/artillery/test/cloud-e2e/fargate/fixtures/mixed-hierarchy/config/config-no-file-uploads.yml
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js

This copies over a Fargate test, then fixes the issue it uncovered. There's a few small things it solves to improve the experience overall:
- https://github.com/artilleryio/artillery/pull/2750/commits/50ba526ed0bd47027762e9ef21c6fdce273ec13e : Adds the test
- https://github.com/artilleryio/artillery/pull/2750/commits/86d2efae3c75569d31597f7aea431bd24d1e8356 : Adds dependency tree logic from Fargate
- https://github.com/artilleryio/artillery/pull/2750/commits/17a20593dc294b32b8bdb5e59753e02c11100882 : Appropriately catch errors from S3 sync - currently it would continue without any user feedback
- https://github.com/artilleryio/artillery/pull/2750/commits/4e70e1e0cb8ea99590beccc05d8d20455e65892c : look for files recursively when doing the file count check (files uploaded == files available …

fix(lambda): make Lambda containers work with hierarchical deps

---

packages/artillery/lib/platform/aws-lambda/dependencies.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/lib/platform/aws-lambda/lambda-handler/a9-handler-index.js
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js

This PR implements the Fargate `simple-bom` test for Lambda. This uncovered a couple of issues due to not running some of the bom functions (e.g. `expandDirectories`).
- https://github.com/artilleryio/artillery/commit/ac92d7a12ebe417d110b4bddaa9a2d105f18dec4 makes Lambda use Fargate's bom. As it turns out we can now actually just use Fargate BOM's directly, simplifying things further.
- In addition to that, the `simple-bom` test relies on using packages like `js-yaml` and `uuid` that aren't installed as dependencies but exist as Artillery deps. In Lambda that was erroring, so https://github.com/artilleryio/artillery/commit/674edca532a19af8a4837fbb6a3627c15292f3f4 fixes the `NODE_PATH` to work similar to Fargate (accounts for both locations).
Note: the old BOM implementation was kept for …

fix(lambda): make lambda containers handle dependencies like fargate

---

packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/lib/platform/aws-lambda/lambda-handler/a9-handler-index.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js

Currently errors from workers still make the main CLI process exit with 0. This is inconsistent with Local and Fargate, and can lead to incorrect behaviour in CI and Artillery Cloud (e.g. filtering). Particularly relevant for things like `expect`.
Note: this API will allow us to define specific exit codes for different types of workerErrors (e.g. TestDataSync), but right now I have just defaulted to 1 for everything. Only in the case of `ArtilleryErrors`, it will use the exitCode from the CLI in the worker.

fix(lambda): handle nonzero codes from workers

---

packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/test/cloud-e2e/lambda/fixtures/dotenv/.env-test
packages/artillery/test/cloud-e2e/lambda/fixtures/dotenv/dotenv-test.yml
packages/artillery/test/cloud-e2e/lambda/fixtures/dotenv/processor.js
packages/artillery/test/cloud-e2e/lambda/lambda-dotenv.test.js

Implements mechanism similar to zipfile Lambda of bundling the .env file (in this case in S3 instead of in Zip). Currently only for container Lambda, but we can make this work in Fargate as well separately if desired.

feat(lambda): bundle dotenv file in lambda containers

---

packages/artillery/lib/platform/aws-lambda/dependencies.js
packages/artillery/lib/platform/aws-lambda/index.js

This PR implements the fix done for Windows in https://github.com/artilleryio/artillery/pull/2431, now in Lambda containers. The rest of the change is picked up automatically since Lambda now uses Fargate's BOM.
Has been tested using a Github Action and the `simple-bom` test against Windows.

fix(lambda): convert to posix paths before sending files to s3

---

.github/workflows/docker-ecs-worker-image.yml

This changes the worker image build system to build both architectures and publish to both ECR's, leveraging `strategy` to build them all in parallel. 
This will enable the move to Lambda Container Images to still allow choosing the desired architecture (and defaulting to the more performant arm64). We should also be able to have Fargate on both architectures (will need testing).
I have tested that `arm64` architecture works with Lambda.
Unfortunately due to the usage of `pull_request_target` in AWS tests, this workflow can't be tested yet. Thus why I haven't made the corresponding change in CLI code. I'll make those changes in a separate PR once this is pushed to main, which will allow testing.

ci(docker): publish arm64 and x86_64 images to private and public ecr

---

.github/workflows/docker-ecs-worker-image.yml

Follow up of https://github.com/artilleryio/artillery/pull/2772 . `arm64` can't build in ubuntu without emulation (QEMU).
Can't test in this branch, will have to be tested in https://github.com/artilleryio/artillery/pull/2773 after merging to main.

ci(docker): use official docker action with qemu to build arm64

---

.github/workflows/docker-ecs-worker-image.yml
.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-all-packages.yml
.github/workflows/npm-publish-specific-package.yml

Using the `docker/build-push-action` uses buildx and sets an `image manifest` type which is unsupported by Lambda. We now build the image with `docker build` as before, but setup `qemu` to ensure emulation is present for building `arm64`.
Note: builds `arm64` conditionally so we can skip in PR's for now (given how long it takes). We can then add smoke tests to main against canary.
Tested this in another branch with a `workflow_dispatch` build, and locally triggered some Lambda tests against arm64 and x86_64. All seems to be working.

ci(docker): build single architecture instead of multi arch image manifest

---

packages/artillery/lib/cmds/run-lambda.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-dotenv.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-ensure.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js
packages/artillery/test/cloud-e2e/lambda/run-lambda-container.test.js

We now build `x86_64` and `arm64` images. Fargate will use `x86_64` image by default (as it currently does), and Fargate will use `arm64` by default (as it currently does).
Notes:
- We don't test against `arm64` in PRs due to how long it takes to build. We will make some changes separately to run that in main against a canary
- Lambda functions will contain the architecture in the name to piggyback on existing name mechanism to determine if a new function is needed

feat(cli): use correct architecture in worker images

---

packages/artillery/lib/platform/aws-lambda/index.js

When using the aws-lambda platform for running tests and using a VPC, it often takes a little longer for the function to become ready that it does when creating the lambda without a VPC. When the lambda doesn't get created in time that leaves things in an inconsistent state, as the lambda is also never cleaned up. To avoid changing the behaviour when not using a VPC, this change adds a check before starting the wait for lambda flow. If the lambda is going to be connected to a VPC it sets the wait timeout to 4 minutes, otherwise it sets it to the current value of 2 minutes.
This issue happens fairly regularly, the effect being a failed test run:
and an orphaned lambda floating in the aws account:
I'm afraid I didn't open an issue first (or write tests) since the change is extremely …

fix(aws-lambda): wait a little longer for the lambda when using a VPC

---

packages/artillery-engine-playwright/index.js

Print an error message when a Playwright test function can't be loaded. This can happen if a `testFunction` or `flowFunction` attribute specifies a function that does not exist, or if the attribute is missing.

feat: warn when a Playwright test function can't be found

---

packages/artillery-plugin-slack/index.js
packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/create-bom/built-in-plugins.js
packages/artillery/lib/platform/aws-ecs/legacy/plugins.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws-lambda/lambda-handler/a9-handler-index.js

- Manually instantiating the plugin  in `run-cluster.js` similar to `ensure` plugin. ( plugins are not automatically loaded in main thread for Fargate runs)
- Disabling `slack` in cloud workers to avoid sending duplicate notifications.
- Setting the `global.artillery.cloudEnabled` variable in `run-fargate`. `slack` uses this variable to check if a run URL needs to be included in the notification. It is set in `run.js` when cloud is enabled but was missing in `run-fargate`
- Adding `slack` to both official plugin lists
- Setting the `WORKER_ID` to `process.env`
- Works with containerized Lambda (tested manually) and _**should**_ work with `.zip file`  version but can't test easily as local changes from other unreleased packages aren't reflected
-  As a tweak to `duration` - `seconds` are …

fix(slack): make slack work with distributed tests

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/metrics.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/http.js
packages/artillery-plugin-publish-metrics/lib/open-telemetry/tracing/playwright.js
packages/artillery/test/cloud-e2e/fargate/dd-adot.test.js

Multiple changes in OTel:
1. `url` attribute is added to page spans in Playwright tracing 
2. fix for  bug in Playwright tracing support - using `url` attribute instead of `name` is used along with `vu.uuid` to match web vitals with appropriate `pageSpan` (`replaceSpanNameRegex` introduced a bug where web vitals would not appear for spans with replaced names) 
3.  remove `test_id` being added by default to OTel metrics
4. Request timing phases  are recorded as attributes instead of spans in HTTP tracing for the purpose of reducing the cost. (e.g. `dns_lookup` span is now  `dns_lookup.duration` attribute with a value in `ms` set on the request span it belongs to.) 
- **!This will change the structure of traces for HTTP engine support** 
Tested manually, and will be added to OTel tracing …

feat(publish-metrics): implement multiple otel improvements

---

packages/artillery-engine-playwright/index.js

fixes #2785
`0` is a falsy value, so `0 || 30` will get `30` which is not what we want (`0` is a valid timeout setting, meaning no timeout).
I've used `Number` instead of `parseInt`, which is less verbose and in our case just better.
Maybe styling is not good, I'll look at the PR checks (edit: seems like they are skipped for the moment, let me know).
Speaking of lengh of lines, I found out two new questions :
- why are the setting in seconds instead of millis like the playwright config ? Isn't it just reducing the possibilities, for no gain (and les readable code here) ?
- where is `defaultPageTimeout` coming from ? It does not exist in playwright, and is not mentioned in artillery's doc neither. (so as you see I did not added a falsy protection on it)
**This is for use by the Artillery …

fix: accept 0 values for defaultNavigationTimeout and defaultTimeout

---

examples/README.md
examples/refresh-auth-token/README.md
examples/refresh-auth-token/refresh.mjs
examples/refresh-auth-token/refresh.yml

An example for a common use-case of needing to refresh a short-lived auth token used by individual VUs.

feat: add example for refreshing short-lived auth tokens

---

.github/workflows/s3-publish-cf-templates.yml

This will be part of a larger task to create and publish codified CF templates for IAM permissions needed for Artillery.
In order to test the workflow e2e, it must exist already on `main`, so just creating a dummy workflow first.

ci: add action for publishing cf templates to s3

---

.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-all-packages.yml
.github/workflows/run-aws-tests-on-pr.yml
.github/workflows/run-distributed-tests.yml
packages/artillery-engine-playwright/test/fargate.aws.js
packages/artillery/test/cloud-e2e/fargate/bom.test.js
packages/artillery/test/cloud-e2e/fargate/cw-adot.test.js
packages/artillery/test/cloud-e2e/fargate/dd-adot.test.js
packages/artillery/test/cloud-e2e/fargate/ensure-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/expect-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/memory.test.js
packages/artillery/test/cloud-e2e/fargate/misc.test.js
packages/artillery/test/cloud-e2e/fargate/processors.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-dotenv.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-ensure.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-smoke.test.js

This gives us the ability to run tests after NPM publish (canary or mainline).
Follow up of https://github.com/artilleryio/artillery/pull/2805.
Triggers the reusable workflow for AWS tests from NPM publish workflows, overriding the new `A9_PATH` env variable with the path to a locally freshly installed NPM version (after publish). Tests will then use that version rather than local workspace version.

ci(test): run aws tests against published versions

---

packages/core/lib/engine_http.js

Fixes `config.http.defaults.strictCapture` not being taken into account when set to "false". Change to an explicit check to avoid it being set to `undefined` with current check.

fix(http): check if default strictCapture is set to false

---

packages/artillery/lib/cmds/run-lambda.js
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-dotenv.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-ensure.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-smoke.test.js

Remove unnecessary `--container` flag. This was a temporary measure while we improved Lambda, but is now unnecessary, and will only affect people specifically on version `2.0.12` where `--container` was not the default.

feat(lambda): remove --container flag

---

packages/artillery/lib/platform/aws-lambda/index.js

This PR slightly changes how the function creation works. We now hash any changeable config and add that to the name, so that a change in config is handled properly. This prevents a function update on the same function causing some of the invokes to use one function configuration, and other invokes another.
Additionally, we also look for `ResourceConflictException` when creating the function, so that if a function already exists that looks like that, we don't create another.

fix(lambda): handle function creation conflicts correctly

---

packages/artillery/test/cloud-e2e/fargate/bom.test.js

Noticed the right version isn't being picked up by this specific test. Need to use `zx` so the path to the executable will be correctly overridden by the workflow.

test(cli): use zx with env vars on simple bom fargate test

---

packages/artillery-plugin-expect/index.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/test/cloud-e2e/fargate/expect-plugin.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js

This PR removes the error messages that show up when running expect in distributed tests (`Worker exited with an error, worker ID = <id>`) by giving a specific exit code to expect that can be caught in distributed tests.
This may get further improvements in the future, but right now it's the easiest way to avoid the confusing error message.

fix(cli): remove worker error message when expect errors in workers

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json
packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

Updates Playwright engine to https://github.com/microsoft/playwright/releases/tag/v1.44.1.
These are all fixes for regressions.

dep(playwright): update Playwright to v1.44.1

---

packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker

Fix handling of `SIGTERM`:
- Exit with appropriate exit code (143) from the `run` command
- On Fargate (e.g. when stopped early by Fargate Spot, or via explicit task stop, e.g. through `aws ecs stop-task`) - replace the use of `wait` with `timeout`. `wait` cannot be used for processes that run in a subshell - https://github.com/artilleryio/artillery/blob/27fae398ce0d6bab5f4226e361a9de6d4d8bec2a/packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker#L277

fix: handle SIGTERM correctly on Fargate

---

packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Trying to run a test on an ECS EC2 container with `artillery run-fargate --launch-type ecs:ec2` currently fails because Artillery tries to set cpu/memory config explicitly for ADOT containers on ECS EC2, which does not always exist.

fix(ecs): set ADOT's cpu/memory config only if the container exists

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws/aws-cloudwatch.js

A couple of ECS related things:
* Follow up to #3192. The fix in that PR did not work as intended because the array would always contain 2 elements
* Introduce `run-ecs` alias for `run-fargate`. This will be useful in future to make things less ambiguous when we add support for Amazon EKS, which also supports Fargate as a capacity provider.
* A couple of tweaks/fixes to copy

feat: a few ECS-related tweaks

---

.github/workflows/npm-publish-all-packages-canary.yml
.github/workflows/npm-publish-all-packages.yml
.github/workflows/run-distributed-tests.yml
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-dotenv.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-ensure.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-smoke.test.js

Change lambda tests that run against canary or mainline published versions to run against `arm64` (except for one, which remains as a smoke test for `x86_64`). Possible to do after https://github.com/artilleryio/artillery/pull/2807.

ci(test): run arm64 lambda tests in main

---

package-lock.json
packages/core/package.json

`punycode` is showing a deprecation notice when running the CLI on Node 21+. From what I can tell, this is coming from `tough-cookie`, and they've solved the issue on the unreleased version 5. From what I've read, this is mostly a rewrite to Typescript, and should not contain functional changes. It's unknown when they'll officially release it.

dep(core): use rc of tough-cookie to fix deprecated package

---

packages/artillery/lib/platform/aws-ecs/ecs.js

Adding a 30s wait after creating the IAM `artilleryio-ecs-worker-role` in order to make sure the IAM role is created and ready before using it. 
When a Fargate test runs for the first time on an AWS account, Artillery creates the `artilleryio-ecs-worker-role`, but doesn't wait before attempting to use the role. 
While creating the e2e tests in https://github.com/artilleryio/artillery/pull/2800 it was found that sometimes the IAM role is not ready in time an the following error occurs:
This is added because it was discovered that in some occasions the `artilleryio-ecs-worker-role` will not be ready in time and the following error will occur:
`ClientException: ECS was unable to assume the role 'arn:aws:iam::***:role/artilleryio-ecs-worker-role' that was provided for this task. Please verify …

fix(fargate): wait for ECS worker role to be available

---

packages/artillery/test/cli/async-hooks-esm.test.js
packages/artillery/test/cli/command-run.test.js
packages/artillery/test/cli/run-typescript.test.js
packages/artillery/test/cloud-e2e/fargate/bom.test.js
packages/artillery/test/cloud-e2e/fargate/cw-adot.test.js
packages/artillery/test/cloud-e2e/fargate/dd-adot.test.js
packages/artillery/test/cloud-e2e/fargate/ensure-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/expect-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/misc.test.js
packages/artillery/test/cloud-e2e/fargate/processors.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-dotenv.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-ensure.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-smoke.test.js
packages/artillery/test/helpers/expectations.js

We have an open issue regarding negative/null values in report (https://github.com/artilleryio/artillery/issues/2774). We haven't been able to replicate this, so we'll be adding these assertions to our test suite to see if it's able to replicate it.
It wasn't added to every test, since some use the output rather than a report for assertions. We can refactor some of the older tests that still use output, and then include this additional assertion separately.

test(cli): add assertions for not containing negative summaries

---

packages/artillery/test/publish-metrics/tracing/http-trace.test.js
packages/artillery/test/publish-metrics/tracing/playwright-trace.test.js

There were a few occasions that the publish-metrics trace tests failed. I was not able to reproduce the issue but from the existing logs it seemed as the second test would use the report of the first one. 
These tests are within a single file and use `beforeEach` and `afterEach` to set `report` and `trace` file paths. The paths were not set on the test `context` though, I added them directly on the test context here to make sure each is explicitly using their own paths.

refactor(test): set report and trace file paths to test context

---

.github/workflows/run-distributed-tests.yml
.github/workflows/scripts/npm-command-retry.sh

Tests are occasionally failing in an `npm install` step ([example](https://github.com/artilleryio/artillery/actions/runs/9759298237/job/26936970178)) that happens in main, seemingly due to intermittent network issues.
This PR creates a bash script to retry npm commands. If needed we can use this in more places in the future, but I've only seen this issue in these 2 install steps in recent history.

ci(test): retry npm install in distributed tests

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json
packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

Upgrade to [Playwright v1.45.0](https://github.com/microsoft/playwright/releases). There are no mentioned breaking changes in this release, but there are a few API improvements in `playwright` and `@playwright/test`.

dep(playwright): update playwright version to v1.45.0

---

packages/artillery/test/cloud-e2e/fargate/bom.test.js
packages/artillery/test/cloud-e2e/fargate/cw-adot.test.js
packages/artillery/test/cloud-e2e/fargate/dd-adot.test.js
packages/artillery/test/cloud-e2e/fargate/ensure-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/expect-plugin.test.js
packages/artillery/test/cloud-e2e/fargate/misc.test.js
packages/artillery/test/cloud-e2e/fargate/processors.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-dotenv.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-ensure.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-expect.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-smoke.test.js
packages/artillery/test/helpers/expectations.js

There's a reported issue for a single user in which not all of the intermediates seem to be being accounted for in the aggregate (despite appearing in Cloudwatch). We haven't been able to reproduce it, so we are adding a check for it in distributed tests.

test(cli): add check for intermediates matching aggregates in aws tests

---

.github/workflows/s3-publish-cf-templates.yml
packages/artillery/lib/platform/aws/iam-cf-templates/gh-oidc-fargate.yml
packages/artillery/lib/platform/aws/iam-cf-templates/gh-oidc-lambda.yml

Adding new CloudFormation templates with IAM resources required to run Artillery tests on AWS Fargate/Lambda from GitHub Actions.
A version of templates created [here](https://github.com/artilleryio/artillery/pull/2800) that configure the GitHub OIDC trust relationship. 
The templates take the following parameters:
- `GitHubRepository` - (orgname/reponame) - GitHub repository to set the OIDC for
- `GitHubBranch` - (optional) - GitHub branch to allow access for. Defaults to `*` all branches
- `GitHubOIDCProviderArn` -  The ARN of the existing GitHub Identity Provider if one exists, if left empty the GitHub Identity Provider will be created by the CF stack along with the IAM role
Resources created:
- `ArtilleryGitHubOIDC{Lambda/Fargate}Role` with an inline …

feat(ci): provide a separate CloudFormation stack for GitHub OIDC setup

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json
packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

Upgrades Playwright from 1.45.0 to [1.45.2](https://github.com/microsoft/playwright/releases/tag/v1.45.2). These releases include bug fixes from regressions introduced in 1.45.0.

dep(playwright): update playwright version to v1.45.2

---

packages/artillery-plugin-metrics-by-endpoint/index.js
packages/artillery-plugin-metrics-by-endpoint/test/fixtures/scenario-templated-url.yml
packages/artillery-plugin-metrics-by-endpoint/test/index.spec.js
packages/artillery-plugin-metrics-by-endpoint/test/index.unit.js
packages/artillery/test/cloud-e2e/fargate/fixtures/cli-kitchen-sink/kitchen-sink.yml
packages/types/schema/plugins/metrics-by-endpoint.js

By default, we will start setting a `req.name` equal to the non-templated url. This solves the issue with reports getting too big when users don't set `req.name`, which is particularly relevant in Cloud Dashboard, where it becomes unreadable. It will now look like this:
Users can opt-out of this behaviour by setting `groupDynamicURLs: false` in their config.

feat(cli): set nontemplated url as req name by default in metrics

---

packages/artillery/lib/launch-platform.js
packages/artillery/lib/platform/aws-lambda/index.js
packages/artillery/lib/platform/local/index.js
packages/artillery/test/cloud-e2e/fargate/fixtures/memory-hog/memory-hog.yml

After these changes the `Launcher` class will delegate more of how a test is run down to the actual implementation of the runtime platform (e.g. local, AWS Lambda, AWS ECS or something else).
It will no longer manage workers directly via `createWorker()`, `prepareWorker()` etc.
The only concerns handled in Launcher now are to:
- Initialize a specific platform implementation (e.g. AWS Lambda)
- Subscribe to events emitted by the platform
- Worker-level events such as `'stats'` or `'phaseCompleted'` and aggregate metric reports from multiple workers
These changes make it easier to implement support for new platforms and to move the existing AWS ECS implementation over to use the `Launcher` abstraction.
**This is for use by the Artillery team. Please leave this in if you're contributing to …

refactor: make the Launcher abstraction less opinionated

---

.github/workflows/run-distributed-tests.yml
.github/workflows/run-tests.yml
packages/artillery/package.json
packages/artillery/test/cloud-e2e/fargate/bom.test.js
packages/artillery/test/cloud-e2e/fargate/processors.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-bom.test.js
packages/artillery/test/cloud-e2e/lambda/lambda-smoke.test.js
packages/artillery/test/helpers/index.js

Adding an additional job that runs in parallel with jobs on linux. These tests are non-blocking for now due to stability, and the run will fail, as there's currently a Windows bug. We can use this setup to fix the bug. A notification will be sent to the channel when one of these tests fail.
I was planning on only running them on main, but this is easier to setup and get immediate feedback, especially when we're fixing things on branches.

ci(tests): add windows tests to CI as non blocking

---

packages/core/lib/runner.js

fix(core): import mjs path correctly when running on windows

---

packages/artillery/lib/platform/aws-lambda/lambda-handler/a9-handler-index.js

https://github.com/artilleryio/artillery/pull/3291 introduced a regression to Lambda tests by [removing the installation](https://github.com/artilleryio/artillery/pull/3291/files#diff-a33800f8944e9e0680e8427bdbe98ef51764c448e6681c5a68737ca2c304fc19L43) of the `artillery-plugin-sqs-reporter`. This was anyway a piece of tech debt, as it's better to set the path to the plugin code that is bundled with the Artillery source code.

fix(lambda): set plugin path to plugin folder and test data folder

---

packages/core/lib/runner.js

- Should solve https://github.com/artilleryio/artillery/issues/3268
- Adds a warning when `loadAll` is set without `name`
Automated tests need to be added for all the possible options (there aren't any existing ones that check these options). I'll handle that separately to get the fix out now.
However, I have tested manually all cases:
- `loadAll:true, name:something`: this is the bug, resolves it by not setting the random key:value pairs on the root, and only setting the whole csv
- `loadAll:undefined, name:something`: remains the same (sets the data under the name key, but also sets the random key:value pairs).
- `loadAll:true, name:undefined`: previously would set a random key:value pair on the root. This doesn't make sense, as there is a clear intent to load all data. Now logs a …

fix(core): prevent setting random fields when using loadAll

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Add ability to customize two settings for Artillery workers on ECS:
- `--container-dns-servers` can now be used to set the `dnsServers` setting for the Artillery container
- `--ephemeral-storage` can now be used to set the amount of ephemeral storage for the worker task

feat(ecs): add ability to set DNS servers and ephemeral storage size

---

packages/core/lib/runner.js

Fix issue where Artillery prints a warning when running a test with a payload that does not set `loadAll`.
https://github.com/artilleryio/artillery/pull/3277#issuecomment-2272522330

fix: don't print a warning when loadAll is not set

---

packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker

This change makes sure that files such as custom .npmrc config are made available to the worker on Azure.

fix: make hidden files available to Azure worker

---

packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/lib/platform/az/aci.js

- Bundle dotenv files when running tests on Azure
- Improve error handling for container provisioning errors on Azure

Azure improvements

---

packages/core/lib/engine_http.js
packages/core/test/unit/engine_http.test.js

Based on this discussion: https://github.com/artilleryio/artillery/discussions/3315
Support `contentType` when building a request with `formData`. Example:
```yaml
- post:
name: Post activity
url: /climate
formData:
activity: '{{ activity }}'
type: '{{ type }}'
photo:
fromFile: './photo.png'
climate:
value: '{"temperature": "{{ climate.temperature }}", "unit": "{{ climate.unit }}"}'
contentType: application/json
expect:
- statusCode: 201
```

feat(core): specify a Content-Type for individual values when building a formdata request

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/cloud/cloud.js

This helps detect a common issue on corporate networks where a firewall is blocking POST requests to unknown domains.

feat(cloud): check that POST requests can be made when Cloud is enabled

---

packages/artillery/lib/cli/common-flags.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js

Add `--name` option to all run commands (`run`, `run-lambda`, `run-ecs` and `run-aci`).
The option can be used to set the name of the test that will be shown in Artillery Cloud.
Shorthand for setting the `name` tag. Overrides the `name` tag if that's also set via `--tags`.

feat: add --name option for setting test names in Artillery Cloud

---

packages/core/lib/engine_http.js

Track response time by status code (2xx, 3xx, 4xx, and 5xx).
New metrics that will be emitted:
- `http.response_time.2xx`
- `http.response_time.3xx`
- `http.response_time.4xx`
- `http.response_time.5xx`
Why the change is needed, and any details to help code reviewers.

feat(http): track response time by status code

---

packages/artillery-plugin-publish-metrics/lib/open-telemetry/index.js

`resourceAttributes` may now be used to set resource [1] level attributes when reporting via Open Telemetry.
```yaml
config:
plugins:
publish-metrics:
- type: 'open-telemetry'
resourceAttributes:
service.name: Artillery.io
custom-attribute: some-value
```
Original discussion: https://github.com/artilleryio/artillery/discussions/3333
1. https://opentelemetry.io/docs/languages/js/resources/

feat: allow setting resource-level attributes for OpenTelemetry

---

package-lock.json
packages/artillery/lib/platform/cloud/cloud.js
packages/artillery/package.json

If the test is running in CI, set isCI true and send the name of the CI service to Artillery Cloud as part of test's metadata.
This will be shown in reports and available as a property to filter & search on too.

feat: send CI status to cloud

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json
packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

Upgrade to most recent release of Playwright (v1.48.0)

dep: upgrade to Playwright 1.48.0

---

packages/artillery/lib/platform/cloud/cloud.js

If an Artillery test is running on GitHub Actions, send the job URL to Artillery Cloud.
This will let the Artillery Cloud reports to link back to the GHA job run that triggered the test.

feat: send GHA job URL to cloud for tests running on GHA

---

package-lock.json
packages/artillery-engine-playwright/Dockerfile
packages/artillery-engine-playwright/package.json
packages/artillery-engine-playwright/test/index.test.js
packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js
packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

This PR contains two fixes:
1. `awscli` is no longer available via apt in the version of Ubuntu that Playwright's 1.48.0 image is based on & we need to install it in a different way.
2. `amazon/aws-otel-collector` released a breaking change in v0.40.0 so we're explicitly pinning to v0.39.0 for now

fix: update worker Docker image

---

packages/commons/engine_util.js

This updates the JSON parse logic so that it returns what is requested by the user using the [JSONpath-plus](https://www.npmjs.com/package/jsonpath-plus) standard queries
refactors the `extractJSONPath` function to improve its flexibility and simplify its implementation.

feat(JSONPath-Plus): Use library correctly

---

examples/browser-load-testing-playwright/README.md
examples/browser-load-testing-playwright/browser-smoke-test.yml
examples/browser-load-testing-playwright/flows.js
examples/browser-load-testing-playwright/pages.csv

The example will currently check only one page by default unless a `config.phases` section is added with the number of VUs matching the number of rows. This PR fixes that:
- Use `loadAll` to always load all rows in the CSV file and only run one VU (instead of relying on creating the right number of VUs)
- Update the checks in the CSV file
Reported in https://github.com/artilleryio/artillery/discussions/3367

docs: update browser smoke test example

---

packages/artillery/lib/platform/az/aci.js

Seeing some cases where starting up large (80+ workers) load tests on ACI seems to exceed some underlying Azure Blob Storage limits with multiple containers all accessing the same blob container concurrently.
With this change Artillery will pause for up to 10 seconds after launching every batch of 10 workers.

feat: stagger startup of containers on Azure

---

packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

Docker builds for arm64 have been broken since https://github.com/artilleryio/artillery/pull/3363
The issue is caused by:
- An issue with curl/OpenSSL specific to Ubuntu 24 on arm64:
- https://github.com/curl/curl/issues/14154
- https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2073448
- Our image uses Ubuntu 24 now as that's what the Playwright v1.48.0 image is based on

fix: use wget instead of curl to install az CLI

---

packages/artillery/lib/cli/common-flags.js
packages/artillery/lib/platform/az/aci.js

* Make values from a file specified with `--dotenv` available to workers on Azure
* Introduce `--env-file` as an alias for `--dotenv`

feat: env file improvements

---

packages/artillery/lib/platform/az/aci.js

Allow for the worker image to be overridden on Azure via `WORKER_IMAGE_URL` environment variable (same as on AWS Lambda and Fargate). Useful for development & debugging.

feat: allow worker image overrides on Azure

---

packages/artillery/lib/platform/aws-ecs/worker/loadgen-worker

The current cleanup() code will attempt to remove files from Blob Storage in every worker in a test. This can lead to the following issue:
- User launches a test with a lot of workers (e.g. 100)
- Workers 1 to 50 launch and boostrap successfully
- Worker 51 encounters an error and exits early
- Workers 52 onwards won't be able to download test-related assets from Blob Storage anymore, and will fail
The main problem with this is that this makes debugging the actual cause of a failure much harder, as container logs will be polluted with errors related to inability to download test assets.

fix: remove files in Azure Blob Storage only once per test run

---

packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

This change temporarily disables SSL verification in `curl` at build time on ARM64 only. This is a workaround to have ARM64 builds working again, see https://github.com/artilleryio/artillery/pull/3375

fix: disable SSL verification on arm64 as a workaround

---

.github/workflows/npm-publish-all-packages-canary.yml

Disabling ARM64 builds & tests for canary releases - those can take upwards of 35m at a time.

ci: disable ARM64 builds & tests for canary releases

---

packages/artillery/lib/util/prepare-test-execution-plan.js

fix: handle case when config.target is set to a remote env var

---

.github/workflows/examples.yml
examples/browser-load-testing-playwright/README.md
examples/browser-load-testing-playwright/browser-load-test.ts
examples/browser-load-testing-playwright/browser-smoke-test.ts
packages/artillery-engine-playwright/index.js
packages/artillery/lib/artillery-global.js
packages/artillery/lib/cmds/quick.js
packages/artillery/lib/cmds/run.js
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/lib/platform/local/artillery-worker-local.js
packages/artillery/lib/platform/local/index.js
packages/artillery/lib/platform/local/worker.js
packages/artillery/lib/util/prepare-test-execution-plan.js
packages/artillery/test/cloud-e2e/fargate/misc.test.js

This PR adds support for defining Artillery + Playwright load tests entirely in TypeScript:
- `config` and `scenario` sections map exactly onto their YAML equivalents
- `config.processor` is no longer needed - test functions can be defined inline (or imported from another existing module)
**Known limitations & issues:**

feat: define Artillery + Playwright tests fully in TypeScript

---

package-lock.json
packages/artillery-engine-posthog/index.js
packages/artillery-engine-posthog/package.json
packages/artillery/package.json
packages/skytrace/package.json

See https://github.com/advisories/GHSA-wf5p-g6vw-rhxx. This affects the `0.8.1 - 0.27.2` versions of `axios`, which affects the `<=1.3.0 || 2.1.0 - 3.1.2` versions of `posthog-node`, so I upgraded the latter to 4.1.2.
Fixes https://github.com/artilleryio/artillery/issues/2519.
Please find the breaking changes of `posthog-node` here:
https://github.com/PostHog/posthog-js-lite/blob/main/posthog-node/CHANGELOG.md

dep: upgrade posthog-node to fix moderate vulnerability

---

packages/artillery/Dockerfile

The current docker container can't run playwright scripts since the required playwright browsers are missing, this PR fixes that by pre-installing them

Pre-install browsers in docker container

---

packages/artillery/lib/cmds/run-fargate.js
packages/artillery/lib/platform/aws-ecs/ecs.js

resolved #3470 
Allow specifying a custom task role name when running Artillery on Fargate, with a fallback to the default worker role. This provides more flexibility in IAM role configuration during Fargate test runs.
currently there isn't a way to pass a custom role name for tasks to assume. In `PlatformECS.init` it always looks for the default role name. this fixes it by passing the `task-role-name` flag to PlatformECS

fix: optional task role name in Fargate run command

---

packages/artillery/lib/platform/aws-ecs/legacy/sqs-reporter.js

* Number of consumers no longer hardcoded at 30. Instead, one consumer will be created per 10 workers in the test
* Number of consumers may be overridden via SQS_CONSUMER_POOL_SIZE environment variable

feat: set number of SQS consumers dynamically

---

examples/browser-load-testing-playwright/browser-load-test.ts
packages/artillery/lib/platform/local/index.js

- Update a Playwright TypeScript example to show how to use a `before` hook
- Disable worker threads for Playwright tests:
- Fixes/avoids current issue of load tests written in TypeScript not respecting `phases` config. Because each worker re-imports the script, the original phase configuration is preserved, which leads to the load being multiplied rather than distrubuted.
- There's no performance benefit to multiple threads in this case anyway because the actual work will happen in an external Chrome process

Playwright improvements

---

packages/artillery-plugin-slack/index.js

When a large amount of checks are defined, users were hitting a Slack error around the message length limit. The same was also happening when a test would have a large amount of errors.
- Adds limits around showing checks and errors, show summary if too many
- Improve message formatting following Slack guidelines
| Before | After |
| --- | --- |
| ![before](https://github.com/user-attachments/assets/217af953-7c47-49f0-a0c6-3cedaffbe2e7) | ![after](https://github.com/user-attachments/assets/3f1d8523-dc33-4f8e-a247-f061df3de558) |
| ![before](https://github.com/user-attachments/assets/fde7eac8-87d8-420c-8124-7be0a02484bd) | ![after](https://github.com/user-attachments/assets/5d71e6eb-0855-4535-b8c3-3868ba067516) |
| ![before](https://github.com/user-attachments/assets/8d0fd52b-e3b7-401a-aff4 …

feat: Slack plugin improvements

---

packages/artillery-plugin-slack/index.js

Some Slack messages are showing the test as failed even though it passed. This is only on the header text, so trying to rule out the exit code being `null`. Checks and errors are showing correctly.

fix: check if exit code is not null before sending message

---

packages/artillery-plugin-ensure/README.md
packages/artillery-plugin-expect/README.md

Update links to Artillery Docs.

docs: update links for ensure and expect docs

---

packages/artillery/test/publish-metrics/tracing/playwright-trace.test.js

The test has been failing since upgrading to Playwright v1.51.0 but based on an initial investigation does not seem to be related to the version upgrade. The functionality still works, so marking as skipped test for now.

test: skip flaky OTel test for now

---

packages/artillery/lib/cmds/run-aci.js
packages/artillery/lib/platform/az/aci.js

We won't allow setting those values via CLI flags anymore so that authentication relies only on [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/javascript/api/overview/azure/identity-readme?view=azure-node-latest#defaultazurecredential).

feat(azure): require that client id and secret are set via env vars

---

packages/artillery/lib/platform/aws-ecs/legacy/constants.js
packages/artillery/lib/platform/az/aci.js

* Allow the default worker provisioning timeout to be customized on Azure ACI (similarly to what's already available for AWS ECS)
* The override on both ACI and ECS is now via the `WORKER_WAIT_TIMEOUT_SEC` environment variable. The legacy AWS ECS-specific `ECS_WAIT_TIMEOUT` env var is still supported.

feat: allow worker timeout override on Azure ACI

---

examples/browser-load-testing-playwright/browser-load-test.ts
packages/artillery/lib/platform/aws-ecs/legacy/bom.js
packages/artillery/test/unit/fargate-bom.test.js

Fixes an issue where a self-contained TypeScript test definitions wouldn't get bundled as expected, resulting in nothing being uploaded to S3 / Blob Storage bucket.

fix(bom): make sure self-contained TS scripts are bundled as expected

---

packages/artillery/lib/platform/az/aci.js

Follow up to https://github.com/artilleryio/artillery/pull/3527
The value of `WAIT_TIMEOUT_SEC` needs to be passed into worker containers as well to avoid them timing out while waiting for other workers to start.

fix(azure): pass value of WAIT_TIMEOUT_SEC into worker containers

---

packages/artillery-engine-playwright/index.js
packages/artillery/lib/platform/cloud/cloud.js

- Increase max wait time for assets to be uploaded to 5m up from 30s. This helps in cases where there may be several large trace files that need to be uploaded.
- Increase the default number of concurrent recordings to 5 from 3 - this helps increase the probability that a recording from a failed VU will be captured

feat: improve Playwright trace capture

---

packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

The `packageManager` field in the top-level `package.json` file can cause issues with projects using Yarn, see: https://github.com/yarnpkg/yarn/issues/9015

fix: remove top-level (monorepo) package.json from Dockerfile

---

packages/artillery/lib/platform/local/artillery-worker-local.js
packages/artillery/lib/platform/local/worker.js

When the main script is a TypeScript file it gets transpiled in the main thread, and each worker thread then loads the transpiled module. This "resets" the results of divideWork() call, i.e. each worker runs with the original values of config.phases rather than the ones adjusted to distribute the work across all workers.
With this change, each worker receives a phase configuration for a subset of overall phase profile.
Fixes https://github.com/artilleryio/artillery/issues/3546

fix: take distributed phases into account in TypeScript scripts

---

packages/artillery-plugin-slack/index.js

- Use `formatDuration()` function from `packages/artillery/lib/utils.js` for consistency
- Check if `lastMetricAt` and `firstMetricAt` are defined before calculating duration
- Only report duration if the value is valid
- Add exit code fallback in cases where is not set in time

fix: slack plugin not reporting duration and status correctly

---

packages/artillery-plugin-apdex/index.js

Fix Apdex score not showing at the end of the test run if threshold is set under `config.plugins.apdex`.

fix: apdex score not showing

---

packages/artillery/types.d.ts

Add initial set of type definitions for Playwright scripts written in TypeScript.

feat: add type definitions for Playwright tests
